// @generated by packages/ibex-devtools/src/scripts/generate-module-manifest.ts
// Do not edit by hand.

#[rustfmt::skip]
pub(crate) const BUILTIN_MANIFEST_REGISTRATIONS: &[BuiltinManifestRegistration] = &[
    BuiltinManifestRegistration { specifier: r"exact:process", source_key: r"exact_process" },
    BuiltinManifestRegistration { specifier: r"exact:crypto", source_key: r"exact_crypto" },
    BuiltinManifestRegistration { specifier: r"exact:clipboard", source_key: r"exact_clipboard" },
    BuiltinManifestRegistration { specifier: r"exact:http", source_key: r"exact_http" },
    BuiltinManifestRegistration { specifier: r"exact:sqlite", source_key: r"exact_sqlite" },
    BuiltinManifestRegistration { specifier: r"bun:sqlite", source_key: r"exact_sqlite" },
    BuiltinManifestRegistration { specifier: r"bun:fs", source_key: r"node_fs" },
    BuiltinManifestRegistration { specifier: r"node:fs", source_key: r"node_fs" },
    BuiltinManifestRegistration { specifier: r"fs", source_key: r"node_fs" },
    BuiltinManifestRegistration { specifier: r"node:process", source_key: r"exact_process" },
    BuiltinManifestRegistration { specifier: r"process", source_key: r"exact_process" },
    BuiltinManifestRegistration { specifier: r"bun:fs/promises", source_key: r"node_fs_promises" },
    BuiltinManifestRegistration { specifier: r"node:fs/promises", source_key: r"node_fs_promises" },
    BuiltinManifestRegistration { specifier: r"fs/promises", source_key: r"node_fs_promises" },
    BuiltinManifestRegistration { specifier: r"internal/fs/promises", source_key: r"node_fs_promises" },
    BuiltinManifestRegistration { specifier: r"node:path", source_key: r"node_path" },
    BuiltinManifestRegistration { specifier: r"path", source_key: r"node_path" },
    BuiltinManifestRegistration { specifier: r"node:path/posix", source_key: r"path_posix_alias" },
    BuiltinManifestRegistration { specifier: r"path/posix", source_key: r"path_posix_alias" },
    BuiltinManifestRegistration { specifier: r"node:path/win32", source_key: r"path_win32_alias" },
    BuiltinManifestRegistration { specifier: r"path/win32", source_key: r"path_win32_alias" },
    BuiltinManifestRegistration { specifier: r"node:crypto", source_key: r"exact_crypto" },
    BuiltinManifestRegistration { specifier: r"crypto", source_key: r"exact_crypto" },
    BuiltinManifestRegistration { specifier: r"node:events", source_key: r"node_events" },
    BuiltinManifestRegistration { specifier: r"events", source_key: r"node_events" },
    BuiltinManifestRegistration { specifier: r"node:stream", source_key: r"node_stream" },
    BuiltinManifestRegistration { specifier: r"stream", source_key: r"node_stream" },
    BuiltinManifestRegistration { specifier: r"_stream_readable", source_key: r"legacy_stream_readable" },
    BuiltinManifestRegistration { specifier: r"_stream_writable", source_key: r"legacy_stream_writable" },
    BuiltinManifestRegistration { specifier: r"_stream_duplex", source_key: r"legacy_stream_duplex" },
    BuiltinManifestRegistration { specifier: r"_stream_transform", source_key: r"legacy_stream_transform" },
    BuiltinManifestRegistration { specifier: r"_stream_passthrough", source_key: r"legacy_stream_passthrough" },
    BuiltinManifestRegistration { specifier: r"node:stream/consumers", source_key: r"node_stream_consumers" },
    BuiltinManifestRegistration { specifier: r"stream/consumers", source_key: r"node_stream_consumers" },
    BuiltinManifestRegistration { specifier: r"node:stream/promises", source_key: r"node_stream_promises" },
    BuiltinManifestRegistration { specifier: r"stream/promises", source_key: r"node_stream_promises" },
    BuiltinManifestRegistration { specifier: r"node:buffer", source_key: r"node_buffer" },
    BuiltinManifestRegistration { specifier: r"buffer", source_key: r"node_buffer" },
    BuiltinManifestRegistration { specifier: r"node:util", source_key: r"node_util" },
    BuiltinManifestRegistration { specifier: r"util", source_key: r"node_util" },
    BuiltinManifestRegistration { specifier: r"sys", source_key: r"node_util" },
    BuiltinManifestRegistration { specifier: r"node:sys", source_key: r"node_util" },
    BuiltinManifestRegistration { specifier: r"util/types", source_key: r"util_types_alias" },
    BuiltinManifestRegistration { specifier: r"node:util/types", source_key: r"node_util_types_alias" },
    BuiltinManifestRegistration { specifier: r"node:timers", source_key: r"node_timers" },
    BuiltinManifestRegistration { specifier: r"timers", source_key: r"node_timers" },
    BuiltinManifestRegistration { specifier: r"node:timers/promises", source_key: r"node_timers_promises" },
    BuiltinManifestRegistration { specifier: r"timers/promises", source_key: r"node_timers_promises" },
    BuiltinManifestRegistration { specifier: r"node:http", source_key: r"node_http" },
    BuiltinManifestRegistration { specifier: r"http", source_key: r"node_http" },
    BuiltinManifestRegistration { specifier: r"_http_agent", source_key: r"node_http" },
    BuiltinManifestRegistration { specifier: r"_http_common", source_key: r"node_http" },
    BuiltinManifestRegistration { specifier: r"_http_server", source_key: r"node_http" },
    BuiltinManifestRegistration { specifier: r"_http_outgoing", source_key: r"node_http" },
    BuiltinManifestRegistration { specifier: r"_http_incoming", source_key: r"node_http" },
    BuiltinManifestRegistration { specifier: r"node:https", source_key: r"node_https" },
    BuiltinManifestRegistration { specifier: r"https", source_key: r"node_https" },
    BuiltinManifestRegistration { specifier: r"node:stream/web", source_key: r"node_stream_web" },
    BuiltinManifestRegistration { specifier: r"stream/web", source_key: r"node_stream_web" },
    BuiltinManifestRegistration { specifier: r"node:url", source_key: r"node_url" },
    BuiltinManifestRegistration { specifier: r"url", source_key: r"url_alias" },
    BuiltinManifestRegistration { specifier: r"node:os", source_key: r"node_os" },
    BuiltinManifestRegistration { specifier: r"os", source_key: r"node_os" },
    BuiltinManifestRegistration { specifier: r"node:tty", source_key: r"node_tty" },
    BuiltinManifestRegistration { specifier: r"tty", source_key: r"node_tty" },
    BuiltinManifestRegistration { specifier: r"node:assert", source_key: r"node_assert" },
    BuiltinManifestRegistration { specifier: r"assert", source_key: r"node_assert" },
    BuiltinManifestRegistration { specifier: r"node:assert/strict", source_key: r"node_assert" },
    BuiltinManifestRegistration { specifier: r"assert/strict", source_key: r"node_assert" },
    BuiltinManifestRegistration { specifier: r"node:string_decoder", source_key: r"node_string_decoder" },
    BuiltinManifestRegistration { specifier: r"string_decoder", source_key: r"node_string_decoder" },
    BuiltinManifestRegistration { specifier: r"node:querystring", source_key: r"node_querystring" },
    BuiltinManifestRegistration { specifier: r"querystring", source_key: r"node_querystring" },
    BuiltinManifestRegistration { specifier: r"node:punycode", source_key: r"node_punycode" },
    BuiltinManifestRegistration { specifier: r"punycode", source_key: r"node_punycode" },
    BuiltinManifestRegistration { specifier: r"node:child_process", source_key: r"node_child_process" },
    BuiltinManifestRegistration { specifier: r"child_process", source_key: r"node_child_process" },
    BuiltinManifestRegistration { specifier: r"node:readline", source_key: r"node_readline" },
    BuiltinManifestRegistration { specifier: r"readline", source_key: r"node_readline" },
    BuiltinManifestRegistration { specifier: r"node:readline/promises", source_key: r"node_readline" },
    BuiltinManifestRegistration { specifier: r"readline/promises", source_key: r"node_readline" },
    BuiltinManifestRegistration { specifier: r"node:module", source_key: r"node_module" },
    BuiltinManifestRegistration { specifier: r"module", source_key: r"node_module" },
    BuiltinManifestRegistration { specifier: r"node:zlib", source_key: r"node_zlib" },
    BuiltinManifestRegistration { specifier: r"zlib", source_key: r"node_zlib" },
    BuiltinManifestRegistration { specifier: r"node:tls", source_key: r"node_tls" },
    BuiltinManifestRegistration { specifier: r"tls", source_key: r"node_tls" },
    BuiltinManifestRegistration { specifier: r"node:dns", source_key: r"node_dns" },
    BuiltinManifestRegistration { specifier: r"dns", source_key: r"node_dns" },
    BuiltinManifestRegistration { specifier: r"node:dns/promises", source_key: r"node_dns_promises" },
    BuiltinManifestRegistration { specifier: r"dns/promises", source_key: r"node_dns_promises" },
    BuiltinManifestRegistration { specifier: r"internal/fs/utils", source_key: r"internal_fs_utils" },
    BuiltinManifestRegistration { specifier: r"node:net", source_key: r"node_net" },
    BuiltinManifestRegistration { specifier: r"net", source_key: r"node_net" },
    BuiltinManifestRegistration { specifier: r"node:perf_hooks", source_key: r"node_perf_hooks" },
    BuiltinManifestRegistration { specifier: r"perf_hooks", source_key: r"node_perf_hooks" },
    BuiltinManifestRegistration { specifier: r"node:async_hooks", source_key: r"node_async_hooks" },
    BuiltinManifestRegistration { specifier: r"async_hooks", source_key: r"node_async_hooks" },
    BuiltinManifestRegistration { specifier: r"node:worker_threads", source_key: r"node_worker_threads" },
    BuiltinManifestRegistration { specifier: r"worker_threads", source_key: r"node_worker_threads" },
    BuiltinManifestRegistration { specifier: r"node:vm", source_key: r"node_vm" },
    BuiltinManifestRegistration { specifier: r"vm", source_key: r"node_vm" },
    BuiltinManifestRegistration { specifier: r"node:console", source_key: r"node_console" },
    BuiltinManifestRegistration { specifier: r"console", source_key: r"node_console" },
    BuiltinManifestRegistration { specifier: r"node:cluster", source_key: r"node_cluster" },
    BuiltinManifestRegistration { specifier: r"cluster", source_key: r"node_cluster" },
    BuiltinManifestRegistration { specifier: r"node:dgram", source_key: r"node_dgram" },
    BuiltinManifestRegistration { specifier: r"dgram", source_key: r"node_dgram" },
    BuiltinManifestRegistration { specifier: r"node:domain", source_key: r"node_domain" },
    BuiltinManifestRegistration { specifier: r"domain", source_key: r"node_domain" },
    BuiltinManifestRegistration { specifier: r"node:v8", source_key: r"node_v8" },
    BuiltinManifestRegistration { specifier: r"v8", source_key: r"node_v8" },
    BuiltinManifestRegistration { specifier: r"node:constants", source_key: r"node_constants" },
    BuiltinManifestRegistration { specifier: r"constants", source_key: r"node_constants" },
    BuiltinManifestRegistration { specifier: r"ws", source_key: r"ws" },
    BuiltinManifestRegistration { specifier: r"node:http2", source_key: r"node_http2" },
    BuiltinManifestRegistration { specifier: r"http2", source_key: r"node_http2" },
    BuiltinManifestRegistration { specifier: r"node:diagnostics_channel", source_key: r"node_diagnostics_channel" },
    BuiltinManifestRegistration { specifier: r"diagnostics_channel", source_key: r"node_diagnostics_channel" },
    BuiltinManifestRegistration { specifier: r"node:trace_events", source_key: r"node_trace_events" },
    BuiltinManifestRegistration { specifier: r"trace_events", source_key: r"node_trace_events" },
    BuiltinManifestRegistration { specifier: r"node:inspector", source_key: r"node_inspector" },
    BuiltinManifestRegistration { specifier: r"inspector", source_key: r"node_inspector" },
    BuiltinManifestRegistration { specifier: r"node:inspector/promises", source_key: r"node_inspector" },
    BuiltinManifestRegistration { specifier: r"inspector/promises", source_key: r"node_inspector" },
    BuiltinManifestRegistration { specifier: r"node:wasi", source_key: r"node_wasi" },
    BuiltinManifestRegistration { specifier: r"wasi", source_key: r"node_wasi" },
];

#[rustfmt::skip]
pub const RUNTIME_GATED_NODE_BUILTINS: &[&str] = &[
    r"assert",
    r"async_hooks",
    r"buffer",
    r"child_process",
    r"cluster",
    r"console",
    r"constants",
    r"crypto",
    r"dgram",
    r"diagnostics_channel",
    r"dns",
    r"domain",
    r"events",
    r"fs",
    r"http",
    r"http2",
    r"https",
    r"inspector",
    r"module",
    r"net",
    r"os",
    r"path",
    r"perf_hooks",
    r"process",
    r"punycode",
    r"querystring",
    r"readline",
    r"repl",
    r"sqlite",
    r"stream",
    r"string_decoder",
    r"sys",
    r"timers",
    r"tls",
    r"trace_events",
    r"tty",
    r"url",
    r"util",
    r"v8",
    r"vm",
    r"wasi",
    r"worker_threads",
    r"zlib",
];

// Specifiers builtins require between themselves that the shared runtime's
// bootstrap module cache serves (or that are intentionally absent and guarded
// at the require site). The host manifest resolver refuses them by design, so
// graph materialization must treat such edges as call-time, not eager.
#[rustfmt::skip]
pub(crate) const BOOTSTRAP_INTERNAL_MODULE_SPECIFIERS: &[&str] = &[
    r"internal/util/debuglog",
    r"internal/linkedlist",
    r"internal/util",
    r"internal/util/inspect",
    r"internal/options",
    r"internal/http",
    r"internal/net",
    r"internal/async_hooks",
    r"internal/timers",
    r"internal/assert/myers_diff",
    r"internal/crypto/util",
    r"internal/crypto/x509",
    r"internal/url",
    r"internal/fs/utils",
    r"internal/test/binding",
    r"internal/child_process",
    r"stream/consumers",
    r"node:stream/consumers",
    r"stream/promises",
    r"node:stream/promises",
];

#[rustfmt::skip]
pub(crate) const BOOTSTRAP_INTERNAL_MODULE_SPECIFIERS: &[&str] = &[
    r"internal/util/debuglog",
    r"internal/linkedlist",
    r"internal/util",
    r"internal/util/inspect",
    r"internal/options",
    r"internal/http",
    r"internal/net",
    r"internal/async_hooks",
    r"internal/timers",
    r"internal/assert/myers_diff",
    r"internal/crypto/util",
    r"internal/crypto/x509",
    r"internal/url",
    r"internal/fs/utils",
    r"internal/test/binding",
    r"internal/child_process",
    r"stream/consumers",
    r"node:stream/consumers",
    r"stream/promises",
    r"node:stream/promises",
];

#[rustfmt::skip]
pub(crate) const BUILTIN_MANIFEST_DEBUG_ENTRIES: &[BuiltinManifestDebugEntry] = &[
    BuiltinManifestDebugEntry { specifier: r"exact:process", source_key: r"exact_process", source_kind: r"generated", source_path: Some(r"builtins/process.js"), platform_availability: r"all", module_builtin: false, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"exact:crypto", source_key: r"exact_crypto", source_kind: r"generated", source_path: Some(r"builtins/crypto.js"), platform_availability: r"all", module_builtin: false, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"exact:clipboard", source_key: r"exact_clipboard", source_kind: r"generated", source_path: Some(r"builtins/clipboard.js"), platform_availability: r"all", module_builtin: false, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"exact:http", source_key: r"exact_http", source_kind: r"repo", source_path: Some(r"packages/ibex-runtime-js/src/http-server/index.js"), platform_availability: r"all", module_builtin: false, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"exact:sqlite", source_key: r"exact_sqlite", source_kind: r"repo", source_path: Some(r"packages/ibex-runtime-js/src/sqlite/module.js"), platform_availability: r"all", module_builtin: false, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"bun:sqlite", source_key: r"exact_sqlite", source_kind: r"repo", source_path: Some(r"packages/ibex-runtime-js/src/sqlite/module.js"), platform_availability: r"all", module_builtin: false, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"bun:fs", source_key: r"node_fs", source_kind: r"generated", source_path: Some(r"builtins/fs.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:fs", source_key: r"node_fs", source_kind: r"generated", source_path: Some(r"builtins/fs.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"fs", source_key: r"node_fs", source_kind: r"generated", source_path: Some(r"builtins/fs.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:process", source_key: r"exact_process", source_kind: r"generated", source_path: Some(r"builtins/process.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"process", source_key: r"exact_process", source_kind: r"generated", source_path: Some(r"builtins/process.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"bun:fs/promises", source_key: r"node_fs_promises", source_kind: r"generated", source_path: Some(r"builtins/fs-promises.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:fs/promises", source_key: r"node_fs_promises", source_kind: r"generated", source_path: Some(r"builtins/fs-promises.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"fs/promises", source_key: r"node_fs_promises", source_kind: r"generated", source_path: Some(r"builtins/fs-promises.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"internal/fs/promises", source_key: r"node_fs_promises", source_kind: r"generated", source_path: Some(r"builtins/fs-promises.js"), platform_availability: r"all", module_builtin: false, bundle_external: false },
    BuiltinManifestDebugEntry { specifier: r"node:path", source_key: r"node_path", source_kind: r"generated", source_path: Some(r"builtins/path.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"path", source_key: r"node_path", source_kind: r"generated", source_path: Some(r"builtins/path.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:path/posix", source_key: r"path_posix_alias", source_kind: r"inline", source_path: None, platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"path/posix", source_key: r"path_posix_alias", source_kind: r"inline", source_path: None, platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:path/win32", source_key: r"path_win32_alias", source_kind: r"inline", source_path: None, platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"path/win32", source_key: r"path_win32_alias", source_kind: r"inline", source_path: None, platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:crypto", source_key: r"exact_crypto", source_kind: r"generated", source_path: Some(r"builtins/crypto.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"crypto", source_key: r"exact_crypto", source_kind: r"generated", source_path: Some(r"builtins/crypto.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:events", source_key: r"node_events", source_kind: r"generated", source_path: Some(r"builtins/events.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"events", source_key: r"node_events", source_kind: r"generated", source_path: Some(r"builtins/events.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:stream", source_key: r"node_stream", source_kind: r"generated", source_path: Some(r"builtins/stream.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"stream", source_key: r"node_stream", source_kind: r"generated", source_path: Some(r"builtins/stream.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"_stream_readable", source_key: r"legacy_stream_readable", source_kind: r"inline", source_path: None, platform_availability: r"all", module_builtin: false, bundle_external: false },
    BuiltinManifestDebugEntry { specifier: r"_stream_writable", source_key: r"legacy_stream_writable", source_kind: r"inline", source_path: None, platform_availability: r"all", module_builtin: false, bundle_external: false },
    BuiltinManifestDebugEntry { specifier: r"_stream_duplex", source_key: r"legacy_stream_duplex", source_kind: r"inline", source_path: None, platform_availability: r"all", module_builtin: false, bundle_external: false },
    BuiltinManifestDebugEntry { specifier: r"_stream_transform", source_key: r"legacy_stream_transform", source_kind: r"inline", source_path: None, platform_availability: r"all", module_builtin: false, bundle_external: false },
    BuiltinManifestDebugEntry { specifier: r"_stream_passthrough", source_key: r"legacy_stream_passthrough", source_kind: r"inline", source_path: None, platform_availability: r"all", module_builtin: false, bundle_external: false },
    BuiltinManifestDebugEntry { specifier: r"node:stream/consumers", source_key: r"node_stream_consumers", source_kind: r"inline", source_path: None, platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"stream/consumers", source_key: r"node_stream_consumers", source_kind: r"inline", source_path: None, platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:stream/promises", source_key: r"node_stream_promises", source_kind: r"generated", source_path: Some(r"builtins/stream-promises.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"stream/promises", source_key: r"node_stream_promises", source_kind: r"generated", source_path: Some(r"builtins/stream-promises.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:buffer", source_key: r"node_buffer", source_kind: r"generated", source_path: Some(r"builtins/buffer.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"buffer", source_key: r"node_buffer", source_kind: r"generated", source_path: Some(r"builtins/buffer.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:util", source_key: r"node_util", source_kind: r"generated", source_path: Some(r"builtins/util.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"util", source_key: r"node_util", source_kind: r"generated", source_path: Some(r"builtins/util.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"sys", source_key: r"node_util", source_kind: r"generated", source_path: Some(r"builtins/util.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:sys", source_key: r"node_util", source_kind: r"generated", source_path: Some(r"builtins/util.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"util/types", source_key: r"util_types_alias", source_kind: r"inline", source_path: None, platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:util/types", source_key: r"node_util_types_alias", source_kind: r"inline", source_path: None, platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:timers", source_key: r"node_timers", source_kind: r"generated", source_path: Some(r"builtins/timers.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"timers", source_key: r"node_timers", source_kind: r"generated", source_path: Some(r"builtins/timers.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:timers/promises", source_key: r"node_timers_promises", source_kind: r"generated", source_path: Some(r"builtins/timers-promises.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"timers/promises", source_key: r"node_timers_promises", source_kind: r"generated", source_path: Some(r"builtins/timers-promises.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:http", source_key: r"node_http", source_kind: r"generated", source_path: Some(r"builtins/http.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"http", source_key: r"node_http", source_kind: r"generated", source_path: Some(r"builtins/http.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"_http_agent", source_key: r"node_http", source_kind: r"generated", source_path: Some(r"builtins/http.js"), platform_availability: r"all", module_builtin: false, bundle_external: false },
    BuiltinManifestDebugEntry { specifier: r"_http_common", source_key: r"node_http", source_kind: r"generated", source_path: Some(r"builtins/http.js"), platform_availability: r"all", module_builtin: false, bundle_external: false },
    BuiltinManifestDebugEntry { specifier: r"_http_server", source_key: r"node_http", source_kind: r"generated", source_path: Some(r"builtins/http.js"), platform_availability: r"all", module_builtin: false, bundle_external: false },
    BuiltinManifestDebugEntry { specifier: r"_http_outgoing", source_key: r"node_http", source_kind: r"generated", source_path: Some(r"builtins/http.js"), platform_availability: r"all", module_builtin: false, bundle_external: false },
    BuiltinManifestDebugEntry { specifier: r"_http_incoming", source_key: r"node_http", source_kind: r"generated", source_path: Some(r"builtins/http.js"), platform_availability: r"all", module_builtin: false, bundle_external: false },
    BuiltinManifestDebugEntry { specifier: r"node:https", source_key: r"node_https", source_kind: r"generated", source_path: Some(r"builtins/https.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"https", source_key: r"node_https", source_kind: r"generated", source_path: Some(r"builtins/https.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:stream/web", source_key: r"node_stream_web", source_kind: r"generated", source_path: Some(r"builtins/stream-web.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"stream/web", source_key: r"node_stream_web", source_kind: r"generated", source_path: Some(r"builtins/stream-web.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:url", source_key: r"node_url", source_kind: r"generated", source_path: Some(r"builtins/url.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"url", source_key: r"url_alias", source_kind: r"inline", source_path: None, platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:os", source_key: r"node_os", source_kind: r"generated", source_path: Some(r"builtins/os.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"os", source_key: r"node_os", source_kind: r"generated", source_path: Some(r"builtins/os.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:tty", source_key: r"node_tty", source_kind: r"generated", source_path: Some(r"builtins/tty.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"tty", source_key: r"node_tty", source_kind: r"generated", source_path: Some(r"builtins/tty.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:assert", source_key: r"node_assert", source_kind: r"generated", source_path: Some(r"builtins/assert.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"assert", source_key: r"node_assert", source_kind: r"generated", source_path: Some(r"builtins/assert.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:assert/strict", source_key: r"node_assert", source_kind: r"generated", source_path: Some(r"builtins/assert.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"assert/strict", source_key: r"node_assert", source_kind: r"generated", source_path: Some(r"builtins/assert.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:string_decoder", source_key: r"node_string_decoder", source_kind: r"generated", source_path: Some(r"builtins/string-decoder.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"string_decoder", source_key: r"node_string_decoder", source_kind: r"generated", source_path: Some(r"builtins/string-decoder.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:querystring", source_key: r"node_querystring", source_kind: r"generated", source_path: Some(r"builtins/querystring.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"querystring", source_key: r"node_querystring", source_kind: r"generated", source_path: Some(r"builtins/querystring.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:punycode", source_key: r"node_punycode", source_kind: r"generated", source_path: Some(r"builtins/punycode.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"punycode", source_key: r"node_punycode", source_kind: r"generated", source_path: Some(r"builtins/punycode.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:child_process", source_key: r"node_child_process", source_kind: r"generated", source_path: Some(r"builtins/child-process.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"child_process", source_key: r"node_child_process", source_kind: r"generated", source_path: Some(r"builtins/child-process.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:readline", source_key: r"node_readline", source_kind: r"generated", source_path: Some(r"builtins/readline.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"readline", source_key: r"node_readline", source_kind: r"generated", source_path: Some(r"builtins/readline.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:readline/promises", source_key: r"node_readline", source_kind: r"generated", source_path: Some(r"builtins/readline.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"readline/promises", source_key: r"node_readline", source_kind: r"generated", source_path: Some(r"builtins/readline.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:module", source_key: r"node_module", source_kind: r"generated", source_path: Some(r"builtins/module.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"module", source_key: r"node_module", source_kind: r"generated", source_path: Some(r"builtins/module.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:zlib", source_key: r"node_zlib", source_kind: r"generated", source_path: Some(r"builtins/zlib.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"zlib", source_key: r"node_zlib", source_kind: r"generated", source_path: Some(r"builtins/zlib.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:tls", source_key: r"node_tls", source_kind: r"generated", source_path: Some(r"builtins/tls.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"tls", source_key: r"node_tls", source_kind: r"generated", source_path: Some(r"builtins/tls.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:dns", source_key: r"node_dns", source_kind: r"generated", source_path: Some(r"builtins/dns.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"dns", source_key: r"node_dns", source_kind: r"generated", source_path: Some(r"builtins/dns.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:dns/promises", source_key: r"node_dns_promises", source_kind: r"generated", source_path: Some(r"builtins/dns-promises.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"dns/promises", source_key: r"node_dns_promises", source_kind: r"generated", source_path: Some(r"builtins/dns-promises.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"internal/fs/utils", source_key: r"internal_fs_utils", source_kind: r"inline", source_path: None, platform_availability: r"all", module_builtin: false, bundle_external: false },
    BuiltinManifestDebugEntry { specifier: r"node:net", source_key: r"node_net", source_kind: r"generated", source_path: Some(r"builtins/net.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"net", source_key: r"node_net", source_kind: r"generated", source_path: Some(r"builtins/net.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:perf_hooks", source_key: r"node_perf_hooks", source_kind: r"generated", source_path: Some(r"builtins/perf-hooks.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"perf_hooks", source_key: r"node_perf_hooks", source_kind: r"generated", source_path: Some(r"builtins/perf-hooks.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:async_hooks", source_key: r"node_async_hooks", source_kind: r"generated", source_path: Some(r"builtins/async-hooks.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"async_hooks", source_key: r"node_async_hooks", source_kind: r"generated", source_path: Some(r"builtins/async-hooks.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:worker_threads", source_key: r"node_worker_threads", source_kind: r"generated", source_path: Some(r"builtins/worker-threads.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"worker_threads", source_key: r"node_worker_threads", source_kind: r"generated", source_path: Some(r"builtins/worker-threads.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:vm", source_key: r"node_vm", source_kind: r"generated", source_path: Some(r"builtins/vm.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"vm", source_key: r"node_vm", source_kind: r"generated", source_path: Some(r"builtins/vm.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:console", source_key: r"node_console", source_kind: r"generated", source_path: Some(r"builtins/console.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"console", source_key: r"node_console", source_kind: r"generated", source_path: Some(r"builtins/console.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:cluster", source_key: r"node_cluster", source_kind: r"generated", source_path: Some(r"builtins/cluster.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"cluster", source_key: r"node_cluster", source_kind: r"generated", source_path: Some(r"builtins/cluster.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:dgram", source_key: r"node_dgram", source_kind: r"generated", source_path: Some(r"builtins/dgram.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"dgram", source_key: r"node_dgram", source_kind: r"generated", source_path: Some(r"builtins/dgram.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:domain", source_key: r"node_domain", source_kind: r"generated", source_path: Some(r"builtins/domain.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"domain", source_key: r"node_domain", source_kind: r"generated", source_path: Some(r"builtins/domain.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:v8", source_key: r"node_v8", source_kind: r"generated", source_path: Some(r"builtins/v8.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"v8", source_key: r"node_v8", source_kind: r"generated", source_path: Some(r"builtins/v8.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:constants", source_key: r"node_constants", source_kind: r"generated", source_path: Some(r"builtins/constants.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"constants", source_key: r"node_constants", source_kind: r"generated", source_path: Some(r"builtins/constants.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"ws", source_key: r"ws", source_kind: r"generated", source_path: Some(r"builtins/ws.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:http2", source_key: r"node_http2", source_kind: r"generated", source_path: Some(r"builtins/http2.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"http2", source_key: r"node_http2", source_kind: r"generated", source_path: Some(r"builtins/http2.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:diagnostics_channel", source_key: r"node_diagnostics_channel", source_kind: r"generated", source_path: Some(r"builtins/diagnostics-channel.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"diagnostics_channel", source_key: r"node_diagnostics_channel", source_kind: r"generated", source_path: Some(r"builtins/diagnostics-channel.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:trace_events", source_key: r"node_trace_events", source_kind: r"generated", source_path: Some(r"builtins/trace-events.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"trace_events", source_key: r"node_trace_events", source_kind: r"generated", source_path: Some(r"builtins/trace-events.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:inspector", source_key: r"node_inspector", source_kind: r"generated", source_path: Some(r"builtins/inspector.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"inspector", source_key: r"node_inspector", source_kind: r"generated", source_path: Some(r"builtins/inspector.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:inspector/promises", source_key: r"node_inspector", source_kind: r"generated", source_path: Some(r"builtins/inspector.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"inspector/promises", source_key: r"node_inspector", source_kind: r"generated", source_path: Some(r"builtins/inspector.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"node:wasi", source_key: r"node_wasi", source_kind: r"generated", source_path: Some(r"builtins/wasi.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
    BuiltinManifestDebugEntry { specifier: r"wasi", source_key: r"node_wasi", source_kind: r"generated", source_path: Some(r"builtins/wasi.js"), platform_availability: r"all", module_builtin: true, bundle_external: true },
];

fn generated_builtin_source(source_key: &str) -> Option<&'static str> {
    Some(match source_key {
        r"exact_process" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/process.js")),
        r"exact_crypto" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/crypto.js")),
        r"exact_clipboard" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/clipboard.js")),
        r"exact_http" => include_str!(concat!(env!("CARGO_MANIFEST_DIR"), r"/packages/ibex-runtime-js/src/http-server/index.js")),
        r"exact_sqlite" => include_str!(concat!(env!("CARGO_MANIFEST_DIR"), r"/packages/ibex-runtime-js/src/sqlite/module.js")),
        r"node_fs" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/fs.js")),
        r"node_fs_promises" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/fs-promises.js")),
        r"node_path" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/path.js")),
        r"path_posix_alias" => r"module.exports = require('path').posix;",
        r"path_win32_alias" => r"module.exports = require('path').win32;",
        r"node_events" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/events.js")),
        r"node_stream" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/stream.js")),
        r"legacy_stream_readable" => r"module.exports = require('stream').Readable;",
        r"legacy_stream_writable" => r"module.exports = require('stream').Writable;",
        r"legacy_stream_duplex" => r"module.exports = require('stream').Duplex;",
        r"legacy_stream_transform" => r"module.exports = require('stream').Transform;",
        r"legacy_stream_passthrough" => r"module.exports = require('stream').PassThrough;",
        r"node_stream_consumers" => r#"var _bufferMod = require('buffer');
var _Buffer = _bufferMod && _bufferMod.Buffer ? _bufferMod.Buffer : null;

function _toUint8Array(chunk) {
  if (!chunk) {
    return new Uint8Array(0);
  }
  if (chunk instanceof Uint8Array) {
    return chunk;
  }
  if (chunk instanceof ArrayBuffer) {
    return new Uint8Array(chunk);
  }
  if (ArrayBuffer.isView(chunk)) {
    return new Uint8Array(chunk.buffer, chunk.byteOffset, chunk.byteLength);
  }
  if (typeof chunk === 'string') {
    if (typeof TextEncoder === 'function') {
      return new TextEncoder().encode(chunk);
    }
    if (_Buffer && typeof _Buffer.from === 'function') {
      return _Buffer.from(chunk);
    }
    return new Uint8Array(chunk.length);
  }
  return _Buffer && _Buffer.isBuffer(chunk) ? chunk : new Uint8Array(0);
}

function _collect(stream) {
  if (!stream) {
    return Promise.reject(new TypeError('The "stream" argument must be of type stream. Received ' + String(stream)));
  }
  if (typeof stream.getReader === 'function') {
    return new Promise(function(resolve, reject) {
      var chunks = [];
      var reader = stream.getReader();
      function read() {
        reader.read().then(function(result) {
          if (result.done) {
            resolve(chunks);
            return;
          }
          chunks.push(_toUint8Array(result.value));
          read();
        }).catch(reject);
      }
      read();
    });
  }
  if (typeof stream.on === 'function') {
    return new Promise(function(resolve, reject) {
      var chunks = [];
      var ended = false;

      function cleanup() {
        stream.removeListener && stream.removeListener('data', onData);
        stream.removeListener && stream.removeListener('error', onError);
        stream.removeListener && stream.removeListener('end', onEnd);
        stream.removeListener && stream.removeListener('close', onEnd);
      }
      function onData(chunk) {
        chunks.push(_toUint8Array(chunk));
      }
      function onError(err) {
        if (ended) {
          return;
        }
        ended = true;
        cleanup();
        reject(err);
      }
      function onEnd() {
        if (ended) {
          return;
        }
        ended = true;
        cleanup();
        resolve(chunks);
      }
      stream.on('data', onData);
      stream.on('error', onError);
      stream.on('end', onEnd);
      stream.on('close', onEnd);
      if (stream.readableEnded) {
        onEnd();
      }
    });
  }
  return Promise.reject(new TypeError('The "stream" argument must be of type stream. Received ' + String(stream)));
}

function _concatChunks(chunks) {
  var total = 0;
  for (var i = 0; i < chunks.length; i++) {
    total += chunks[i].byteLength || 0;
  }
  var merged = new Uint8Array(total);
  var offset = 0;
  for (var j = 0; j < chunks.length; j++) {
    var chunk = chunks[j];
    merged.set(chunk, offset);
    offset += chunk.byteLength;
  }
  return merged;
}

function _streamToBuffer(chunks) {
  if (_Buffer && _Buffer.concat) {
    return _Buffer.concat(chunks);
  }
  var merged = _concatChunks(chunks);
  return _Buffer ? _Buffer.from(merged) : merged;
}

function _decode(chunks) {
  var merged = _concatChunks(chunks);
  if (typeof TextDecoder === 'function') {
    return new TextDecoder().decode(merged);
  }
  var out = '';
  for (var i = 0; i < merged.length; i++) {
    out += String.fromCharCode(merged[i]);
  }
  return out;
}

function buffer(stream) {
  return _collect(stream).then(function(chunks) {
    return _streamToBuffer(chunks);
  });
}

function arrayBuffer(stream) {
  return _collect(stream).then(function(chunks) {
    return _concatChunks(chunks).buffer;
  });
}

function text(stream) {
  return _collect(stream).then(function(chunks) {
    return _decode(chunks);
  });
}

function blob(stream, options) {
  return _collect(stream).then(function(chunks) {
    if (typeof Blob === 'function') {
      return new Blob(chunks, options);
    }
    var data = _concatChunks(chunks);
    return {
      size: data.length,
      type: options && options.type || '',
      arrayBuffer: function() {
        return Promise.resolve(data.buffer);
      }
    };
  });
}

function json(stream) {
  return text(stream).then(JSON.parse);
}

module.exports = {
  blob: blob,
  buffer: buffer,
  arrayBuffer: arrayBuffer,
  text: text,
  json: json
};"#,
        r"node_stream_promises" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/stream-promises.js")),
        r"node_buffer" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/buffer.js")),
        r"node_util" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/util.js")),
        r"util_types_alias" => r"module.exports = require('util').types;",
        r"node_util_types_alias" => r"module.exports = require('node:util').types;",
        r"node_timers" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/timers.js")),
        r"node_timers_promises" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/timers-promises.js")),
        r"node_http" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/http.js")),
        r"node_https" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/https.js")),
        r"node_stream_web" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/stream-web.js")),
        r"node_url" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/url.js")),
        r"url_alias" => r"const nodeUrl = require('node:url');
const exported = {};
Object.defineProperties(exported, Object.getOwnPropertyDescriptors(nodeUrl));
module.exports = exported;",
        r"node_assert" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/assert.js")),
        r"node_os" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/os.js")),
        r"node_tty" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/tty.js")),
        r"node_string_decoder" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/string-decoder.js")),
        r"node_querystring" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/querystring.js")),
        r"node_punycode" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/punycode.js")),
        r"node_child_process" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/child-process.js")),
        r"node_readline" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/readline.js")),
        r"node_module" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/module.js")),
        r"node_zlib" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/zlib.js")),
        r"node_tls" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/tls.js")),
        r"node_dns" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/dns.js")),
        r"node_dns_promises" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/dns-promises.js")),
        r"internal_fs_utils" => r#"function isFd(fd) {
  return typeof fd === 'number' && Number.isInteger(fd) && fd >= 0;
}

function isFileMode(mode) {
  return typeof mode === 'number' && Number.isInteger(mode);
}

function validateFd(fd) {
  if (!isFd(fd)) {
    throw new TypeError('The "fd" argument must be a non-negative integer. Received ' + String(fd));
  }
}

function toPathIfFileURL(value) {
  if (typeof value === 'string' || value instanceof String) {
    return value;
  }
  if (value && typeof value === 'object' && typeof value.path === 'string') {
    return value.path;
  }
  return value;
}

function _invalidValueError(name, value, extra) {
  var received;
  if (value === null) {
    received = 'null';
  } else if (value === undefined) {
    received = 'undefined';
  } else if (typeof value === 'number') {
    received = 'type number (' + value + ')';
  } else if (value === '') {
    received = 'type string';
  } else {
    received = 'type ' + typeof value;
  }
  if (extra) {
    return new TypeError('The "' + name + '" argument ' + extra + '. Received ' + received);
  }
  return new TypeError('The "' + name + '" argument must be of type object. Received ' + received);
}

function _invalidArgType(name, value, expected, check) {
  var err = new TypeError('The "' + name + '" argument must be of type ' + expected + '. Received ' + (value === null ? 'null' : typeof value));
  err.code = 'ERR_INVALID_ARG_TYPE';
  if (check) throw err;
  return err;
}

function _invalidArgValue(name, value, reason) {
  var err = new TypeError('The "' + name + '" argument must be ' + reason + '. Received ' + (value === null ? 'null' : value));
  err.code = 'ERR_INVALID_ARG_VALUE';
  return err;
}

function _stringToInt(value) {
  return Number.parseInt(value, 10);
}

function _rangeError(name, value, min, max) {
  var err = new RangeError('The value of "' + name + '" is out of range. It must be ' + min + '. Received ' + value);
  err.code = 'ERR_OUT_OF_RANGE';
  return err;
}

function _validateOffsetLength(offset, length, byteLength, mode, maxLength) {
  if (!Number.isInteger(offset) || offset < 0) {
    throw _rangeError('offset', offset, '>= 0', offset);
  }
  if (!Number.isInteger(length) || length < 0) {
    throw _rangeError('length', length, '>= 0', length);
  }
  if (mode === 'write') {
    if (offset > byteLength) {
      var offsetErr = new RangeError('The value of "offset" is out of range. It must be <= ' + byteLength + '. Received ' + offset);
      offsetErr.code = 'ERR_OUT_OF_RANGE';
      throw offsetErr;
    }
  }
  if (length > maxLength) {
    var maxLenErr = new RangeError('The value of "length" is out of range. It must be <= ' + maxLength + '. Received ' + length);
    maxLenErr.code = 'ERR_OUT_OF_RANGE';
    throw maxLenErr;
  }
  var max = byteLength - offset;
  if (length > max) {
    var err = new RangeError('The value of "length" is out of range. It must be <= ' + max + '. Received ' + length);
    err.code = 'ERR_OUT_OF_RANGE';
    throw err;
  }
}

function validateOffsetLengthRead(offset, length, byteLength, lengthIsBigInt) {
  if (lengthIsBigInt !== undefined && lengthIsBigInt) {
    if (typeof offset === 'bigint' || typeof length === 'bigint') {
      offset = _stringToInt(offset);
      length = _stringToInt(length);
    }
  }
  _validateOffsetLength(offset, length, byteLength, 'read', (2 ** 31) - 1);
}

function validateOffsetLengthWrite(offset, length, byteLength, lengthIsBigInt) {
  if (lengthIsBigInt !== undefined && lengthIsBigInt) {
    if (typeof offset === 'bigint' || typeof length === 'bigint') {
      offset = _stringToInt(offset);
      length = _stringToInt(length);
    }
  }
  _validateOffsetLength(offset, length, byteLength, 'write', (2 ** 31) - 1);
}

function _validateOption(name, value, expectedType) {
  if (expectedType === 'boolean' && typeof value !== 'boolean') {
    var boolErr = new TypeError('The "options.' + name + '" property must be of type boolean. Received type ' + typeof value + '.');
    boolErr.code = 'ERR_INVALID_ARG_TYPE';
    throw boolErr;
  }
  if (expectedType === 'number' && (typeof value !== 'number' || !Number.isFinite(value))) {
    var rangeError = new RangeError('The value of "options.' + name + '" is out of range. Received ' + value);
    rangeError.code = 'ERR_OUT_OF_RANGE';
    throw rangeError;
  }
}

function validateRmdirOptions(options) {
  if (options === undefined) {
    return { retryDelay: 100, maxRetries: 0, recursive: false };
  }
  if (options === null || typeof options !== 'object') {
    var e = _invalidArgType('options', options, 'object');
    e.code = 'ERR_INVALID_ARG_TYPE';
    throw e;
  }
  if (Object.prototype.hasOwnProperty.call(options, 'recursive')) {
    _validateOption('recursive', options.recursive, 'boolean');
  }
  if (Object.prototype.hasOwnProperty.call(options, 'retryDelay')) {
    if (typeof options.retryDelay !== 'number' || !Number.isFinite(options.retryDelay) || options.retryDelay < 0) {
      var retryErr = new RangeError('The value of "options.retryDelay" is out of range. Received ' + options.retryDelay);
      retryErr.code = 'ERR_OUT_OF_RANGE';
      throw retryErr;
    }
  }
  if (Object.prototype.hasOwnProperty.call(options, 'maxRetries')) {
    if (typeof options.maxRetries !== 'number' || !Number.isFinite(options.maxRetries) || options.maxRetries < 0) {
      var maxErr = new RangeError('The value of "options.maxRetries" is out of range. Received ' + options.maxRetries);
      maxErr.code = 'ERR_OUT_OF_RANGE';
      throw maxErr;
    }
  }
  return {
    retryDelay: options.retryDelay === undefined ? 100 : options.retryDelay,
    maxRetries: options.maxRetries === undefined ? 0 : options.maxRetries,
    recursive: options.recursive === undefined ? false : options.recursive
  };
}

function validateRmOptionsSync(path, options) {
  var base = validateRmdirOptions(options);
  var hasForce = !!(options && Object.prototype.hasOwnProperty.call(options, 'force'));
  if (hasForce) {
    _validateOption('force', options.force, 'boolean');
  }
  return {
    retryDelay: base.retryDelay,
    maxRetries: base.maxRetries,
    recursive: base.recursive,
    force: hasForce ? options.force : false
  };
}

function _validatePathLike(value, name) {
  if (typeof value === 'string' || Buffer.isBuffer(value)) return;
  if (value && typeof value === 'object' && typeof value.href === 'string' && value.protocol === 'file:') {
    return;
  }
  var err = new TypeError('The "' + name + '" argument must be of type string or an instance of Buffer. Received type ' + (value === null ? 'object' : typeof value) + ' (' + String(value) + ')');
  err.code = 'ERR_INVALID_ARG_TYPE';
  throw err;
}

function Dirent(name, parentPath, type) {
  this.name = name;
  this.path = parentPath;
  this.parentPath = parentPath;
  this._type = type;
}

Dirent.prototype.isFile = function() { return this._type === 1; };
Dirent.prototype.isDirectory = function() { return this._type === 2; };
Dirent.prototype.isSymbolicLink = function() { return this._type === 3; };
Dirent.prototype.isFIFO = function() { return this._type === 4; };
Dirent.prototype.isSocket = function() { return this._type === 5; };
Dirent.prototype.isCharacterDevice = function() { return this._type === 6; };
Dirent.prototype.isBlockDevice = function() { return this._type === 7; };

function getDirent(path, name, type, callback) {
  _validatePathLike(path, 'path');
  var dirent = new Dirent(name, path, type);
  if (callback) {
    callback(null, dirent);
    return null;
  }
  return dirent;
}

function getDirents(path, entries, callback) {
  _validatePathLike(path, 'path');
  var result = [];
  for (var i = 0; i < entries.length; i++) {
    var entry = entries[i];
    if (!entry || !entry.length) {
      continue;
    }
    result.push(getDirent(path, entry[0], entry[1]));
  }
  callback(null, result);
}

function stringToFlags(flags) {
  if (typeof flags !== 'string' || flags === '') {
    var err = new TypeError('The flags argument must be a valid flags string. Received ' + flags);
    err.code = 'ERR_INVALID_ARG_VALUE';
    throw err;
  }
  var hasPlus = flags.indexOf('+') !== -1;
  if (flags.indexOf('+') !== flags.lastIndexOf('+')) {
    throw _invalidArgValue('flags', flags, 'a valid flag string');
  }
  if (hasPlus && flags.indexOf('+') !== flags.length - 1) {
    throw _invalidArgValue('flags', flags, 'a valid flag string');
  }
  var flagChars = hasPlus ? flags.slice(0, -1) : flags;
  var hasSync = false;
  var hasExclusive = false;
  var modeFlags = '';
  for (var i = 0; i < flagChars.length; i++) {
    var ch = flagChars.charAt(i);
    if (ch === 's') {
      if (hasSync) throw _invalidArgValue('flags', flags, 'a valid flag string');
      hasSync = true;
    } else if (ch === 'x') {
      if (hasExclusive) throw _invalidArgValue('flags', flags, 'a valid flag string');
      hasExclusive = true;
    } else if (ch === 'r' || ch === 'w' || ch === 'a') {
      if (modeFlags.length >= 1) throw _invalidArgValue('flags', flags, 'a valid flag string');
      modeFlags = ch;
    } else {
      throw _invalidArgValue('flags', flags, 'a valid flag string');
    }
  }

  if (modeFlags.length !== 1) {
    throw _invalidArgValue('flags', flags, 'a valid flag string');
  }
  if (hasExclusive && modeFlags === 'r') {
    throw _invalidArgValue('flags', flags, 'a valid flag string');
  }
  var result = 0;
  if (modeFlags === 'r') {
    result = hasPlus ? 2 : 0;
  } else if (modeFlags === 'w') {
    result = 0x200 | 0x400 | 0x1;
  } else {
    result = 0x8 | 0x200 | 0x1;
  }
  if (hasPlus) {
    result = (result & ~0x1) | 0x2;
  }
  if (hasExclusive) result |= 0x800;
  if (hasSync) result |= 0x80;
  return result;
}

function BigIntStats(dev, mode, nlink, uid, gid, rdev, blksize, ino, size, blocks, atimeMs, mtimeMs, ctimeMs, birthtimeMs, atimeNs, mtimeNs, ctimeNs, birthtimeNs) {
  this.dev = BigInt(dev);
  this.mode = BigInt(mode);
  this.nlink = BigInt(nlink);
  this.uid = BigInt(uid);
  this.gid = BigInt(gid);
  this.rdev = BigInt(rdev);
  this.size = BigInt(size);
  this.blksize = BigInt(blksize);
  this.blocks = BigInt(blocks);
  this.atimeMs = BigInt(atimeMs);
  this.mtimeMs = BigInt(mtimeMs);
  this.ctimeMs = BigInt(ctimeMs);
  this.birthtimeMs = BigInt(birthtimeMs);
  this.atimeNs = BigInt(atimeNs || 0);
  this.mtimeNs = BigInt(mtimeNs || 0);
  this.ctimeNs = BigInt(ctimeNs || 0);
  this.birthtimeNs = BigInt(birthtimeNs || 0);
  this.atime = new Date(Number(this.atimeMs));
  this.mtime = new Date(Number(this.mtimeMs));
  this.ctime = new Date(Number(this.ctimeMs));
  this.birthtime = new Date(Number(this.birthtimeMs));
  this._isFile = (mode & 0o170000) === 0o100000;
  this._isDir = (mode & 0o170000) === 0o40000;
  this._isChrDev = (mode & 0o170000) === 0o20000;
  this._isBlkDev = (mode & 0o170000) === 0o60000;
  this._isFifo = (mode & 0o170000) === 0o10000;
  this._isSocket = (mode & 0o170000) === 0o140000;
  this._isSymlink = (mode & 0o170000) === 0o120000;
}
BigIntStats.prototype.isFile = function() { return this._isFile; };
BigIntStats.prototype.isDirectory = function() { return this._isDir; };
BigIntStats.prototype.isBlockDevice = function() { return this._isBlkDev; };
BigIntStats.prototype.isCharacterDevice = function() { return this._isChrDev; };
BigIntStats.prototype.isFIFO = function() { return this._isFifo; };
BigIntStats.prototype.isSocket = function() { return this._isSocket; };
BigIntStats.prototype.isSymbolicLink = function() { return this._isSymlink; };

function SyncWriteStream() {}
SyncWriteStream.prototype = {
  _write: function(chunk, encoding, cb) {
    if (cb && typeof cb === 'function') {
      cb();
    }
  }
};

module.exports = {
  isFd: isFd,
  isFileMode: isFileMode,
  validateFd: validateFd,
  toPathIfFileURL: toPathIfFileURL,
  stringToFlags: stringToFlags,
  validateOffsetLengthRead: validateOffsetLengthRead,
  validateOffsetLengthWrite: validateOffsetLengthWrite,
  validateRmdirOptions: validateRmdirOptions,
  validateRmOptionsSync: validateRmOptionsSync,
  getDirents: getDirents,
  getDirent: getDirent,
  BigIntStats: BigIntStats,
  SyncWriteStream: SyncWriteStream,
  kMinPoolSpace: 8192
};"#,
        r"node_net" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/net.js")),
        r"node_perf_hooks" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/perf-hooks.js")),
        r"node_async_hooks" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/async-hooks.js")),
        r"node_worker_threads" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/worker-threads.js")),
        r"node_vm" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/vm.js")),
        r"node_console" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/console.js")),
        r"node_cluster" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/cluster.js")),
        r"node_dgram" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/dgram.js")),
        r"node_domain" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/domain.js")),
        r"node_v8" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/v8.js")),
        r"node_constants" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/constants.js")),
        r"ws" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/ws.js")),
        r"node_http2" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/http2.js")),
        r"node_diagnostics_channel" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/diagnostics-channel.js")),
        r"node_trace_events" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/trace-events.js")),
        r"node_inspector" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/inspector.js")),
        r"node_wasi" => include_str!(concat!(env!("OUT_DIR"), r"/builtins/wasi.js")),
        _ => return None,
    })
}
