// @generated by packages/ibex-devtools/src/scripts/generate-import-grant-keys.mjs
// Source: packages/ibex-devtools/src/scripts/import-grants.mjs
// Source SHA-256: 5ae794adec1936b81e1bbe6a026a0306c11edf13775a3d9a2159483852ba7b69
// Generator SHA-256: 16d384b3c74d15ee62bc9fc933084cfe2481df822a577b9701aefcb74448026f
// Do not edit by hand.
// @ref LLP 0022#6-imports-and-authority

pub const RESERVED_IMPORT_GRANT_KEYS: &[&str; 6] = &[
    "authorities",
    "grants",
    "endow",
    "builtins",
    "also",
    "needs",
];
