// @generated by packages/ibex-devtools/src/scripts/generate-interrupt-machine.mjs
// Source: session/interrupt-machine.v1.json
// Source SHA-256: 1c604efe5f284a4557785019df018d709c228f0abde436940b9a1ae1f707810c
// Generator SHA-256: 3641473b85884a6810607b791937b1f44b03cf5111fb384731e224c9658a2d91
// Do not edit by hand.
// @ref LLP 0025#6-interruption-and-cancellation

#![allow(dead_code)]

pub const INTERRUPT_MACHINE_SOURCE_SHA256: &str = "1c604efe5f284a4557785019df018d709c228f0abde436940b9a1ae1f707810c";
pub const INTERRUPT_MACHINE_GENERATOR_SHA256: &str = "3641473b85884a6810607b791937b1f44b03cf5111fb384731e224c9658a2d91";
pub const ESCAPE_TEMPORAL_PROPERTY: &str = "interrupts_without_editor_input <= 3";
pub const PROMISE_TEMPORAL_PROPERTY: &str = "(promised && no editor input since) => next interrupt terminal";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EditorPhase { Idle, Editing, Continuation, Evaluating, Shutdown }

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PendingSubmission { None, Undispatched, Dispatched, Discarded }

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum WorkKind { Evaluation, Callback, Completion }

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ExecutingUnit { pub id: u64, pub kind: WorkKind }

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PromiseClass { None, Orderly, Interrupt130 }

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TerminationCause { pub status: i32 }

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct InterruptState<'a> {
    pub phase: EditorPhase,
    pub pending_submission: PendingSubmission,
    pub executing: Option<ExecutingUnit>,
    pub suspended_ids: &'a [u64],
    /// Scheduling identities are distinct from cancellation target ids.
    pub due_schedules: &'a [u64],
    pub completion_queued: Option<u64>,
    pub escape_credit: u8,
    pub promise: PromiseClass,
    pub cause: Option<TerminationCause>,
    pub exit_code: i32,
    pub ended: bool,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DispatchBranch { LatchedCause, PriorPromise, CreditThree, TargetRow }

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum InterruptRow {
    IdleExecuting,
    IdleNonexecutingWork,
    IdlePrompt,
    EditorCompletionExecuting,
    EditorCompletionQueued,
    EditorBuffer,
    EvaluatingExecuting,
    EvaluatingNonexecutingWork,
    EvaluatingDispatched,
    EvaluatingUndispatched,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum StatusClass { Cause, Orderly, Interrupt130 }

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Notice { None, OrderlyPromise, CancellingWork, WorkInFlight, CancellingCompletion, InputDiscarded }

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BufferAction { Unchanged, PreserveInvalidate, DiscardInvalidate }

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SubmissionAction { Unchanged, Discard, DiscardAndIdle }

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct InterruptDecision {
    pub branch: DispatchBranch,
    pub row: Option<InterruptRow>,
    pub terminal: bool,
    pub expedited: bool,
    pub next_credit: u8,
    pub status: Option<i32>,
    pub status_class: Option<StatusClass>,
    pub notice: Notice,
    pub promise_to_set: PromiseClass,
    pub abandon_completion: bool,
    pub cancel_target: Option<u64>,
    pub buffer: BufferAction,
    pub submission: SubmissionAction,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum InvalidInterruptState { SessionEnded, MissingOrAmbiguousRow }

pub fn dispatch_interrupt(state: InterruptState<'_>) -> Result<InterruptDecision, InvalidInterruptState> {
    if state.ended { return Err(InvalidInterruptState::SessionEnded); }
    let next_credit = state.escape_credit.saturating_add(1).min(3);
    if let Some(cause) = state.cause {
        return Ok(InterruptDecision {
            branch: DispatchBranch::LatchedCause, row: None, terminal: true,
            expedited: true, next_credit, status: Some(cause.status),
            status_class: Some(StatusClass::Cause), notice: Notice::None,
            promise_to_set: PromiseClass::None, abandon_completion: false,
            cancel_target: None, buffer: BufferAction::Unchanged,
            submission: SubmissionAction::Unchanged,
        });
    }
    if state.promise != PromiseClass::None {
        let (status, status_class) = match state.promise {
            PromiseClass::Orderly => (state.exit_code, StatusClass::Orderly),
            PromiseClass::Interrupt130 => (130, StatusClass::Interrupt130),
            PromiseClass::None => unreachable!(),
        };
        return Ok(InterruptDecision {
            branch: DispatchBranch::PriorPromise, row: None, terminal: true,
            expedited: false, next_credit, status: Some(status),
            status_class: Some(status_class), notice: Notice::None,
            promise_to_set: PromiseClass::None, abandon_completion: false,
            cancel_target: None, buffer: BufferAction::Unchanged,
            submission: SubmissionAction::Unchanged,
        });
    }
    if next_credit >= 3 {
        return Ok(InterruptDecision {
            branch: DispatchBranch::CreditThree, row: None, terminal: true,
            expedited: false, next_credit, status: Some(130),
            status_class: Some(StatusClass::Interrupt130), notice: Notice::None,
            promise_to_set: PromiseClass::None, abandon_completion: false,
            cancel_target: None, buffer: BufferAction::Unchanged,
            submission: SubmissionAction::Unchanged,
        });
    }

    let mut selected = None;
    let mut matches = 0_u8;
    if (state.phase == EditorPhase::Idle) && (state.executing.is_some()) {
        matches += 1;
        selected = Some(InterruptDecision {
            branch: DispatchBranch::TargetRow,
            row: Some(InterruptRow::IdleExecuting),
            terminal: false,
            expedited: false,
            next_credit,
            status: None,
            status_class: None,
            notice: Notice::CancellingWork,
            promise_to_set: PromiseClass::Interrupt130,
            abandon_completion: true,
            cancel_target: state.executing.map(|unit| unit.id),
            buffer: BufferAction::Unchanged,
            submission: SubmissionAction::Unchanged,
        });
    }
    if (state.phase == EditorPhase::Idle) && (state.executing.is_none()) && (!state.suspended_ids.is_empty() || !state.due_schedules.is_empty()) {
        matches += 1;
        selected = Some(InterruptDecision {
            branch: DispatchBranch::TargetRow,
            row: Some(InterruptRow::IdleNonexecutingWork),
            terminal: false,
            expedited: false,
            next_credit,
            status: None,
            status_class: None,
            notice: Notice::WorkInFlight,
            promise_to_set: PromiseClass::Interrupt130,
            abandon_completion: true,
            cancel_target: None,
            buffer: BufferAction::Unchanged,
            submission: SubmissionAction::Unchanged,
        });
    }
    if (state.phase == EditorPhase::Idle) && (state.executing.is_none()) && (state.suspended_ids.is_empty() && state.due_schedules.is_empty()) {
        matches += 1;
        selected = Some(InterruptDecision {
            branch: DispatchBranch::TargetRow,
            row: Some(InterruptRow::IdlePrompt),
            terminal: false,
            expedited: false,
            next_credit,
            status: None,
            status_class: None,
            notice: Notice::OrderlyPromise,
            promise_to_set: PromiseClass::Orderly,
            abandon_completion: true,
            cancel_target: None,
            buffer: BufferAction::Unchanged,
            submission: SubmissionAction::Unchanged,
        });
    }
    if (state.phase == EditorPhase::Editing || state.phase == EditorPhase::Continuation) && (matches!(state.executing, Some(unit) if unit.kind == WorkKind::Completion)) {
        matches += 1;
        selected = Some(InterruptDecision {
            branch: DispatchBranch::TargetRow,
            row: Some(InterruptRow::EditorCompletionExecuting),
            terminal: false,
            expedited: false,
            next_credit,
            status: None,
            status_class: None,
            notice: Notice::CancellingCompletion,
            promise_to_set: PromiseClass::Interrupt130,
            abandon_completion: true,
            cancel_target: state.executing.map(|unit| unit.id),
            buffer: BufferAction::PreserveInvalidate,
            submission: SubmissionAction::Unchanged,
        });
    }
    if (state.phase == EditorPhase::Editing || state.phase == EditorPhase::Continuation) && (!matches!(state.executing, Some(unit) if unit.kind == WorkKind::Completion)) && (state.completion_queued.is_some()) {
        matches += 1;
        selected = Some(InterruptDecision {
            branch: DispatchBranch::TargetRow,
            row: Some(InterruptRow::EditorCompletionQueued),
            terminal: false,
            expedited: false,
            next_credit,
            status: None,
            status_class: None,
            notice: Notice::WorkInFlight,
            promise_to_set: PromiseClass::Interrupt130,
            abandon_completion: true,
            cancel_target: None,
            buffer: BufferAction::PreserveInvalidate,
            submission: SubmissionAction::Unchanged,
        });
    }
    if (state.phase == EditorPhase::Editing || state.phase == EditorPhase::Continuation) && (!matches!(state.executing, Some(unit) if unit.kind == WorkKind::Completion)) && (state.completion_queued.is_none()) {
        matches += 1;
        selected = Some(InterruptDecision {
            branch: DispatchBranch::TargetRow,
            row: Some(InterruptRow::EditorBuffer),
            terminal: false,
            expedited: false,
            next_credit,
            status: None,
            status_class: None,
            notice: Notice::InputDiscarded,
            promise_to_set: PromiseClass::None,
            abandon_completion: false,
            cancel_target: None,
            buffer: BufferAction::DiscardInvalidate,
            submission: SubmissionAction::Unchanged,
        });
    }
    if (state.phase == EditorPhase::Evaluating) && (state.executing.is_some()) {
        matches += 1;
        selected = Some(InterruptDecision {
            branch: DispatchBranch::TargetRow,
            row: Some(InterruptRow::EvaluatingExecuting),
            terminal: false,
            expedited: false,
            next_credit,
            status: None,
            status_class: None,
            notice: Notice::CancellingWork,
            promise_to_set: PromiseClass::Interrupt130,
            abandon_completion: true,
            cancel_target: state.executing.map(|unit| unit.id),
            buffer: BufferAction::Unchanged,
            submission: SubmissionAction::Discard,
        });
    }
    if (state.phase == EditorPhase::Evaluating) && (state.executing.is_none()) && (!state.suspended_ids.is_empty() || !state.due_schedules.is_empty()) {
        matches += 1;
        selected = Some(InterruptDecision {
            branch: DispatchBranch::TargetRow,
            row: Some(InterruptRow::EvaluatingNonexecutingWork),
            terminal: false,
            expedited: false,
            next_credit,
            status: None,
            status_class: None,
            notice: Notice::WorkInFlight,
            promise_to_set: PromiseClass::Interrupt130,
            abandon_completion: true,
            cancel_target: None,
            buffer: BufferAction::Unchanged,
            submission: SubmissionAction::Discard,
        });
    }
    if (state.phase == EditorPhase::Evaluating) && (state.executing.is_none()) && (state.suspended_ids.is_empty() && state.due_schedules.is_empty()) && (state.pending_submission == PendingSubmission::Dispatched) {
        matches += 1;
        selected = Some(InterruptDecision {
            branch: DispatchBranch::TargetRow,
            row: Some(InterruptRow::EvaluatingDispatched),
            terminal: false,
            expedited: false,
            next_credit,
            status: None,
            status_class: None,
            notice: Notice::WorkInFlight,
            promise_to_set: PromiseClass::Interrupt130,
            abandon_completion: true,
            cancel_target: None,
            buffer: BufferAction::Unchanged,
            submission: SubmissionAction::Discard,
        });
    }
    if (state.phase == EditorPhase::Evaluating) && (state.executing.is_none()) && (state.suspended_ids.is_empty() && state.due_schedules.is_empty()) && (state.pending_submission == PendingSubmission::Undispatched) {
        matches += 1;
        selected = Some(InterruptDecision {
            branch: DispatchBranch::TargetRow,
            row: Some(InterruptRow::EvaluatingUndispatched),
            terminal: false,
            expedited: false,
            next_credit,
            status: None,
            status_class: None,
            notice: Notice::None,
            promise_to_set: PromiseClass::None,
            abandon_completion: true,
            cancel_target: None,
            buffer: BufferAction::Unchanged,
            submission: SubmissionAction::DiscardAndIdle,
        });
    }
    if matches != 1 { return Err(InvalidInterruptState::MissingOrAmbiguousRow); }
    Ok(selected.expect("one generated row matched"))
}
