// @generated by packages/ibex-devtools/src/scripts/generate-repl-surface.mjs
// Source: runtime-surface.json#replSurface,#keybindingSurface
// Source SHA-256: 6bc3f3fe03bf331be88fe0e0d55ba778fe0f93d214d7175911c45c0832ea701b
// Schema: session/schema/repl-surface.schema.json
// Schema SHA-256: db497eb37039d5f5501d723ff9c8aa91c0833758773f8ba32c6e6390449718c8
// Generator SHA-256: 773b6ecacbb2e134e23249aae4be8ef296600f5da0d7a0ef88b796e8c15ca84e
// Do not edit by hand.
// @ref LLP 0022#8-commands — generated command, help, and completion authority
// @ref LLP 0025#5-terminal-presentation-and-restoration — generated key controls

#![allow(dead_code)]

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum ReplCommandId {
    Help,
    Exit,
    Clear,
    Load,
    Time,
    Break,
    Mounts,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ArgumentKind {
    None,
    RequiredRemainder,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ReplMode {
    Interactive,
    PlainTranscript,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ReplState {
    Fresh,
    Continuation,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SuccessOutput {
    Stdout,
    None,
    EditorControlOrNone,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Affordance {
    PresentationOnly,
    CooperativeLifecycle,
    TerminalOperatorState,
    TypedSessionEffect,
    EvaluationWrapper,
    SessionControl,
    LogicalNamespaceIntrospection,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RegistryRelationKind {
    Capability,
    NonCapabilityRationale,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SourceSubmission {
    None,
    AdvanceOnSourceRequest,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RegistryRelation {
    pub kind: RegistryRelationKind,
    pub id: &'static str,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ReplCommandSpec {
    pub id: ReplCommandId,
    pub name: &'static str,
    pub aliases: &'static [&'static str],
    pub usage: &'static str,
    pub argument_kind: ArgumentKind,
    pub argument_name: Option<&'static str>,
    pub modes: &'static [ReplMode],
    pub states: &'static [ReplState],
    pub success_output: SuccessOutput,
    pub affordance: Affordance,
    pub registry_relations: &'static [RegistryRelation],
    pub source_submission: SourceSubmission,
    pub help: &'static str,
}

pub const RUNTIME_SURFACE_SOURCE_SHA256: &str =
    "6bc3f3fe03bf331be88fe0e0d55ba778fe0f93d214d7175911c45c0832ea701b";
pub const REPL_SURFACE_SCHEMA_SHA256: &str =
    "db497eb37039d5f5501d723ff9c8aa91c0833758773f8ba32c6e6390449718c8";
pub const REPL_SURFACE_GENERATOR_SHA256: &str =
    "773b6ecacbb2e134e23249aae4be8ef296600f5da0d7a0ef88b796e8c15ca84e";
pub const CAPABILITY_DEFINITIONS_SHA256: &str =
    "0f13000157f1b55ffa51ccd930369b57b296aa13c8065bec5e858c440a65828e";
pub const POLICY_RULES_SHA256: &str =
    "c35dfa2cb7c8634c4d24e9ba5639ee795eba207b71ff8990e19b67541ce00751";
pub const REPL_SURFACE_VERSION: u32 = 1;
pub const KEYBINDING_SURFACE_VERSION: u32 = 1;
pub const REPL_HELP_TEXT: &str = "REPL Commands:\n  .help (.h)         Show every command, alias, and published keybinding\n  .exit (.quit, .q)  End the session through orderly shutdown\n  .clear (.cls)      Clear an interactive display without resetting session state\n  .load <path>       Read a virtual path through typed authority and evaluate its supported contents\n  .time <input>      Evaluate input with prompt semantics and report elapsed time\n  .break             Abandon a pending multiline continuation\n  .mounts            Show the virtual mount table and virtual current directory\n\nKeybindings:\n  Tab     Complete without authorizing effects or evaluating user code\n  Ctrl+C  Cancel, discard, or escalate according to session state\n  Ctrl+D  Exit at an empty prompt; otherwise delete forward\n  Ctrl+R  Search session history in reverse\n  Ctrl+Z  Restore the terminal, suspend, and recapture on resume\n";

pub static REPL_COMMANDS: &[ReplCommandSpec] = &[
    ReplCommandSpec {
        id: ReplCommandId::Help,
        name: ".help",
        aliases: &[".h"],
        usage: ".help",
        argument_kind: ArgumentKind::None,
        argument_name: None,
        modes: &[ReplMode::Interactive, ReplMode::PlainTranscript],
        states: &[ReplState::Fresh],
        success_output: SuccessOutput::Stdout,
        affordance: Affordance::PresentationOnly,
        registry_relations: &[],
        source_submission: SourceSubmission::None,
        help: "Show every command, alias, and published keybinding",
    },
    ReplCommandSpec {
        id: ReplCommandId::Exit,
        name: ".exit",
        aliases: &[".quit", ".q"],
        usage: ".exit",
        argument_kind: ArgumentKind::None,
        argument_name: None,
        modes: &[ReplMode::Interactive, ReplMode::PlainTranscript],
        states: &[ReplState::Fresh],
        success_output: SuccessOutput::None,
        affordance: Affordance::CooperativeLifecycle,
        registry_relations: &[RegistryRelation {
            kind: RegistryRelationKind::Capability,
            id: "lifecycle:exit",
        }],
        source_submission: SourceSubmission::None,
        help: "End the session through orderly shutdown",
    },
    ReplCommandSpec {
        id: ReplCommandId::Clear,
        name: ".clear",
        aliases: &[".cls"],
        usage: ".clear",
        argument_kind: ArgumentKind::None,
        argument_name: None,
        modes: &[ReplMode::Interactive, ReplMode::PlainTranscript],
        states: &[ReplState::Fresh],
        success_output: SuccessOutput::EditorControlOrNone,
        affordance: Affordance::TerminalOperatorState,
        registry_relations: &[],
        source_submission: SourceSubmission::None,
        help: "Clear an interactive display without resetting session state",
    },
    ReplCommandSpec {
        id: ReplCommandId::Load,
        name: ".load",
        aliases: &[],
        usage: ".load <path>",
        argument_kind: ArgumentKind::RequiredRemainder,
        argument_name: Some("path"),
        modes: &[ReplMode::Interactive, ReplMode::PlainTranscript],
        states: &[ReplState::Fresh],
        success_output: SuccessOutput::Stdout,
        affordance: Affordance::TypedSessionEffect,
        registry_relations: &[
            RegistryRelation {
                kind: RegistryRelationKind::NonCapabilityRationale,
                id: "authenticated-code-ingress",
            },
            RegistryRelation {
                kind: RegistryRelationKind::Capability,
                id: "fs:list",
            },
            RegistryRelation {
                kind: RegistryRelationKind::Capability,
                id: "fs:read",
            },
        ],
        source_submission: SourceSubmission::AdvanceOnSourceRequest,
        help: "Read a virtual path through typed authority and evaluate its supported contents",
    },
    ReplCommandSpec {
        id: ReplCommandId::Time,
        name: ".time",
        aliases: &[],
        usage: ".time <input>",
        argument_kind: ArgumentKind::RequiredRemainder,
        argument_name: Some("input"),
        modes: &[ReplMode::Interactive, ReplMode::PlainTranscript],
        states: &[ReplState::Fresh],
        success_output: SuccessOutput::Stdout,
        affordance: Affordance::EvaluationWrapper,
        registry_relations: &[RegistryRelation {
            kind: RegistryRelationKind::NonCapabilityRationale,
            id: "authenticated-code-ingress",
        }],
        source_submission: SourceSubmission::AdvanceOnSourceRequest,
        help: "Evaluate input with prompt semantics and report elapsed time",
    },
    ReplCommandSpec {
        id: ReplCommandId::Break,
        name: ".break",
        aliases: &[],
        usage: ".break",
        argument_kind: ArgumentKind::None,
        argument_name: None,
        modes: &[ReplMode::Interactive, ReplMode::PlainTranscript],
        states: &[ReplState::Fresh, ReplState::Continuation],
        success_output: SuccessOutput::None,
        affordance: Affordance::SessionControl,
        registry_relations: &[],
        source_submission: SourceSubmission::None,
        help: "Abandon a pending multiline continuation",
    },
    ReplCommandSpec {
        id: ReplCommandId::Mounts,
        name: ".mounts",
        aliases: &[],
        usage: ".mounts",
        argument_kind: ArgumentKind::None,
        argument_name: None,
        modes: &[ReplMode::Interactive, ReplMode::PlainTranscript],
        states: &[ReplState::Fresh],
        success_output: SuccessOutput::Stdout,
        affordance: Affordance::LogicalNamespaceIntrospection,
        registry_relations: &[],
        source_submission: SourceSubmission::None,
        help: "Show the virtual mount table and virtual current directory",
    },
];

pub fn command_by_name(name: &str) -> Option<&'static ReplCommandSpec> {
    REPL_COMMANDS
        .iter()
        .find(|command| command.name == name || command.aliases.contains(&name))
}

pub static COMMAND_COMPLETIONS: &[&str] = &[
    ".help", ".h", ".exit", ".quit", ".q", ".clear", ".cls", ".load", ".time", ".break", ".mounts",
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CommandLine<'a> {
    JavaScript,
    Known {
        command: &'static ReplCommandSpec,
        argument: &'a str,
    },
    Unknown {
        name: &'a str,
    },
}

pub fn classify_command_line(line: &str) -> CommandLine<'_> {
    let Some((start, first)) = line.char_indices().find(|(_, ch)| !ch.is_whitespace()) else {
        return CommandLine::JavaScript;
    };
    if first != '.' {
        return CommandLine::JavaScript;
    }
    let name_start = start + first.len_utf8();
    let Some((_, first_name)) = line[name_start..].char_indices().next() else {
        return CommandLine::JavaScript;
    };
    if !first_name.is_ascii_alphabetic() {
        return CommandLine::JavaScript;
    }
    let scan_start = name_start + first_name.len_utf8();
    let mut name_end = scan_start;
    for (offset, ch) in line[scan_start..].char_indices() {
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '-' {
            name_end = scan_start + offset + ch.len_utf8();
            continue;
        }
        if !ch.is_whitespace() {
            return CommandLine::JavaScript;
        }
        break;
    }
    let name = &line[start..name_end];
    let argument = line[name_end..].trim_start_matches(char::is_whitespace);
    match command_by_name(name) {
        Some(command) => CommandLine::Known { command, argument },
        None => CommandLine::Unknown { name },
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ArgumentError {
    Missing,
    Unexpected,
}

pub fn validate_argument(command: &ReplCommandSpec, argument: &str) -> Result<(), ArgumentError> {
    match (command.argument_kind, argument.is_empty()) {
        (ArgumentKind::None, false) => Err(ArgumentError::Unexpected),
        (ArgumentKind::RequiredRemainder, true) => Err(ArgumentError::Missing),
        _ => Ok(()),
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ParserDialect {
    JavaScript,
    JavaScriptJsx,
    TypeScript,
    TypeScriptJsx,
    Json,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum LoadDisposition {
    Script(ParserDialect),
    JsonData,
    RefuseModuleKind,
    RefuseTypesOnly,
    RefuseUnknownOrExtensionless,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct LoadExtensionSpec {
    pub extension: &'static str,
    pub disposition: LoadDisposition,
    pub error_code: Option<&'static str>,
}
pub static LOAD_EXTENSIONS: &[LoadExtensionSpec] = &[
    LoadExtensionSpec {
        extension: ".d.ts",
        disposition: LoadDisposition::RefuseTypesOnly,
        error_code: Some("load-types-only"),
    },
    LoadExtensionSpec {
        extension: ".json",
        disposition: LoadDisposition::JsonData,
        error_code: None,
    },
    LoadExtensionSpec {
        extension: ".jsx",
        disposition: LoadDisposition::Script(ParserDialect::JavaScriptJsx),
        error_code: None,
    },
    LoadExtensionSpec {
        extension: ".tsx",
        disposition: LoadDisposition::Script(ParserDialect::TypeScriptJsx),
        error_code: None,
    },
    LoadExtensionSpec {
        extension: ".mjs",
        disposition: LoadDisposition::RefuseModuleKind,
        error_code: Some("load-module-kind"),
    },
    LoadExtensionSpec {
        extension: ".cjs",
        disposition: LoadDisposition::RefuseModuleKind,
        error_code: Some("load-module-kind"),
    },
    LoadExtensionSpec {
        extension: ".mts",
        disposition: LoadDisposition::RefuseModuleKind,
        error_code: Some("load-module-kind"),
    },
    LoadExtensionSpec {
        extension: ".cts",
        disposition: LoadDisposition::RefuseModuleKind,
        error_code: Some("load-module-kind"),
    },
    LoadExtensionSpec {
        extension: ".js",
        disposition: LoadDisposition::Script(ParserDialect::JavaScript),
        error_code: None,
    },
    LoadExtensionSpec {
        extension: ".ts",
        disposition: LoadDisposition::Script(ParserDialect::TypeScript),
        error_code: None,
    },
];
pub const LOAD_DEFAULT_ERROR_CODE: &str = "load-unsupported-extension";
pub fn classify_load_path(path: &str) -> LoadDisposition {
    LOAD_EXTENSIONS
        .iter()
        .find(|row| path.ends_with(row.extension))
        .map(|row| row.disposition)
        .unwrap_or(LoadDisposition::RefuseUnknownOrExtensionless)
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum KeybindingId {
    Complete,
    Interrupt,
    Eof,
    ReverseHistory,
    Suspend,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum KeybindingAction {
    BoundedAsynchronousCompletion,
    InterruptMachine,
    OrderlyEofOrDeleteForward,
    ReverseHistorySearch,
    SuspendTransaction,
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct KeybindingSpec {
    pub id: KeybindingId,
    pub display: &'static str,
    pub bytes: &'static [u8],
    pub action: KeybindingAction,
    pub counts_as_editor_input: bool,
    pub help: &'static str,
}
pub static KEYBINDINGS: &[KeybindingSpec] = &[
    KeybindingSpec {
        id: KeybindingId::Complete,
        display: "Tab",
        bytes: &[9],
        action: KeybindingAction::BoundedAsynchronousCompletion,
        counts_as_editor_input: true,
        help: "Complete without authorizing effects or evaluating user code",
    },
    KeybindingSpec {
        id: KeybindingId::Interrupt,
        display: "Ctrl+C",
        bytes: &[3],
        action: KeybindingAction::InterruptMachine,
        counts_as_editor_input: false,
        help: "Cancel, discard, or escalate according to session state",
    },
    KeybindingSpec {
        id: KeybindingId::Eof,
        display: "Ctrl+D",
        bytes: &[4],
        action: KeybindingAction::OrderlyEofOrDeleteForward,
        counts_as_editor_input: true,
        help: "Exit at an empty prompt; otherwise delete forward",
    },
    KeybindingSpec {
        id: KeybindingId::ReverseHistory,
        display: "Ctrl+R",
        bytes: &[18],
        action: KeybindingAction::ReverseHistorySearch,
        counts_as_editor_input: true,
        help: "Search session history in reverse",
    },
    KeybindingSpec {
        id: KeybindingId::Suspend,
        display: "Ctrl+Z",
        bytes: &[26],
        action: KeybindingAction::SuspendTransaction,
        counts_as_editor_input: true,
        help: "Restore the terminal, suspend, and recapture on resume",
    },
];
pub fn keybinding_for_bytes(bytes: &[u8]) -> Option<&'static KeybindingSpec> {
    KEYBINDINGS.iter().find(|binding| binding.bytes == bytes)
}
