// @generated by packages/ibex-devtools/src/scripts/generate-session-constants.mjs
// Source: session/session-constants.v1.json
// Source SHA-256: 78ef96d94ef781673388c0caa978edae6800b4b9a35efed2a10fddbaade7aff2
// Schema: session/schema/session-constants.schema.json
// Schema SHA-256: 24d44b3df879786eec06722d0eb384efd93dbc95b4aef55027ecf7783bc6de38
// Generator SHA-256: f471b77374ae5131d3262ef7f122993a5e3c7e50e98df70377486512ece0b23a
// Do not edit by hand.
// @ref LLP 0025#12-constants — generated projection of the v1 annex

#![allow(dead_code)]

pub const SESSION_CONSTANTS_SOURCE_SHA256: &str =
    "78ef96d94ef781673388c0caa978edae6800b4b9a35efed2a10fddbaade7aff2";
pub const SESSION_CONSTANTS_SCHEMA_SHA256: &str =
    "24d44b3df879786eec06722d0eb384efd93dbc95b4aef55027ecf7783bc6de38";
pub const SESSION_CONSTANTS_GENERATOR_SHA256: &str =
    "f471b77374ae5131d3262ef7f122993a5e3c7e50e98df70377486512ece0b23a";
pub const SESSION_CONSTANTS_VERSION: u32 = 1;

pub const PROMPT_DEFAULT_TEXT: &str = "➤ ";
pub const PROMPT_INTERRUPT_BYTE: u8 = 3;
pub const PROMPT_EDITOR_ERASE_BYTES: &[u8] = &[13, 27, 91, 50, 75];
pub const PROMPT_TRANSCRIPT_BOUNDARY_BYTES: &[u8] = &[10];
pub const ANSI_RESET: &str = "\u{1b}[0m";
pub const ANSI_SESSION_PROMPT: &str = "\u{1b}[36m";
pub const ANSI_SESSION_NOTICE: &str = "\u{1b}[33m";
pub const ANSI_SESSION_ERROR: &str = "\u{1b}[31m";
pub const ANSI_DISPLAY_STRING: &str = "\u{1b}[32m";
pub const ANSI_DISPLAY_NUMBER: &str = "\u{1b}[36m";
pub const ANSI_DISPLAY_KEYWORD: &str = "\u{1b}[35m";
pub const ANSI_DISPLAY_ERROR: &str = "\u{1b}[31m";
pub const ANSI_DISPLAY_KEY: &str = "\u{1b}[34m";
pub const ANSI_DISPLAY_TYPE_TAG: &str = "\u{1b}[33m";
pub const ANSI_DISPLAY_TRUNCATION: &str = "\u{1b}[2m";

pub const NOTICE_ORDERLY_PROMISE: &str = "press Ctrl+C again to end the session, or Ctrl+D to exit";
pub const NOTICE_CANCELLING_WORK: &str = "cancelling work — press Ctrl+C again to end the session";
pub const NOTICE_WORK_IN_FLIGHT: &str = "work is in flight — press Ctrl+C again to end the session";
pub const NOTICE_CANCELLING_COMPLETION: &str =
    "cancelling completion — press Ctrl+C again to end the session";
pub const NOTICE_INPUT_DISCARDED: &str = "input discarded";

pub const EXIT_STATUS_ORDERLY_DEFAULT: i32 = 0;
pub const EXIT_STATUS_NON_INTERACTIVE_FAILURE: i32 = 1;
pub const EXIT_STATUS_WORKER_COMMIT_UNACKNOWLEDGED: i32 = 69;
pub const EXIT_STATUS_ENGINE_FAULT: i32 = 70;
pub const EXIT_STATUS_STARTUP_FAILURE: i32 = 78;
pub const EXIT_STATUS_SIGHUP: i32 = 129;
pub const EXIT_STATUS_INTERRUPT: i32 = 130;
pub const EXIT_STATUS_SIGQUIT: i32 = 131;
pub const EXIT_STATUS_BROKEN_PIPE: i32 = 141;
pub const EXIT_STATUS_SIGTERM: i32 = 143;
pub const POSIX_EXIT_STATUS_MASK: i32 = 255;

pub const BROKER_FLUSH_BUDGET_MILLIS: u64 = 500;
pub const HISTORY_LOCK_ACQUISITION_MILLIS: u64 = 250;
pub const LIFECYCLE_COMMIT_ACK_MILLIS: u64 = 2000;
pub const SHUTDOWN_DRAIN_BUDGET_MILLIS: Option<u64> = None;
pub const CANCELLATION_BUDGET_MILLIS: Option<u64> = None;
pub const COMPLETION_BUDGET_MILLIS: Option<u64> = None;
pub const ASYNC_STORM_COALESCING_WINDOW_MILLIS: Option<u64> = None;

pub const DISPLAY_RENDER_DEPTH: usize = 4;
pub const DISPLAY_RENDER_BREADTH: usize = 128;
pub const DISPLAY_PAYLOAD_SCALARS: usize = 10000;
pub const HISTORY_MAX_ENTRIES: usize = 10000;
pub const HISTORY_MAX_BYTES: usize = 8388608;
pub const HISTORY_RECORD_MAX_BYTES: usize = 1048576;
pub const BROKER_QUEUE_BOUND_BYTES: usize = 8388608;
pub const DISPLAY_TREE_MAX_SERIALIZED_BYTES: usize = 16777216;
pub const MAX_LIVE_RELAYS: usize = 64;
pub const MAX_INPUT_BYTES: usize = 1048576;

pub const RENDER_CHILDREN_OPEN: &[u8] = &[32, 91];
pub const RENDER_CHILDREN_SEPARATOR: &[u8] = &[44, 32];
pub const RENDER_CHILDREN_CLOSE: &[u8] = &[93];
pub const RENDER_PAYLOAD_TRUNCATION_SEPARATOR: &[u8] = &[32];
pub const TRUNCATION_PREFIX: &str = "… +";
pub const TRUNCATION_SUFFIX: &str = " more";
pub const DISPLAY_FALLBACK_PREFIX: &str = "[display unavailable: ";
pub const DISPLAY_FALLBACK_SUFFIX: &str = "]";
pub const UNKNOWN_DISPLAY_NODE_PREFIX: &str = "[Unknown display node ";
pub const UNKNOWN_DISPLAY_NODE_SUFFIX: &str = "]";
pub const DISPLAY_FALLBACK_REASON_OVERSIZE_TREE: &str = "display tree exceeds 16 MiB";
pub const DISPLAY_FALLBACK_REASON_MALFORMED_OR_UNKNOWN_TREE: &str =
    "malformed or unknown display tree";
pub const DISPLAY_FALLBACK_REASON_RENDERED_TOO_LARGE: &str =
    "rendered display exceeds broker queue bound";

pub const DISPLAY_TREE_MAGIC: &[u8; 4] = b"IBDX";
pub const DISPLAY_TREE_WIRE_VERSION: u16 = 1;
pub const DISPLAY_TREE_ENDIANNESS: &str = "little";
pub const DISPLAY_TREE_LITTLE_ENDIAN: bool = true;
pub const DISPLAY_TREE_ROOT_DEPTH: usize = 1;
pub const DISPLAY_TREE_HEADER_ORDER: &[&str] = &["magic", "version"];
pub const DISPLAY_TREE_NODE_ORDER: &[&str] =
    &["kind", "payloadLength", "payload", "childCount", "children"];
pub const DISPLAY_TREE_MAGIC_BITS: u8 = 32;
pub const DISPLAY_TREE_VERSION_BITS: u8 = 16;
pub const DISPLAY_TREE_KIND_BITS: u8 = 16;
pub const DISPLAY_TREE_PAYLOAD_LENGTH_BITS: u8 = 32;
pub const DISPLAY_TREE_CHILD_COUNT_BITS: u8 = 32;
pub const DISPLAY_NODE_TAG_TEXT: u16 = 1;
pub const DISPLAY_NODE_TAG_STRING: u16 = 2;
pub const DISPLAY_NODE_TAG_NUMBER: u16 = 3;
pub const DISPLAY_NODE_TAG_BOOLEAN: u16 = 4;
pub const DISPLAY_NODE_TAG_NULL: u16 = 5;
pub const DISPLAY_NODE_TAG_UNDEFINED: u16 = 6;
pub const DISPLAY_NODE_TAG_ERROR: u16 = 7;
pub const DISPLAY_NODE_TAG_KEY: u16 = 8;
pub const DISPLAY_NODE_TAG_TYPE_TAG: u16 = 9;
pub const DISPLAY_NODE_TAG_CYCLE: u16 = 10;
pub const DISPLAY_NODE_TAG_TRUNCATION: u16 = 11;
