// @system @ref LLP 0003 — Hermes runtime bridge for Exact's server-connected runtime
#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-parameter"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#endif
#if defined(__has_include)
#if __has_include(<hermes/AsyncDebuggerAPI.h>)
#include <hermes/AsyncDebuggerAPI.h>
#endif
#endif
#include <hermes/hermes.h>
#include <jsi/jsi.h>
#include <jsi/instrumentation.h>
#if defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#include <algorithm>
#include <atomic>
#include <cerrno>
#include <cstdlib>
#include <cstring>
#if defined(__APPLE__)
#include <crt_externs.h>
#endif
#include <chrono>
#include <deque>
#include <future>
#include <iomanip>
#include <cctype>
#include <condition_variable>
#include <memory>
#include <mutex>
#include <sstream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <optional>
#include <vector>
#include <thread>
#include <tuple>
#include <type_traits>
#if defined(_WIN32)
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <direct.h>
#include <malloc.h>
#include <windows.h>
#else
#include <sys/poll.h>
#include <unistd.h>
#include <sys/resource.h>
#include <sys/wait.h>
#include <spawn.h>
#if defined(__linux__)
#include <sys/epoll.h>
#elif defined(__APPLE__)
#include <sys/event.h>
#include <sys/time.h>
#endif
#include <sys/ioctl.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <sys/uio.h>
#include <sys/time.h>
#include <csignal>
#include <pwd.h>
#include <dirent.h>
#include <sys/types.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <ifaddrs.h>
#include <net/if.h>
#endif
#if defined(__APPLE__)
#include <mach/mach.h>
#include <mach/mach_host.h>
#include <mach-o/dyld.h>
#include <sys/sysctl.h>
#include <CommonCrypto/CommonDigest.h>
#include <CommonCrypto/CommonHmac.h>
#include <CommonCrypto/CommonCryptor.h>
#include <CommonCrypto/CommonKeyDerivation.h>
#include <Security/SecRandom.h>
#include <Security/Security.h>
// GCM functions exist in CommonCrypto but are not in public headers
extern "C" {
  CCCryptorStatus CCCryptorGCMOneshotEncrypt(
      CCAlgorithm alg, const void *key, size_t keyLength,
      const void *iv, size_t ivLength,
      const void *aData, size_t aDataLength,
      const void *dataIn, size_t dataInLength,
      void *cipherOut,
      void *tagOut, size_t tagLength);
  CCCryptorStatus CCCryptorGCMOneshotDecrypt(
      CCAlgorithm alg, const void *key, size_t keyLength,
      const void *iv, size_t ivLength,
      const void *aData, size_t aDataLength,
      const void *cipherIn, size_t dataInLength,
      void *dataOut,
      const void *tagIn, size_t tagLength);
}
#include <zlib.h>
#if !defined(EXACT_NO_BROTLI)
#include <brotli/encode.h>
#include <brotli/decode.h>
#endif
#include <resolv.h>
#include <arpa/nameser.h>
#if !defined(EXACT_NO_OPENSSL)
// OpenSSL on macOS for Ed25519/X25519/ECDSA and key import/export
#include <openssl/evp.h>
#include <openssl/pem.h>
#include <openssl/err.h>
#include <openssl/ec.h>
#include <openssl/x509.h>
#include <openssl/bn.h>
#include <openssl/param_build.h>
#include <openssl/core_names.h>
#endif // !EXACT_NO_OPENSSL
#elif !defined(_WIN32)
#include <sys/sysinfo.h>
#include <openssl/evp.h>
#include <openssl/hmac.h>
#include <openssl/pem.h>
#include <openssl/err.h>
#include <openssl/ec.h>
#include <openssl/x509.h>
#include <openssl/bn.h>
#include <openssl/param_build.h>
#include <openssl/core_names.h>
#include <zlib.h>
#include <brotli/encode.h>
#include <brotli/decode.h>
#include <resolv.h>
#include <arpa/nameser.h>
#endif

#if !defined(__APPLE__) && !defined(_WIN32)
extern "C" char **environ;
#endif

// Precompiled Hermes bytecode for bootstrap JS (generated by build.rs)
#if __has_include("bootstrap_bytecode.h")
#include "bootstrap_bytecode.h"
#define HAS_PRECOMPILED_BOOTSTRAP 1
#endif

// JS source literals for bootstrap (generated by build.rs from bootstrap/*.js)
#if __has_include("bootstrap_source.h")
#include "bootstrap_source.h"
#endif

#include "hermes_runtime_internal.h"

// PATH_MAX / realpath live in <limits.h> on Linux; macOS pulls them in
// transitively. Spell it out so the realpath() path-resolution helpers build
// on Linux. @ref LLP 0177
#include <limits.h>

thread_local uint64_t g_active_module_id = 0;

// Concrete Buffer for static HBC byte arrays (used by precompiled bootstrap)
#ifdef HAS_PRECOMPILED_BOOTSTRAP
class StaticHBCBuffer : public facebook::jsi::Buffer {
    const uint8_t* data_;
    size_t size_;
public:
    StaticHBCBuffer(const uint8_t* data, size_t size) : data_(data), size_(size) {}
    size_t size() const override { return size_; }
    const uint8_t* data() const override { return data_; }
};
#endif

// Process start time for process.uptime()
static const auto g_process_start_time = std::chrono::steady_clock::now();

bool startup_trace_enabled() {
  static int cached = -1;
  if (cached < 0) {
    const char* val = std::getenv("EX_STARTUP_TRACE");
    cached = (val && (val[0] == '1' || val[0] == 'y' || val[0] == 'Y')) ? 1 : 0;
  }
  return cached == 1;
}

bool env_flag_enabled(const char* env_name) {
  const char* val = std::getenv(env_name);
  return val && (val[0] == '1' || val[0] == 'y' || val[0] == 'Y');
}

extern "C" void ex_host_console_log(int32_t level, const char* message);
extern "C" int32_t ex_host_is_allow_all(void);
extern "C" int32_t ex_host_check_capability(uint64_t module_id, const char* capability);
extern "C" void ex_host_grant_capability(uint64_t module_id, const char* capability);
extern "C" void ex_host_log_event(const char* event_type,
                                  uint64_t module_id,
                                  const char* capability,
                                  int32_t result);
extern "C" void* ex_host_fs_open(const char* path, uint32_t flags);
extern "C" int32_t ex_host_fs_read(void* file, uint8_t* buf, uint32_t len);
extern "C" int32_t ex_host_fs_write(void* file, const uint8_t* buf, uint32_t len);
extern "C" void ex_host_fs_close(void* file);
extern "C" uint8_t* ex_host_fs_read_file(const char* path,
                                         uint32_t* out_len,
                                         int32_t* out_errno);
extern "C" void ex_host_free_buffer(uint8_t* buf, uint32_t len);
extern "C" char* ex_host_fs_stat(const char* path);
extern "C" char* ex_host_fs_lstat(const char* path);
extern "C" char* ex_host_fs_readdir(const char* path);
extern "C" int32_t ex_host_fs_mkdir(const char* path, int32_t recursive);
extern "C" int32_t ex_host_fs_rmdir(const char* path);
extern "C" int32_t ex_host_fs_unlink(const char* path);
extern "C" int32_t ex_host_fs_rename(const char* from, const char* to);
extern "C" int32_t ex_host_fs_copy(const char* from, const char* to);
extern "C" char* ex_host_fs_realpath(const char* path);
extern "C" int32_t ex_host_fs_access(const char* path, int32_t mode);
extern "C" int32_t ex_host_fs_chmod(const char* path, uint32_t mode);
extern "C" char* ex_host_fs_mkdtemp(const char* prefix);
extern "C" int32_t ex_host_fs_append(const char* path, const uint8_t* data, uint32_t len);
extern "C" uint32_t ex_host_env_get(const char* key, char* out_buf, uint32_t len);
extern "C" int32_t ex_host_random_fill(uint8_t* buf, uint32_t len);
extern "C" char* ex_host_module_resolve(const char* specifier, const char* referrer);
extern "C" void ex_host_free_string(char* value);
extern "C" int32_t exact_get_state_mirror_buffer(
    void* handle,
    uint8_t** out_ptr,
    size_t* out_size);
extern "C" int64_t exact_module_get_state_offset(void* handle, uint16_t module_id);
extern "C" int32_t exact_get_layout(
    void* handle,
    uint32_t view_id,
    float* out_x,
    float* out_y,
    float* out_width,
    float* out_height);
extern "C" int32_t exact_get_absolute_layout(
    void* handle,
    uint32_t view_id,
    float* out_x,
    float* out_y,
    float* out_width,
    float* out_height);
extern "C" uint32_t exact_get_layout_generation(void* handle);
extern "C" int32_t exact_hit_test(void* handle, float x, float y);
extern "C" int32_t exact_node_exists(void* handle, uint32_t view_id);
extern "C" int32_t exact_get_root_view_id(void* handle, uint32_t root_id);

// HTTP server (implemented in host/http_server.rs)
extern "C" char* ex_host_http_serve(uint16_t port, const char* hostname);
extern "C" char* ex_host_http_wait(uint32_t server_id, uint32_t timeout_ms);
extern "C" char* ex_host_http_read_body(uint32_t server_id, uint32_t request_id);
extern "C" int32_t ex_host_http_respond(
    uint32_t server_id,
    uint32_t request_id,
    uint16_t status,
    const char* headers_json,
    const uint8_t* body,
    uint32_t body_len);
extern "C" int32_t ex_host_http_respond_text(
    uint32_t server_id,
    uint32_t request_id,
    uint16_t status,
    const uint8_t* body,
    uint32_t body_len);
extern "C" int32_t ex_host_http_respond_json(
    uint32_t server_id,
    uint32_t request_id,
    uint16_t status,
    const uint8_t* body,
    uint32_t body_len);
extern "C" int32_t ex_host_http_respond_stream(
    uint32_t server_id,
    uint32_t request_id,
    uint16_t status,
    const char* headers_json);
extern "C" int32_t ex_host_http_respond_chunk(
    uint32_t server_id,
    uint32_t request_id,
    const uint8_t* chunk,
    uint32_t chunk_len);
extern "C" int32_t ex_host_http_respond_end(uint32_t server_id, uint32_t request_id);
extern "C" int32_t ex_host_http_respond_string(
    uint32_t server_id,
    uint32_t request_id,
    uint16_t status,
    const char* headers_json,
    const uint8_t* body,
    uint32_t body_len);
extern "C" char* ex_host_http_address(uint32_t server_id);
extern "C" char* ex_host_http_poll(uint32_t server_id);
extern "C" char* ex_host_http_drain(uint32_t server_id, uint32_t max_count);
extern "C" int32_t ex_host_http_close(uint32_t server_id, int32_t force);
extern "C" int32_t ex_host_http_is_referenced(uint32_t server_id);
extern "C" int32_t ex_host_http_has_referenced(void);
extern "C" int32_t ex_host_http_has_pending_requests(void);
extern "C" void ex_host_http_set_ref(uint32_t server_id, int32_t referenced);
extern "C" uint64_t ex_host_sqlite_open(const char* path, const char* options_json);
extern "C" int32_t ex_host_sqlite_close(uint64_t handle);
extern "C" char* ex_host_sqlite_prepare(uint64_t db_handle, const char* sql);
extern "C" int32_t ex_host_sqlite_finalize(uint64_t statement_handle);
extern "C" char* ex_host_sqlite_expanded_sql(uint64_t statement_handle);
extern "C" int32_t ex_host_sqlite_in_transaction(uint64_t handle);
extern "C" char* ex_host_sqlite_all(uint64_t statement_handle, const char* bindings_json);
extern "C" char* ex_host_sqlite_get(uint64_t statement_handle, const char* bindings_json);
extern "C" char* ex_host_sqlite_run(uint64_t statement_handle, const char* bindings_json);
extern "C" char* ex_host_sqlite_values(uint64_t statement_handle, const char* bindings_json);
extern "C" char* ex_host_sqlite_exec(uint64_t handle, const char* sql, const char* bindings_json);

// Native WebSocket (implemented in native_websocket_macos.mm using NSURLSessionWebSocketTask)
typedef void (*NativeWsOpenCallback)(uint32_t ws_id, const char* protocol, const char* extensions, void* context);
typedef void (*NativeWsMessageCallback)(uint32_t ws_id, const uint8_t* data, size_t length, int is_text, void* context);
typedef void (*NativeWsCloseCallback)(uint32_t ws_id, uint16_t code, const char* reason, int was_clean, void* context);
typedef void (*NativeWsErrorCallback)(uint32_t ws_id, const char* message, void* context);
typedef void (*NativeWsBytesSentCallback)(uint32_t ws_id, size_t bytes_sent, void* context);
extern "C" uint32_t native_ws_connect(
    const char* url,
    const char* protocols,
    NativeWsOpenCallback open_cb,
    NativeWsMessageCallback message_cb,
    NativeWsCloseCallback close_cb,
    NativeWsErrorCallback error_cb,
    NativeWsBytesSentCallback bytes_sent_cb,
    void* context
);
extern "C" void native_ws_send(uint32_t ws_id, const uint8_t* data, size_t length, int is_text);
extern "C" void native_ws_close(uint32_t ws_id, uint16_t code, const char* reason);
extern "C" void native_ws_pause(uint32_t ws_id);
extern "C" void native_ws_resume(uint32_t ws_id);
extern "C" void native_ws_set_flow_controlled(uint32_t ws_id, int enabled);
extern "C" void native_ws_destroy(uint32_t ws_id);
extern "C" int native_ws_has_active(void);
extern "C" void native_ws_retain_context(void* context);
extern "C" void native_ws_release_context(void* context);

// Native fetch (implemented in native_fetch_macos.mm using NSURLSession)
typedef void (*NativeFetchResponseCallback)(
    uint32_t request_id,
    int status,
    const char* status_text,
    const char* headers,
    const uint8_t* body,
    size_t body_length,
    void* context
);
extern "C" void native_fetch_perform(
    uint32_t request_id,
    const char* method,
    const char* url,
    const char* headers,
    int decompress,
    const uint8_t* body,
    size_t body_length,
    NativeFetchResponseCallback response_callback,
    void* context);
extern "C" void native_fetch_cancel(uint32_t request_id);

class MemoryBuffer : public facebook::jsi::Buffer {
 public:
  MemoryBuffer(const uint8_t* data, size_t len) : size_(len), data_(data, data + len) {
    data_.push_back(0);
  }

  size_t size() const override { return size_; }
  const uint8_t* data() const override { return data_.data(); }

 private:
  size_t size_;
  std::vector<uint8_t> data_;
};

class AlignedBytecodeBuffer : public facebook::jsi::Buffer {
 public:
  AlignedBytecodeBuffer(const uint8_t* data, size_t len) : size_(len), data_(nullptr) {
    if (len == 0) {
      return;
    }
    const size_t alignment = alignof(std::max_align_t);
    size_t padded = (len + alignment - 1) & ~(alignment - 1);
#if defined(_WIN32)
    data_ = static_cast<uint8_t*>(_aligned_malloc(padded, alignment));
    if (!data_) {
      throw std::bad_alloc();
    }
#else
    if (posix_memalign(reinterpret_cast<void**>(&data_), alignment, padded) != 0) {
      data_ = nullptr;
      throw std::bad_alloc();
    }
#endif
    memcpy(data_, data, len);
  }

  ~AlignedBytecodeBuffer() {
    if (data_) {
#if defined(_WIN32)
      _aligned_free(data_);
#else
      free(data_);
#endif
    }
  }

  size_t size() const override { return size_; }
  const uint8_t* data() const override { return data_; }

 private:
  size_t size_{0};
  uint8_t* data_;
};

std::string valueToString(facebook::jsi::Runtime& rt, const facebook::jsi::Value& value) {
  if (value.isUndefined()) {
    return "undefined";
  }
  if (value.isNull()) {
    return "null";
  }
  if (value.isObject()) {
    // Check if this is an Error instance — Error properties are non-enumerable
    // so JSON.stringify returns "{}" which is useless.
    try {
      auto obj = value.getObject(rt);
      auto errorCtor = rt.global().getProperty(rt, "Error");
      if (errorCtor.isObject()) {
        auto isInstance = rt.global()
            .getPropertyAsObject(rt, "Object")
            .getPropertyAsFunction(rt, "getPrototypeOf");
        // Simple check: see if the object has a .message property (duck-type Error)
        auto msgProp = obj.getProperty(rt, "message");
        auto stackProp = obj.getProperty(rt, "stack");
        if (msgProp.isString()) {
          std::string result = msgProp.asString(rt).utf8(rt);
          if (stackProp.isString()) {
            auto stack = stackProp.asString(rt).utf8(rt);
            if (!stack.empty()) {
              result += "\n" + stack;
            }
          }
          return result;
        }
      }
    } catch (...) {
    }
    try {
      auto jsonObj = rt.global().getPropertyAsObject(rt, "JSON");
      auto stringify = jsonObj.getPropertyAsFunction(rt, "stringify");
      auto pretty = stringify.call(rt, value, facebook::jsi::Value::null(), facebook::jsi::Value(2.0));
      if (pretty.isString()) {
        return pretty.asString(rt).utf8(rt);
      }
    } catch (const facebook::jsi::JSError&) {
    } catch (...) {
    }
  }
  return value.toString(rt).utf8(rt);
}

facebook::jsi::Function makeLogFunction(facebook::jsi::Runtime& rt, int32_t level) {
  return facebook::jsi::Function::createFromHostFunction(
      rt,
      facebook::jsi::PropNameID::forAscii(rt, "log"),
      1,
      [level](facebook::jsi::Runtime& runtime,
              const facebook::jsi::Value&,
              const facebook::jsi::Value* args,
              size_t count) -> facebook::jsi::Value {
        std::string message;
        for (size_t i = 0; i < count; ++i) {
          if (i > 0) {
            message += " ";
          }
          message += valueToString(runtime, args[i]);
        }
        ex_host_console_log(level, message.c_str());
        return facebook::jsi::Value::undefined();
      });
}

uint64_t nowMs() {
  using namespace std::chrono;
  return duration_cast<milliseconds>(system_clock::now().time_since_epoch()).count();
}

double processUptimeSeconds() {
  auto elapsed = std::chrono::duration<double>(std::chrono::steady_clock::now() -
                                               g_process_start_time);
  return elapsed.count();
}

[[noreturn]] void exactHostExit(int code) {
#if defined(_WIN32)
  ExitProcess(static_cast<UINT>(code));
#else
  std::exit(code);
#endif
}

facebook::jsi::Function makeHardExitFn(facebook::jsi::Runtime& rt) {
  auto fn = facebook::jsi::Function::createFromHostFunction(
      rt,
      facebook::jsi::PropNameID::forAscii(rt, "exit"),
      1,
      [](facebook::jsi::Runtime& runtime,
         const facebook::jsi::Value&,
         const facebook::jsi::Value* args,
         size_t count) -> facebook::jsi::Value {
        int code = 0;
        if (count > 0) {
          if (args[0].isNumber()) {
            code = static_cast<int>(args[0].asNumber());
          } else if (args[0].isString()) {
            try {
              code = std::stoi(args[0].getString(runtime).utf8(runtime));
            } catch (...) {
              code = 0;
            }
          }
        }
        try {
          auto processObj = runtime.global().getProperty(runtime, "process");
          if (!processObj.isObject()) {
            exactHostExit(code);
          }
          auto process = processObj.asObject(runtime);
          process.setProperty(runtime, "exitCode", facebook::jsi::Value(code));
        } catch (...) {
        }
        exactHostExit(code);
      });
  try {
    fn.setProperty(rt, "__exactHostExit", facebook::jsi::Value(true));
  } catch (...) {
  }
  return fn;
}

void drainMicrotasks(facebook::jsi::Runtime& rt) {
#if defined(_WIN32)
  rt.drainMicrotasks(1024);
#else
  rt.drainMicrotasks(-1);
#endif
}

void cleanupFetchCallbacks(ExactHermesRuntime* runtime);
extern "C" int ex_hermes_poll(ExactHermesRuntime* runtime, uint64_t now_ms);
extern "C" int64_t ex_hermes_next_timer(ExactHermesRuntime* runtime);
extern "C" int ex_hermes_has_pending_tasks(ExactHermesRuntime* runtime);
extern "C" uint32_t ex_hermes_callback_backlog(ExactHermesRuntime* runtime);

std::mutex g_runtimeRegistryMutex;
std::unordered_set<ExactHermesRuntime*> g_activeRuntimes;

void registerRuntime(ExactHermesRuntime* runtime) {
  if (!runtime) return;
  std::lock_guard<std::mutex> lock(g_runtimeRegistryMutex);
  g_activeRuntimes.insert(runtime);
}

void unregisterRuntime(ExactHermesRuntime* runtime) {
  if (!runtime) return;
  std::lock_guard<std::mutex> lock(g_runtimeRegistryMutex);
  g_activeRuntimes.erase(runtime);
}

bool runtimeIsAliveImpl(ExactHermesRuntime* runtime) {
  if (!runtime) return false;
  std::lock_guard<std::mutex> lock(g_runtimeRegistryMutex);
  return g_activeRuntimes.find(runtime) != g_activeRuntimes.end();
}

bool hasPendingFetchCallbacks(ExactHermesRuntime* runtime) {
  if (!runtime) {
    return false;
  }

  std::lock_guard<std::mutex> lock(runtime->fetchMutex);
  return !runtime->fetchCallbacks.empty();
}

void cleanupFetchCallbacks(ExactHermesRuntime* runtime) {
  if (!runtime || !runtime->runtime) {
    return;
  }

  auto now = std::chrono::steady_clock::now();
  std::vector<std::tuple<uint32_t, std::shared_ptr<facebook::jsi::Function>, std::string>> expired;

  {
    std::lock_guard<std::mutex> lock(runtime->fetchMutex);
    for (auto it = runtime->fetchCallbacks.begin();
         it != runtime->fetchCallbacks.end();) {
      if (it->second.deadline <= now) {
        expired.push_back({
            it->first,
            std::move(it->second.reject),
            std::move(it->second.url),
        });
        it = runtime->fetchCallbacks.erase(it);
      } else {
        ++it;
      }
    }
  }

  for (auto& entry : expired) {
    auto request_id = std::get<0>(entry);
    auto& reject = std::get<1>(entry);
    auto& url = std::get<2>(entry);
    // Expiry must also cancel the in-flight native task (NSURLSession et al.),
    // not just reject the JS promise. @tactical @ref LLP 0159 R2
    native_fetch_cancel(request_id);
    if (!reject) {
      continue;
    }
    try {
      reject->call(*runtime->runtime,
                   facebook::jsi::JSError(*runtime->runtime,
                                          ("Fetch timeout: " + url).c_str())
                       .value());
    } catch (...) {
    }
  }
}

extern "C" void native_ws_retain_context(void* context) {
  auto* ctx = static_cast<NativeWebSocketCallbackContext*>(context);
  if (!ctx) {
    return;
  }
  ctx->ref_count.fetch_add(1, std::memory_order_relaxed);
}

extern "C" void native_ws_release_context(void* context) {
  auto* ctx = static_cast<NativeWebSocketCallbackContext*>(context);
  if (!ctx) {
    return;
  }
  if (ctx->ref_count.fetch_sub(1, std::memory_order_acq_rel) == 1) {
    // The final release can land on an NSURLSession/dispatch thread, but
    // deleting ctx destroys a jsi::Object, which is only safe on the JS
    // thread while the runtime is alive. Marshal the delete there; if the
    // runtime is already gone, intentionally leak the context rather than
    // destroy a JSI handle after runtime teardown (UB).
    // @tactical @ref LLP 0159 R3
    auto* runtime = ctx->runtime;
    if (!runtime || !runtimeIsAlive(runtime)) {
      return;  // leak-on-dead-runtime fallback
    }
    if (std::this_thread::get_id() == runtime->runtime_thread) {
      delete ctx;
      return;
    }
    // If the runtime dies before the callback runs, the queued lambda is
    // destroyed without running and ctx leaks (same documented fallback).
    pushRuntimeCallback(runtime, [ctx](facebook::jsi::Runtime&) { delete ctx; });
  }
}

struct CFUniqueReleaser {
  void operator()(const void* ptr) const {
    if (ptr) {
#if defined(__APPLE__)
      CFRelease(ptr);
#endif
    }
  }
};

using CFUniquePtr = std::unique_ptr<const void, CFUniqueReleaser>;

template <typename T>
using CFRefPtr = std::unique_ptr<std::remove_pointer_t<T>, CFUniqueReleaser>;

template <typename T>
CFRefPtr<T> adoptCF(T ptr) {
  return CFRefPtr<T>(ptr);
}

bool runtimeIsAlive(ExactHermesRuntime* runtime) {
  return runtimeIsAliveImpl(runtime);
}

extern "C" void ex_hermes_notify_callback();

void pushRuntimeCallback(ExactHermesRuntime* runtime,
                          std::function<void(facebook::jsi::Runtime&)> fn) {
    if (!runtimeIsAlive(runtime)) return;
    std::lock_guard<std::mutex> lock(runtime->callbackMutex);
    runtime->callbackQueue.push_back(std::move(fn));
    ex_hermes_notify_callback();
}

namespace {

int drainCallbackQueue(ExactHermesRuntime* runtime) {
    std::deque<std::function<void(facebook::jsi::Runtime&)>> queue;
    {
        std::lock_guard<std::mutex> lock(runtime->callbackMutex);
        queue.swap(runtime->callbackQueue);
    }
    int count = 0;
    for (auto& fn : queue) {
        try {
            fn(*runtime->runtime);
            count++;
        } catch (const facebook::jsi::JSError& err) {
            // Route the original thrown value through the uncaughtException
            // handler so stack/custom props survive, instead of flattening to
            // a console message. @tactical @ref LLP 0159 R6
            bool handled = false;
            try {
                auto& rt = *runtime->runtime;
                auto handler =
                    rt.global().getProperty(rt, "__exactUncaughtExceptionHandler");
                if (handler.isObject() && handler.asObject(rt).isFunction(rt)) {
                    auto errVal = facebook::jsi::Value(rt, err.value());
                    auto result =
                        handler.asObject(rt).asFunction(rt).call(rt, std::move(errVal));
                    if (result.isBool() && result.getBool()) handled = true;
                }
            } catch (...) {}
            if (!handled) {
                ex_host_console_log(1, err.getMessage().c_str());
            }
        } catch (const std::exception& err) {
            ex_host_console_log(1, err.what());
        } catch (...) {
            ex_host_console_log(1, "Callback execution failed");
        }
    }
    return count;
}

#if EXACT_HAS_HERMES_ASYNC_DEBUGGER
void emitScriptParsed(ExactHermesRuntime* runtime,
                      const facebook::hermes::debugger::SourceLocation& loc) {
  using facebook::hermes::debugger::kInvalidLocation;
  uint32_t line = loc.line == kInvalidLocation ? 0 : (loc.line > 0 ? loc.line - 1 : 0);
  uint32_t column = loc.column == kInvalidLocation ? 0 : (loc.column > 0 ? loc.column - 1 : 0);

  std::ostringstream out;
  out << "{\"method\":\"Debugger.scriptParsed\",\"params\":{";
  out << "\"scriptId\":" << jsonString(std::to_string(loc.fileId)) << ",";
  out << "\"url\":" << jsonString(loc.fileName) << ",";
  out << "\"startLine\":" << line << ",";
  out << "\"startColumn\":" << column << ",";
  out << "\"endLine\":0,";
  out << "\"endColumn\":0";
  out << "}}";
  pushDebugEvent(runtime, out.str());
}

void emitNewScriptsImpl(ExactHermesRuntime* runtime,
                        facebook::hermes::debugger::Debugger& debugger) {
  if (!runtime || !runtime->runtime) {
    return;
  }
  auto scripts = debugger.getLoadedScripts();
  for (const auto& script : scripts) {
    if (runtime->known_scripts.insert(script.fileId).second) {
      runtime->script_id_to_name[script.fileId] = script.fileName;
      emitScriptParsed(runtime, script);
    }
  }
}

// Template functions moved to hermes_runtime_templates.inl
// (shared with hermes_runtime_debugger.cc)
#include "hermes_runtime_templates.inl"
#endif

std::string getEnvValue(const std::string& key) {
  char buffer[4096];
  auto written = ex_host_env_get(key.c_str(), buffer, sizeof(buffer));
  if (written == 0) {
    return std::string();
  }
  return std::string(buffer, buffer + written);
}

void runNextTickQueue(ExactHermesRuntime* runtime);

// Native StringBuffer for O(1) amortized string append (avoids O(n^2) JS string concatenation)
class StringBufferHostObject : public facebook::jsi::HostObject {
public:
  std::string buffer;

  facebook::jsi::Value get(facebook::jsi::Runtime& rt, const facebook::jsi::PropNameID& name) override {
    auto propName = name.utf8(rt);
    if (propName == "append") {
      return facebook::jsi::Function::createFromHostFunction(rt, name, 1,
          [this](facebook::jsi::Runtime& rt, const facebook::jsi::Value&,
                 const facebook::jsi::Value* args, size_t count) -> facebook::jsi::Value {
            if (count > 0) {
              buffer += args[0].asString(rt).utf8(rt);
            }
            return facebook::jsi::Value::undefined();
          });
    }
    if (propName == "toString") {
      return facebook::jsi::Function::createFromHostFunction(rt, name, 0,
          [this](facebook::jsi::Runtime& rt, const facebook::jsi::Value&,
                 const facebook::jsi::Value*, size_t) -> facebook::jsi::Value {
            return facebook::jsi::String::createFromUtf8(rt, buffer);
          });
    }
    if (propName == "length") {
      return facebook::jsi::Value(static_cast<int>(buffer.size()));
    }
    if (propName == "clear") {
      return facebook::jsi::Function::createFromHostFunction(rt, name, 0,
          [this](facebook::jsi::Runtime&, const facebook::jsi::Value&,
                 const facebook::jsi::Value*, size_t) -> facebook::jsi::Value {
            buffer.clear();
            return facebook::jsi::Value::undefined();
          });
    }
    if (propName == "reserve") {
      return facebook::jsi::Function::createFromHostFunction(rt, name, 1,
          [this](facebook::jsi::Runtime&, const facebook::jsi::Value&,
                 const facebook::jsi::Value* args, size_t count) -> facebook::jsi::Value {
            if (count > 0) {
              buffer.reserve(static_cast<size_t>(args[0].asNumber()));
            }
            return facebook::jsi::Value::undefined();
          });
    }
    return facebook::jsi::Value::undefined();
  }

  void set(facebook::jsi::Runtime&, const facebook::jsi::PropNameID&, const facebook::jsi::Value&) override {}

  std::vector<facebook::jsi::PropNameID> getPropertyNames(facebook::jsi::Runtime& rt) override {
    std::vector<facebook::jsi::PropNameID> props;
    props.push_back(facebook::jsi::PropNameID::forAscii(rt, "append"));
    props.push_back(facebook::jsi::PropNameID::forAscii(rt, "toString"));
    props.push_back(facebook::jsi::PropNameID::forAscii(rt, "length"));
    props.push_back(facebook::jsi::PropNameID::forAscii(rt, "clear"));
    props.push_back(facebook::jsi::PropNameID::forAscii(rt, "reserve"));
    return props;
  }
};

// --- Spawn env helpers (used by __exactSpawnSync and __exactSpawn) ---

void installGlobals(struct ExactHermesRuntime* handle) {
  bool _tracing = startup_trace_enabled();
  bool sharedRuntimeInstalled = false;
  auto _t_host_functions = std::chrono::steady_clock::now();
  #define IG_TRACE_START(n) _t_##n = std::chrono::steady_clock::now()
  #define IG_TRACE_END(n) if (_tracing) { \
    auto _el = std::chrono::duration_cast<std::chrono::microseconds>( \
        std::chrono::steady_clock::now() - _t_##n).count(); \
    fprintf(stderr, "[startup]   %-28s %6lld us (%5.1f ms)\n", \
            #n, (long long)_el, _el / 1000.0); }

  auto& rt = *handle->runtime;
  auto _t_console_globals = std::chrono::steady_clock::now();
  installConsoleGlobals(handle);
  IG_TRACE_END(console_globals);

  bool skip_host_functions = env_flag_enabled("EX_SKIP_STARTUP_HOST_FUNCTIONS");
  if (skip_host_functions) {
    if (_tracing) {
      fprintf(stderr, "[startup]   host_functions skipped (set EX_SKIP_STARTUP_HOST_FUNCTIONS=0 to re-enable)\n");
    }
  } else {
  IG_TRACE_START(host_functions);
  installTimerGlobals(handle);
  installAndroidHostFunctions(handle);

  auto capabilityCheckFn = facebook::jsi::Function::createFromHostFunction(
      rt,
      facebook::jsi::PropNameID::forAscii(rt, "__exactCapabilityCheck"),
      1,
      [](facebook::jsi::Runtime& runtime,
         const facebook::jsi::Value&,
         const facebook::jsi::Value* args,
         size_t count) -> facebook::jsi::Value {
        if (count == 0) {
          return facebook::jsi::Value(false);
        }
        auto cap = args[0].toString(runtime).utf8(runtime);
        return facebook::jsi::Value(checkCapability(cap));
      });
  rt.global().setProperty(rt, "__exactCapabilityCheck", std::move(capabilityCheckFn));

  auto getEnvFn = facebook::jsi::Function::createFromHostFunction(
      rt,
      facebook::jsi::PropNameID::forAscii(rt, "__exactGetEnv"),
      1,
      [](facebook::jsi::Runtime& runtime,
         const facebook::jsi::Value&,
         const facebook::jsi::Value* args,
         size_t count) -> facebook::jsi::Value {
        if (count == 0) {
          return facebook::jsi::Value::undefined();
        }
        auto key = args[0].toString(runtime).utf8(runtime);
        std::string cap = "env:read:" + key;
        if (!checkCapability(cap)) {
          return facebook::jsi::Value::undefined();
        }
        auto value = getEnvValue(key);
        if (value.empty()) {
          return facebook::jsi::Value::undefined();
        }
        return facebook::jsi::Value(
            facebook::jsi::String::createFromUtf8(runtime, value));
      });
  rt.global().setProperty(rt, "__exactGetEnv", std::move(getEnvFn));

  auto getAllEnvFn = facebook::jsi::Function::createFromHostFunction(
      rt,
      facebook::jsi::PropNameID::forAscii(rt, "__exactGetAllEnv"),
      0,
      [](facebook::jsi::Runtime& runtime,
         const facebook::jsi::Value&,
         const facebook::jsi::Value*,
         size_t) -> facebook::jsi::Value {
        facebook::jsi::Object env(runtime);
        if (!checkCapability("env:read:*")) {
          return env;
        }
#if defined(_WIN32)
        char **envp = nullptr;
#elif defined(__APPLE__)
        char **envp = *_NSGetEnviron();
#else
        char **envp = ::environ;
#endif
        if (envp) {
          for (char **ep = envp; *ep; ++ep) {
            std::string entry(*ep);
            auto eq = entry.find('=');
            if (eq != std::string::npos) {
              auto key = entry.substr(0, eq);
              auto val = entry.substr(eq + 1);
              env.setProperty(runtime,
                facebook::jsi::PropNameID::forUtf8(runtime, key),
                facebook::jsi::String::createFromUtf8(runtime, val));
            }
          }
        }
        return env;
      });
  rt.global().setProperty(rt, "__exactGetAllEnv", std::move(getAllEnvFn));

  auto setActiveModuleIdFn = facebook::jsi::Function::createFromHostFunction(
      rt,
      facebook::jsi::PropNameID::forAscii(rt, "__exactSetActiveModuleId"),
      1,
      [](facebook::jsi::Runtime&,
               const facebook::jsi::Value&,
               const facebook::jsi::Value* args,
               size_t count) -> facebook::jsi::Value {
        auto previous = g_active_module_id;
        if (count > 0 && args[0].isNumber()) {
          auto next = args[0].asNumber();
          g_active_module_id = next < 0.0 ? 0 : static_cast<uint64_t>(next);
        } else {
          g_active_module_id = 0;
        }
        return facebook::jsi::Value(static_cast<double>(previous));
      });
  rt.global().setProperty(rt, "__exactSetActiveModuleId", std::move(setActiveModuleIdFn));

  auto getCwdFn = facebook::jsi::Function::createFromHostFunction(
      rt,
      facebook::jsi::PropNameID::forAscii(rt, "__exactGetCwd"),
      0,
      [](facebook::jsi::Runtime& runtime,
         const facebook::jsi::Value&,
         const facebook::jsi::Value*,
         size_t) -> facebook::jsi::Value {
        char buffer[4096];
#if defined(_WIN32)
        if (_getcwd(buffer, sizeof(buffer)) == nullptr) {
#else
        if (getcwd(buffer, sizeof(buffer)) == nullptr) {
#endif
          return facebook::jsi::Value::undefined();
        }
        return facebook::jsi::Value(
          facebook::jsi::String::createFromUtf8(runtime, buffer));
      });
  rt.global().setProperty(rt, "__exactGetCwd", std::move(getCwdFn));

  auto setCwdFn = facebook::jsi::Function::createFromHostFunction(
      rt,
      facebook::jsi::PropNameID::forAscii(rt, "__exactSetCwd"),
      1,
      [](facebook::jsi::Runtime& runtime,
         const facebook::jsi::Value&,
         const facebook::jsi::Value* args,
         size_t count) -> facebook::jsi::Value {
        if (count == 0 || !args[0].isString()) {
          throw facebook::jsi::JSError(
              runtime,
              "process.chdir() expected path string");
        }
        auto path = args[0].toString(runtime).utf8(runtime);
#if defined(_WIN32)
        if (_chdir(path.c_str()) != 0) {
#else
        if (chdir(path.c_str()) != 0) {
#endif
          throw facebook::jsi::JSError(
              runtime,
              "Failed to change directory: " + std::string(strerror(errno)));
        }
      return facebook::jsi::Value::undefined();
      });
  rt.global().setProperty(rt, "__exactSetCwd", std::move(setCwdFn));

  // __exactExit(code) — escape hatch used by JS runtime process implementation.
  auto exactExitFn = facebook::jsi::Function::createFromHostFunction(
      rt,
      facebook::jsi::PropNameID::forAscii(rt, "__exactExit"),
      1,
      [](facebook::jsi::Runtime& runtime,
         const facebook::jsi::Value&,
         const facebook::jsi::Value* args,
         size_t count) -> facebook::jsi::Value {
        int code = 0;
        if (count > 0) {
          if (args[0].isNumber()) {
            code = static_cast<int>(args[0].asNumber());
          } else if (args[0].isString()) {
            try {
              code = std::stoi(args[0].getString(runtime).utf8(runtime));
            } catch (...) {
              code = 0;
            }
          }
        }
        exactHostExit(code);
      });
  rt.global().setProperty(rt, "__exactExit", std::move(exactExitFn));

  installOsInfoGlobals(handle);

  installCryptoHostFunctions(handle);
#if defined(_WIN32)
  if (!handle->fs_functions_loaded) {
    handle->fs_functions_loaded = true;
    installFsHostFunctions(handle);
  }
#endif
  auto ensureFsFn = facebook::jsi::Function::createFromHostFunction(
      rt, facebook::jsi::PropNameID::forAscii(rt, "__exactEnsureFs"), 0,
      [handle](facebook::jsi::Runtime&, const facebook::jsi::Value&,
               const facebook::jsi::Value*, size_t) -> facebook::jsi::Value {
        if (!handle->fs_functions_loaded) {
          handle->fs_functions_loaded = true;
          installFsHostFunctions(handle);
        }
        return facebook::jsi::Value::undefined();
      });
  rt.global().setProperty(rt, "__exactEnsureFs", std::move(ensureFsFn));


  auto randomBytesFn = facebook::jsi::Function::createFromHostFunction(
      rt,
      facebook::jsi::PropNameID::forAscii(rt, "__exactRandomBytes"),
      1,
      [](facebook::jsi::Runtime& runtime,
         const facebook::jsi::Value&,
         const facebook::jsi::Value* args,
         size_t count) -> facebook::jsi::Value {
        if (count == 0 || !args[0].isNumber()) {
          return facebook::jsi::Value::undefined();
        }
        if (!checkCapability("crypto:random")) {
          throw facebook::jsi::JSError(runtime, "Permission denied");
        }
        auto len = static_cast<size_t>(args[0].asNumber());
        std::vector<uint8_t> data(len);
        if (len > 0) {
          if (ex_host_random_fill(data.data(), static_cast<uint32_t>(len)) != 0) {
            throw facebook::jsi::JSError(runtime, "Random fill failed");
          }
        }
        return makeUint8Array(runtime, std::move(data));
      });
  rt.global().setProperty(rt, "__exactRandomBytes", std::move(randomBytesFn));
  installProcessSetup(handle);

  // --- Web Crypto API (globalThis.crypto) ---
  {
    static const char* webCryptoJS = WEB_CRYPTO_SRC;

#ifdef HAS_PRECOMPILED_BOOTSTRAP
    handle->web_crypto_loaded = false;
    g_webCryptoJS = webCryptoJS;
#else
    try {
      auto buffer = std::make_shared<facebook::jsi::StringBuffer>(webCryptoJS);
      rt.evaluateJavaScript(buffer, "<web-crypto>");
    } catch (const facebook::jsi::JSError& err) {
      ex_host_console_log(1, (std::string("Web Crypto setup error: ") + err.getMessage()).c_str());
    } catch (const std::exception& err) {
      ex_host_console_log(1, (std::string("Web Crypto setup error: ") + err.what()).c_str());
    }
#endif
  }

  // --- localStorage / sessionStorage (file-backed) ---
  {
    static const char* storageJS = WEB_STORAGE_SRC;

#ifdef HAS_PRECOMPILED_BOOTSTRAP
    handle->web_storage_loaded = false;
    g_webStorageJS = storageJS;
#else
    try {
      auto buffer = std::make_shared<facebook::jsi::StringBuffer>(storageJS);
      rt.evaluateJavaScript(buffer, "<web-storage>");
    } catch (const facebook::jsi::JSError& err) {
      ex_host_console_log(1, (std::string("Storage setup error: ") + err.getMessage()).c_str());
    } catch (const std::exception& err) {
      ex_host_console_log(1, (std::string("Storage setup error: ") + err.what()).c_str());
    }
#endif
  }

  installWebSocketGlobals(handle);

  // --- FormData (globalThis.FormData) + multipart parser ---
  {
    static const char* formDataJS = FORM_DATA_SRC;

#ifdef HAS_PRECOMPILED_BOOTSTRAP
    handle->form_data_loaded = false;
    g_formDataJS = formDataJS;
#else
    try {
      auto buffer = std::make_shared<facebook::jsi::StringBuffer>(formDataJS);
      rt.evaluateJavaScript(buffer, "<form-data>");
    } catch (const facebook::jsi::JSError& err) {
      ex_host_console_log(1, (std::string("FormData setup error: ") + err.getMessage()).c_str());
    } catch (const std::exception& err) {
      ex_host_console_log(1, (std::string("FormData setup error: ") + err.what()).c_str());
    }
#endif
  }

  auto resolveModuleFn = facebook::jsi::Function::createFromHostFunction(
      rt,
      facebook::jsi::PropNameID::forAscii(rt, "__exactModuleResolve"),
      2,
      [](facebook::jsi::Runtime& runtime,
         const facebook::jsi::Value&,
         const facebook::jsi::Value* args,
         size_t count) -> facebook::jsi::Value {
        if (count == 0 || !args[0].isString()) {
          return facebook::jsi::Value::null();
        }
        auto spec = args[0].toString(runtime).utf8(runtime);
        std::string referrer;
        if (count > 1 && args[1].isString()) {
          referrer = args[1].toString(runtime).utf8(runtime);
        }
        char* json = ex_host_module_resolve(
            spec.c_str(),
            referrer.empty() ? nullptr : referrer.c_str());
        if (!json) {
          return facebook::jsi::Value::null();
        }
        auto result = facebook::jsi::String::createFromUtf8(runtime, json);
        ex_host_free_string(json);
        return result;
      });
  // Registered under TWO names: the canonical one (which the dev-server
  // hot-reload bootstrap REPLACES with a module-table override) and a
  // stable alias the override falls back to at CALL time. Capture-once
  // fallbacks proved injection-order-fragile — see LLP 0176 (native agent
  // boot: Module not found for runtime-js directory imports).
  auto resolveModuleValue = facebook::jsi::Value(rt, resolveModuleFn);
  rt.global().setProperty(rt, "__exactModuleResolve", resolveModuleValue);
  rt.global().setProperty(rt, "__exactNativeModuleResolve", resolveModuleValue);
  installFetchGlobals(handle);

  // Deferred: Http host functions (registered lazily on first use)
  auto ensureHttpFn = facebook::jsi::Function::createFromHostFunction(
      rt, facebook::jsi::PropNameID::forAscii(rt, "__exactEnsureHttp"), 0,
      [handle](facebook::jsi::Runtime&, const facebook::jsi::Value&,
               const facebook::jsi::Value*, size_t) -> facebook::jsi::Value {
        if (!handle->http_functions_loaded) {
          handle->http_functions_loaded = true;
          installHttpHostFunctions(handle);
        }
        return facebook::jsi::Value::undefined();
      });
  rt.global().setProperty(rt, "__exactEnsureHttp", std::move(ensureHttpFn));


  // Deferred: Sqlite host functions (registered lazily on first use)
  auto ensureSqliteFn = facebook::jsi::Function::createFromHostFunction(
      rt, facebook::jsi::PropNameID::forAscii(rt, "__exactEnsureSqlite"), 0,
      [handle](facebook::jsi::Runtime&, const facebook::jsi::Value&,
               const facebook::jsi::Value*, size_t) -> facebook::jsi::Value {
        if (!handle->sqlite_functions_loaded) {
          handle->sqlite_functions_loaded = true;
          installSqliteHostFunctions(handle);
        }
        return facebook::jsi::Value::undefined();
      });
  rt.global().setProperty(rt, "__exactEnsureSqlite", std::move(ensureSqliteFn));

  // Deferred: DNS host functions (registered lazily on first use)
  auto ensureDnsFn = facebook::jsi::Function::createFromHostFunction(
      rt, facebook::jsi::PropNameID::forAscii(rt, "__exactEnsureDns"), 0,
      [handle](facebook::jsi::Runtime&, const facebook::jsi::Value&,
               const facebook::jsi::Value*, size_t) -> facebook::jsi::Value {
        if (!handle->dns_functions_loaded) {
          handle->dns_functions_loaded = true;
          installDnsHostFunctions(handle);
        }
        return facebook::jsi::Value::undefined();
      });
  rt.global().setProperty(rt, "__exactEnsureDns", std::move(ensureDnsFn));



  // Deferred: ChildProcess host functions (registered lazily on first use)
  auto ensureChildProcessFn = facebook::jsi::Function::createFromHostFunction(
      rt, facebook::jsi::PropNameID::forAscii(rt, "__exactEnsureChildProcess"), 0,
      [handle](facebook::jsi::Runtime&, const facebook::jsi::Value&,
               const facebook::jsi::Value*, size_t) -> facebook::jsi::Value {
        if (!handle->child_process_functions_loaded) {
          handle->child_process_functions_loaded = true;
          installChildProcessHostFunctions(handle);
        }
        return facebook::jsi::Value::undefined();
      });
  rt.global().setProperty(rt, "__exactEnsureChildProcess", std::move(ensureChildProcessFn));


  // __StringBuffer: native string builder for O(1) amortized append
  // Avoids O(n^2) string concatenation in Hermes (no rope strings)
  rt.global().setProperty(
      rt,
      facebook::jsi::PropNameID::forAscii(rt, "__StringBuffer"),
      facebook::jsi::Function::createFromHostFunction(
          rt,
          facebook::jsi::PropNameID::forAscii(rt, "__StringBuffer"),
          0,
          [](facebook::jsi::Runtime& rt, const facebook::jsi::Value&,
             const facebook::jsi::Value*, size_t) -> facebook::jsi::Value {
            auto obj = std::make_shared<StringBufferHostObject>();
            return facebook::jsi::Object::createFromHostObject(rt, obj);
          }
      )
  );

  // ============================================================
  // TCP Socket host functions for net module
  // ============================================================
  // Deferred: Net host functions (registered lazily on first use)
  auto ensureNetFn = facebook::jsi::Function::createFromHostFunction(
      rt, facebook::jsi::PropNameID::forAscii(rt, "__exactEnsureNet"), 0,
      [handle](facebook::jsi::Runtime&, const facebook::jsi::Value&,
               const facebook::jsi::Value*, size_t) -> facebook::jsi::Value {
        if (!handle->net_functions_loaded) {
          handle->net_functions_loaded = true;
          installNetHostFunctions(handle);
        }
        return facebook::jsi::Value::undefined();
      });
  rt.global().setProperty(rt, "__exactEnsureNet", std::move(ensureNetFn));
  sharedRuntimeInstalled = installModuleLoader(handle);

  installLegacyLazyBootstrapGetters(handle, sharedRuntimeInstalled);
  IG_TRACE_END(host_functions);
  }

  // Compatibility post-bootstrap fixups for host shims used by test suites.
  // Run these before other high-level bootstrap scripts that expect stable
  // process metadata/config wiring.
  auto _t_post_host_fns = std::chrono::steady_clock::now();
  auto _t_versions_fix = std::chrono::steady_clock::now();
  auto _t_ipc_patch = std::chrono::steady_clock::now();
  runLegacyProcessCompatFix(handle, sharedRuntimeInstalled);

  // Legacy bootstraps rely on a hard process.exit() on the process object.
  // The shared runtime bundle installs a JS Process implementation whose
  // prototype exit() preserves Node's recursive exit listener semantics and
  // terminates through __exactExit(). Replacing it with a hard host function
  // breaks tests like test-process-exit-recursive.js by bypassing exit
  // listeners and exitCode overrides.
  if (!sharedRuntimeInstalled) {
    // NOTE: Only set exit on the process object itself, NOT on its prototype.
    // At this point process.__proto__ is Object.prototype, so setting exit there
    // would pollute every object's for...in enumeration.
    auto processValue = rt.global().getProperty(rt, "process");
    if (processValue.isObject()) {
      auto processObjFinal = processValue.asObject(rt);
      auto hardExitFn = makeHardExitFn(rt);
      processObjFinal.setProperty(rt, "exit", std::move(hardExitFn));
      // Note: Do NOT set exit on process.__proto__ as that would pollute
      // Object.prototype and make 'exit' enumerable on all objects, breaking
      // for...in loops (e.g., in WPT headers-basic tests).
    }
  }

  runLegacyCompatPolyfills(handle, sharedRuntimeInstalled);
  runLegacyExactGlobal(handle, sharedRuntimeInstalled);
  IG_TRACE_START(versions_fix);
  runFinalProcessVersionsFix(handle);
  IG_TRACE_END(versions_fix);
  IG_TRACE_START(ipc_patch);
  installIpcListenerPatch(handle);
  IG_TRACE_END(ipc_patch);
  IG_TRACE_END(post_host_fns);
}

void runNextTickQueue(ExactHermesRuntime* runtime) {
  if (!runtime) {
    return;
  }
  auto& rt = *runtime->runtime;
  while (!runtime->next_tick.empty()) {
    auto entry = std::move(runtime->next_tick.front());
    runtime->next_tick.pop_front();
    try {
      if (entry.args.empty()) {
        entry.callback.call(rt);
      } else {
        entry.callback.call(
            rt,
            static_cast<const facebook::jsi::Value*>(entry.args.data()),
            entry.args.size());
      }
    } catch (const facebook::jsi::JSError& err) {
      // Try uncaughtException handler first
      bool handled = false;
      try {
        auto handler = rt.global().getProperty(rt, "__exactUncaughtExceptionHandler");
        if (handler.isObject() && handler.asObject(rt).isFunction(rt)) {
          // Pass the original thrown value through (stack/custom props intact),
          // mirroring the timer error path. @tactical @ref LLP 0159 R6
          auto errVal = facebook::jsi::Value(rt, err.value());
          auto result = handler.asObject(rt).asFunction(rt).call(rt, std::move(errVal));
          if (result.isBool() && result.getBool()) handled = true;
        }
      } catch (...) {}
      if (!handled) {
        ex_host_console_log(1, err.getMessage().c_str());
      }
    } catch (const std::exception& err) {
      ex_host_console_log(1, err.what());
    }
  }
}

} // namespace

#if EXACT_HAS_HERMES_ASYNC_DEBUGGER
void emitNewScripts(ExactHermesRuntime* runtime,
                    facebook::hermes::debugger::Debugger& debugger) {
  emitNewScriptsImpl(runtime, debugger);
}
#endif

#define TRACE_START(name) \
  auto _trace_##name = std::chrono::steady_clock::now()
#define TRACE_END(name) \
  if (startup_trace_enabled()) { \
    auto _elapsed = std::chrono::duration_cast<std::chrono::microseconds>( \
        std::chrono::steady_clock::now() - _trace_##name).count(); \
    fprintf(stderr, "[startup] %-30s %6lld us (%5.1f ms)\n", \
            #name, (long long)_elapsed, _elapsed / 1000.0); \
  }

extern "C" ExactHermesRuntime* ex_hermes_create() {
  TRACE_START(total);
  TRACE_START(hermes_config);
  auto gcConfig = ::hermes::vm::GCConfig::Builder()
                      .withShouldRecordStats(true)
                      .withName("exact-runtime")
                      .build();
  auto configBuilder = ::hermes::vm::RuntimeConfig::Builder().withGCConfig(gcConfig);
#if defined(EXACT_HAVE_HERMES_MICROTASK_CONFIG)
  configBuilder.withMicrotaskQueue(true);
#endif
  auto config = configBuilder.withEnableEval(true).build();
  TRACE_END(hermes_config);

  TRACE_START(hermes_init);
  auto runtime = facebook::hermes::makeHermesRuntime(config);
  TRACE_END(hermes_init);
  if (!runtime) {
    return nullptr;
  }
  TRACE_START(handle_alloc);
  auto handle = new ExactHermesRuntime();
  handle->runtime = std::move(runtime);
  handle->runtime_thread = std::this_thread::get_id();
  TRACE_END(handle_alloc);

  TRACE_START(debugger_init);
#if defined(HERMES_ENABLE_DEBUGGER) && EXACT_HAS_HERMES_ASYNC_DEBUGGER
  try {
    handle->debugger =
        std::make_shared<facebook::hermes::debugger::AsyncDebuggerAPI>(*handle->runtime);
    handle->debugger_available.store(true);
  } catch (const facebook::jsi::JSError& err) {
    ex_host_console_log(1, err.getMessage().c_str());
    disableDebugger(handle);
  } catch (const std::exception& err) {
    ex_host_console_log(1, err.what());
    disableDebugger(handle);
  } catch (...) {
    ex_host_console_log(1, "Debugger not available in this Hermes build.");
    disableDebugger(handle);
  }
#else
  disableDebugger(handle);
#endif
  TRACE_END(debugger_init);

  TRACE_START(install_globals);
  installGlobals(handle);
  TRACE_END(install_globals);

  // Web Streams API polyfill (ReadableStream, WritableStream, TransformStream).
  // Run after all global bootstrap scripts so ReadableStream can be wrapped
  // on the final runtime surface that user code observes.
  if (env_flag_enabled("EX_WEB_STREAMS_POLYFILL")) {
    TRACE_START(web_streams_polyfill);
    installWebStreamsPolyfill(handle);
    TRACE_END(web_streams_polyfill);
  } else if (startup_trace_enabled()) {
    fprintf(stderr, "[startup]   web_streams_polyfill skipped (set EX_WEB_STREAMS_POLYFILL=1 to enable)\n");
  }
  registerRuntime(handle);

  TRACE_END(total);
  return handle;
}

extern "C" void ex_hermes_destroy(ExactHermesRuntime* runtime) {
  if (runtime == nullptr) {
    return;
  }
  disableDebugger(runtime);
  unregisterAndroidHostFunctions(runtime);
  unregisterRuntime(runtime);
  delete runtime;
}

extern "C" int ex_hermes_eval(
    ExactHermesRuntime* runtime,
    const uint8_t* data,
    size_t len,
    const char* source_url,
    int is_bytecode,
    char** out_value) {
  auto writeOutError = [&](const std::string& text) -> bool {
    if (!out_value) {
      return true;
    }

    char* heap = static_cast<char*>(malloc(text.size() + 1));
    if (!heap) {
      return false;
    }
    memcpy(heap, text.data(), text.size());
    heap[text.size()] = '\0';
    *out_value = heap;
    return true;
  };

  if (out_value) {
    *out_value = nullptr;
  }

  if (!runtime || !data || len == 0) {
    writeOutError("Hermes eval received invalid input");
    return 1;
  }

  std::string source = source_url ? source_url : (is_bytecode ? "<bytecode>" : "<eval>");
  bool traceEval = startup_trace_enabled();
  if (!is_bytecode) {
    runtime->sources_by_name[source] = std::string(reinterpret_cast<const char*>(data), len);
  }

  try {
    auto writeOutString = [&](const std::string& text) -> bool {
      if (!out_value) {
        return true;
      }

      char* heap = static_cast<char*>(malloc(text.size() + 1));
      if (!heap) {
        return false;
      }
      memcpy(heap, text.data(), text.size());
      heap[text.size()] = '\0';
      *out_value = heap;
      return true;
    };

    facebook::jsi::Value result;
    std::shared_ptr<facebook::jsi::Buffer> source_buffer;
    if (is_bytecode) {
      source_buffer = std::make_shared<AlignedBytecodeBuffer>(data, len);
      auto aligned_data = source_buffer->data();
#if defined(EXACT_HAVE_HERMES_RUNTIME_BYTECODE_SANITY_CHECK)
      const auto* disable_check = std::getenv("EX_DISABLE_BYTECODE_SANITY_CHECK");
      if (!disable_check) {
        std::string reason;
        if (!facebook::hermes::HermesRuntime::hermesBytecodeSanityCheck(
                aligned_data, len, &reason)) {
          if (out_value) {
            char* heap = static_cast<char*>(malloc(reason.size() + 1));
            if (heap) {
              memcpy(heap, reason.data(), reason.size());
              heap[reason.size()] = '\0';
              *out_value = heap;
            }
          }
          return 1;
        }
      }
#else
      (void)aligned_data;
#endif
      result = runtime->runtime->evaluateJavaScript(source_buffer, source);
    } else {
      source_buffer = std::make_shared<MemoryBuffer>(data, len);
      if (traceEval) {
        fprintf(stderr, "[eval] evaluate_start %s len=%zu\n", source.c_str(), len);
      }
      result = runtime->runtime->evaluateJavaScript(source_buffer, source);
    }
    if (traceEval) {
      fprintf(stderr, "[eval] evaluate_end %s\n", source.c_str());
    }
    if (traceEval) {
      fprintf(stderr, "[eval] next_tick_start %s\n", source.c_str());
    }
    runNextTickQueue(runtime);
    if (traceEval) {
      fprintf(stderr, "[eval] next_tick_end %s\n", source.c_str());
      fprintf(stderr, "[eval] microtasks_start %s\n", source.c_str());
    }
    drainMicrotasks(*runtime->runtime);
    if (traceEval) {
      fprintf(stderr, "[eval] microtasks_end %s\n", source.c_str());
    }
#if EXACT_HAS_HERMES_ASYNC_DEBUGGER
    if (runtime->debugger_attached.load()) {
      emitNewScripts(runtime, runtime->runtime->getDebugger());
    }
#endif

    // If the result is a thenable/Promise, resolve it before returning.
    // This makes top-level await work in the REPL and eval contexts.
    // Windows Hermes currently does not support async function syntax in this
    // eval path, and the CLI already drives the event loop after file/eval
    // execution, so skip the JS unwrap shim there.
#if !defined(_WIN32)
    if (result.isObject()) {
      auto& rt = *runtime->runtime;
      // Stash the result as a temp global so JS can inspect it
      rt.global().setProperty(rt, "__ex_p",
          facebook::jsi::Value(rt, result));
      const char* unwrap_code =
          "(function(){"
          "var p=globalThis.__ex_p;"
          "delete globalThis.__ex_p;"
          "if(!p||typeof p.then!=='function')return null;"
          "var r={v:undefined,ok:true,done:false};"
          "p.then(function(v){r.v=v;r.done=true;},"
          "function(e){r.v=e;r.ok=false;r.done=true;});"
          "return r;"
          "})()";
      auto ubuf = std::make_shared<MemoryBuffer>(
          reinterpret_cast<const uint8_t*>(unwrap_code),
          strlen(unwrap_code));
      auto check = rt.evaluateJavaScript(ubuf, "<promise-unwrap>");
      drainMicrotasks(rt);

      if (!check.isNull() && check.isObject()) {
        auto promiseState = check.getObject(rt);
        auto resolvePromiseResult = [&]() -> std::optional<bool> {
          auto doneProp = promiseState.getProperty(rt, "done");
          if (!doneProp.isBool() || !doneProp.getBool()) {
            return std::nullopt;
          }

          auto ok = promiseState.getProperty(rt, "ok");
          if (ok.isBool() && ok.getBool()) {
            result = promiseState.getProperty(rt, "v");
            return true;
          }

          auto errVal = promiseState.getProperty(rt, "v");
          if (!writeOutString(valueToString(rt, errVal))) {
            return false;
          }
          return false;
        };

        while (true) {
          auto settled = resolvePromiseResult();
          if (settled.has_value()) {
            if (!settled.value()) {
              return 1;
            }
            break;
          }

          int executed = ex_hermes_poll(runtime, nowMs());
          if (executed < 0) {
            if (!writeOutString("Hermes task execution failed while awaiting Promise result")) {
              return 1;
            }
            return 1;
          }

          settled = resolvePromiseResult();
          if (settled.has_value()) {
            if (!settled.value()) {
              return 1;
            }
            break;
          }

          auto nextTimer = ex_hermes_next_timer(runtime);
          auto hasPendingWork = ex_hermes_has_pending_tasks(runtime) != 0;
          if (!hasPendingWork && nextTimer < 0) {
            // No timers or host work can advance the Promise any further.
            // Fall back to returning the raw Promise value rather than spin.
            break;
          }

          if (nextTimer >= 0) {
            auto now = nowMs();
            auto delay = nextTimer > static_cast<int64_t>(now)
                ? static_cast<uint64_t>(nextTimer) - now
                : 0;
            if (delay > 0) {
              std::this_thread::sleep_for(
                  std::chrono::milliseconds(std::min<uint64_t>(delay, 5)));
            }
          } else {
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
          }
        }
      }
    }
#endif

    if (out_value) {
      if (result.isUndefined()) {
        *out_value = nullptr;
      } else {
        auto text = valueToString(*runtime->runtime, result);
        auto size = text.size();
        char* heap = static_cast<char*>(malloc(size + 1));
        if (!heap) {
          return 1;
        }
        memcpy(heap, text.data(), size);
        heap[size] = '\0';
        *out_value = heap;
      }
    }

    return 0;
  } catch (const facebook::jsi::JSError& err) {
    // Try to call process uncaughtException handler before reporting error
    auto& rt = *runtime->runtime;
    try {
      auto handler = rt.global().getProperty(rt, "__exactUncaughtExceptionHandler");
      if (handler.isObject() && handler.asObject(rt).isFunction(rt)) {
        // Create a new Error object from the message (can't copy jsi::Value)
        auto errObj = rt.global()
            .getPropertyAsFunction(rt, "Error")
            .callAsConstructor(rt, facebook::jsi::String::createFromUtf8(rt, err.getMessage()));
        auto result = handler.asObject(rt).asFunction(rt).call(rt, std::move(errObj));
        if (result.isBool() && result.getBool()) {
          // Handler returned true — exception was handled, don't crash
          if (out_value) *out_value = nullptr;
          return 0;
        }
      }
    } catch (...) {
      // If the handler itself throws, fall through to normal error reporting
    }

    if (out_value) {
      auto message = err.getMessage();
      auto stack = err.getStack();
      // Include stack trace if available
      std::string full;
      if (!stack.empty()) {
        full = message + "\n" + stack;
      } else {
        full = message;
      }
      auto size = full.size();
      char* heap = static_cast<char*>(malloc(size + 1));
      if (!heap) {
        return 1;
      }
      memcpy(heap, full.data(), size);
      heap[size] = '\0';
      *out_value = heap;
    }
    return 1;
  } catch (const std::exception& err) {
    if (out_value) {
      auto message = std::string(err.what());
      auto size = message.size();
      char* heap = static_cast<char*>(malloc(size + 1));
      if (!heap) {
        return 1;
      }
      memcpy(heap, message.data(), size);
      heap[size] = '\0';
      *out_value = heap;
    }
    return 1;
  } catch (...) {
    std::string source_label = source_url ? source_url : (is_bytecode ? "<bytecode>" : "<eval>");
    if (!writeOutError("Unknown non-std exception while evaluating " + source_label)) {
      return 1;
    }
    return 1;
  }
}

// --- Valet host-call bridge ---

extern "C" void ex_hermes_set_host_call(
    ExactHermesRuntime* runtime,
    char* (*callback)(const char* op, const char* args_json)) {
  if (!runtime) return;
  runtime->host_call_fn = callback;

  // Install (or reinstall) the __hostCall JS function
  auto& rt = *runtime->runtime;
  auto hostCallFn = facebook::jsi::Function::createFromHostFunction(
      rt,
      facebook::jsi::PropNameID::forAscii(rt, "__hostCall"),
      2,
      [runtime](facebook::jsi::Runtime& rt,
                const facebook::jsi::Value&,
                const facebook::jsi::Value* args,
                size_t count) -> facebook::jsi::Value {
        if (!runtime->host_call_fn || count < 2) {
          throw facebook::jsi::JSError(rt, "__hostCall: no callback registered or wrong arity");
        }
        auto op = args[0].asString(rt).utf8(rt);
        auto argsJson = args[1].asString(rt).utf8(rt);

        char* result = runtime->host_call_fn(op.c_str(), argsJson.c_str());
        if (!result) {
          return facebook::jsi::Value::null();
        }

        // Parse the result — first char indicates success/error:
        // '+' prefix = success, result JSON follows
        // '-' prefix = error, error message follows
        std::string resultStr(result);
        free(result);

        if (resultStr.empty()) {
          return facebook::jsi::Value::null();
        }

        if (resultStr[0] == '-') {
          throw facebook::jsi::JSError(rt, resultStr.substr(1));
        }

        // Parse the JSON result (skip '+' prefix)
        std::string json = (resultStr[0] == '+') ? resultStr.substr(1) : resultStr;
        if (json.empty() || json == "null" || json == "undefined") {
          return facebook::jsi::Value::null();
        }

        // Use JSON.parse to convert
        auto jsonGlobal = rt.global().getPropertyAsObject(rt, "JSON");
        auto parseFn = jsonGlobal.getPropertyAsFunction(rt, "parse");
        return parseFn.call(rt, facebook::jsi::String::createFromUtf8(rt, json));
      });
  rt.global().setProperty(rt, "__hostCall", std::move(hostCallFn));
}

extern "C" void ex_hermes_free_string(char* value) {
  if (value) {
    free(value);
  }
}

extern "C" int ex_hermes_poll(ExactHermesRuntime* runtime, uint64_t now_ms) {
  if (!runtime) {
    return 0;
  }

  int executed = 0;
  cleanupFetchCallbacks(runtime);

  // Drain cross-thread callback queue (HTTP server responses, etc.)
  executed += drainCallbackQueue(runtime);

  // Drain pending cross-thread tasks
  {
    std::vector<std::function<void(facebook::jsi::Runtime&)>> tasks;
    {
      std::lock_guard<std::mutex> lock(runtime->task_mutex);
      tasks.swap(runtime->pending_tasks);
    }
    if (!tasks.empty()) {
      auto& rt = *runtime->runtime;
      for (auto& task : tasks) {
        try {
          task(rt);
          executed++;
        } catch (const facebook::jsi::JSError& err) {
          ex_host_console_log(1, err.getMessage().c_str());
        } catch (const std::exception& err) {
          ex_host_console_log(1, err.what());
        }
      }
    }
  }

  runNextTickQueue(runtime);
  drainMicrotasks(*runtime->runtime);

  // Check if there are any referenced tasks keeping the loop alive
  // (excluding unref'd timers). If not, skip unref'd due timers.
  bool has_referenced_work = false;
  if (ex_host_http_has_referenced() || ex_host_http_has_pending_requests()
      || native_ws_has_active() || hasPendingFetchCallbacks(runtime)) {
    has_referenced_work = true;
  } else if (!runtime->next_tick.empty()) {
    has_referenced_work = true;
  } else if (runtime->active_spawn_processes.load(std::memory_order_relaxed) > 0) {
    has_referenced_work = true;
  } else {
    std::lock_guard<std::mutex> lock(runtime->callbackMutex);
    if (!runtime->callbackQueue.empty()) has_referenced_work = true;
  }
  if (!has_referenced_work) {
    // Check if any referenced timer exists
    for (const auto& kv : runtime->timers) {
      if (kv.second.referenced) {
        has_referenced_work = true;
        break;
      }
    }
  }

  std::vector<uint64_t> due;
  for (const auto& kv : runtime->timers) {
    if (kv.second.due_ms <= now_ms) {
      // Skip unref'd timers if nothing else is keeping the loop alive
      if (!kv.second.referenced && !has_referenced_work) {
        continue;
      }
      due.push_back(kv.first);
    }
  }
  // Sort by timer ID to maintain insertion order (IDs are monotonically increasing)
  std::sort(due.begin(), due.end());

  for (auto id : due) {
    auto it = runtime->timers.find(id);
    if (it == runtime->timers.end()) {
      continue;
    }
    // Retire or reschedule the fired timer. Must run before any error return
    // below: otherwise a throwing one-shot timer stays due and refires on
    // every subsequent poll. @tactical @ref LLP 0159 R1
    auto retireTimer = [runtime, now_ms, id]() {
      auto after = runtime->timers.find(id);
      if (after != runtime->timers.end()) {
        if (after->second.repeat) {
          after->second.due_ms = now_ms + after->second.interval_ms;
        } else {
          runtime->timers.erase(after);
        }
      }
    };
    try {
      if (it->second.args.empty()) {
        it->second.callback.call(*runtime->runtime);
      } else {
        it->second.callback.call(
            *runtime->runtime,
            static_cast<const facebook::jsi::Value*>(it->second.args.data()),
            it->second.args.size());
      }
      executed += 1;
      runNextTickQueue(runtime);
      drainMicrotasks(*runtime->runtime);
    } catch (const facebook::jsi::JSError& err) {
      executed += 1;
      // Try uncaughtException handler before terminating
      bool handled = false;
      try {
        auto& rt = *runtime->runtime;
        auto handler = rt.global().getProperty(rt, "__exactUncaughtExceptionHandler");
        if (handler.isObject() && handler.asObject(rt).isFunction(rt)) {
          auto errVal = facebook::jsi::Value(rt, err.value());
          auto result = handler.asObject(rt).asFunction(rt).call(rt, std::move(errVal));
          if (result.isBool() && result.getBool()) handled = true;
        }
      } catch (...) {}
      if (!handled) {
        retireTimer();
        ex_host_console_log(1, err.getMessage().c_str());
        return -1;
      }
      // Continue processing remaining timers after handled exception
      runNextTickQueue(runtime);
      drainMicrotasks(*runtime->runtime);
    } catch (const std::exception& err) {
      retireTimer();
      ex_host_console_log(1, err.what());
      return -1;
    }

    retireTimer();
  }

  return executed;
}

extern "C" int64_t ex_hermes_next_timer(ExactHermesRuntime* runtime) {
  if (!runtime || runtime->timers.empty()) {
    return -1;
  }
  uint64_t next_due = UINT64_MAX;
  for (const auto& kv : runtime->timers) {
    if (kv.second.due_ms < next_due) {
      next_due = kv.second.due_ms;
    }
  }
  if (next_due == UINT64_MAX) {
    return -1;
  }
  return static_cast<int64_t>(next_due);
}

extern "C" int ex_hermes_has_pending_tasks(ExactHermesRuntime* runtime) {
  if (!runtime) {
    return 0;
  }
  if (ex_host_http_has_referenced() || ex_host_http_has_pending_requests()
      || native_ws_has_active() || hasPendingFetchCallbacks(runtime)) {
    return 1;
  }
  if (!runtime->next_tick.empty()) {
    return 1;
  }
  if (runtime->active_spawn_processes.load(std::memory_order_relaxed) > 0) {
    return 1;
  }
  {
    std::lock_guard<std::mutex> lock(runtime->callbackMutex);
    if (!runtime->callbackQueue.empty()) return 1;
  }
  // Only count referenced timers as keeping the loop alive
  for (const auto& kv : runtime->timers) {
    if (kv.second.referenced) {
      return 1;
    }
  }
  return 0;
}

extern "C" uint32_t ex_hermes_callback_backlog(ExactHermesRuntime* runtime) {
  if (!runtime) {
    return 0;
  }

  std::lock_guard<std::mutex> lock(runtime->callbackMutex);
  return static_cast<uint32_t>(runtime->callbackQueue.size());
}

extern "C" void ex_hermes_schedule_watchdog_heartbeat(
    ExactHermesRuntime* runtime,
    void (*callback)(void* context),
    void* context) {
  if (!runtime || !callback) {
    return;
  }

  pushRuntimeCallback(runtime, [callback, context](facebook::jsi::Runtime&) {
    callback(context);
  });
}

// Debugger API functions extracted to hermes_runtime_debugger.cc

// iOS rendering pipeline callbacks extracted to hermes_runtime_ios.cc

// GC
// =============================================================================

extern "C" void ex_hermes_gc(ExactHermesRuntime* runtime) {
  if (!runtime || !runtime->runtime) return;
  runtime->runtime->instrumentation().collectGarbage("ex_hermes_gc");
}

extern "C" char* ex_hermes_get_heap_info(
    ExactHermesRuntime* runtime,
    int include_expensive) {
  if (!runtime || !runtime->runtime) {
    return nullptr;
  }

  auto heapInfo = captureHeapInfo(runtime, include_expensive != 0);
  return copyMallocString(stringifyHeapInfo(heapInfo));
}

extern "C" char* ex_hermes_get_gc_stats(ExactHermesRuntime* runtime) {
  if (!runtime || !runtime->runtime) {
    return nullptr;
  }

  try {
    auto stats = runtime->runtime->instrumentation().getRecordedGCStats();
    return copyMallocString(stats);
  } catch (...) {
    return nullptr;
  }
}

// =============================================================================
// HTTP server stubs (deliberate no-host builds only)
// =============================================================================

// No-op stubs for the HTTP server functions. The real implementation is the
// Rust host/http_server.rs in this crate, compiled when the `host-http-server`
// cargo feature is enabled (build.rs then omits these stubs). They exist so
// builds that deliberately exclude the server still link. Non-MSVC builds mark
// them weak so an external strong implementation can override them; MSVC gets
// strong stubs only in the feature-off build. @ref LLP 0005#c-compilation
#if defined(EXACT_RUNTIME_USE_HTTP_STUBS)
#if defined(_MSC_VER)
#define WEAK_STUB
#else
#define WEAK_STUB __attribute__((weak))
#endif

extern "C" WEAK_STUB char* ex_host_http_serve(uint16_t, const char*) { return nullptr; }
extern "C" WEAK_STUB char* ex_host_http_wait(uint32_t, uint32_t) { return nullptr; }
extern "C" WEAK_STUB char* ex_host_http_read_body(uint32_t, uint32_t) { return nullptr; }
extern "C" WEAK_STUB int32_t ex_host_http_respond(uint32_t, uint32_t, uint16_t, const char*, const uint8_t*, uint32_t) { return -1; }
extern "C" WEAK_STUB int32_t ex_host_http_respond_text(uint32_t, uint32_t, uint16_t, const uint8_t*, uint32_t) { return -1; }
extern "C" WEAK_STUB int32_t ex_host_http_respond_json(uint32_t, uint32_t, uint16_t, const uint8_t*, uint32_t) { return -1; }
extern "C" WEAK_STUB int32_t ex_host_http_respond_stream(uint32_t, uint32_t, uint16_t, const char*) { return -1; }
extern "C" WEAK_STUB int32_t ex_host_http_respond_chunk(uint32_t, uint32_t, const uint8_t*, uint32_t) { return -1; }
extern "C" WEAK_STUB int32_t ex_host_http_respond_end(uint32_t, uint32_t) { return -1; }
extern "C" WEAK_STUB int32_t ex_host_http_respond_string(uint32_t, uint32_t, uint16_t, const char*, const uint8_t*, uint32_t) { return -1; }
extern "C" WEAK_STUB char* ex_host_http_address(uint32_t) { return nullptr; }
extern "C" WEAK_STUB char* ex_host_http_poll(uint32_t) { return nullptr; }
extern "C" WEAK_STUB char* ex_host_http_drain(uint32_t, uint32_t) { return nullptr; }
extern "C" WEAK_STUB int32_t ex_host_http_close(uint32_t, int32_t) { return -1; }
extern "C" WEAK_STUB int32_t ex_host_http_is_referenced(uint32_t) { return 0; }
extern "C" WEAK_STUB int32_t ex_host_http_has_referenced(void) { return 0; }
extern "C" WEAK_STUB int32_t ex_host_http_has_pending_requests(void) { return 0; }
extern "C" WEAK_STUB void ex_host_http_set_ref(uint32_t, int32_t) {}

#undef WEAK_STUB
#endif
