//! Source map V3 parser and stack trace rewriter.
//!
//! Parses source maps generated by esbuild/rolldown and rewrites Hermes
//! stack traces to show original TypeScript/JSX file positions.

use serde::Deserialize;
use std::path::Path;

/// A single decoded mapping entry.
#[derive(Debug, Clone)]
struct Mapping {
    gen_line: u32,
    gen_col: u32,
    source_idx: u32,
    orig_line: u32,
    orig_col: u32,
}

/// Parsed source map with lookup capability.
pub struct SourceMap {
    sources: Vec<String>,
    mappings: Vec<Mapping>,
}

#[derive(Deserialize)]
struct RawSourceMap {
    sources: Vec<String>,
    mappings: String,
}

impl SourceMap {
    /// Load and parse a V3 source map from a file path.
    pub fn load(path: &Path) -> Option<Self> {
        let data = std::fs::read_to_string(path).ok()?;
        Self::parse(&data)
    }

    /// Parse a V3 source map JSON string.
    fn parse(json: &str) -> Option<Self> {
        let raw: RawSourceMap = serde_json::from_str(json).ok()?;
        let mappings = decode_vlq_mappings(&raw.mappings);
        Some(SourceMap {
            sources: raw.sources,
            mappings,
        })
    }

    /// Look up the original position for a generated line and column.
    /// Returns (source_file, original_line, original_col).
    pub fn lookup(&self, gen_line: u32, gen_col: u32) -> Option<(&str, u32, u32)> {
        // Find the best matching mapping for this generated position.
        // Mappings are sorted by gen_line, then gen_col.
        let mut best: Option<&Mapping> = None;
        for m in &self.mappings {
            if m.gen_line == gen_line && m.gen_col <= gen_col {
                match best {
                    None => best = Some(m),
                    Some(prev) if m.gen_col > prev.gen_col => best = Some(m),
                    _ => {}
                }
            } else if m.gen_line == gen_line && best.is_none() {
                // Take first mapping on the line even if col is past
                best = Some(m);
            }
        }
        let m = best?;
        let source = self.sources.get(m.source_idx as usize)?;
        Some((source, m.orig_line + 1, m.orig_col + 1)) // 1-based
    }
}

/// Decode VLQ-encoded source map mappings string.
fn decode_vlq_mappings(mappings: &str) -> Vec<Mapping> {
    let mut result = Vec::new();
    let mut gen_line: u32 = 0;
    let mut source_idx: i64 = 0;
    let mut orig_line: i64 = 0;
    let mut orig_col: i64 = 0;

    for group in mappings.split(';') {
        let mut gen_col: i64 = 0;
        for segment in group.split(',') {
            if segment.is_empty() {
                continue;
            }
            let values = decode_vlq_segment(segment);
            if values.is_empty() {
                continue;
            }
            gen_col += values[0];
            if values.len() >= 4 {
                source_idx += values[1];
                orig_line += values[2];
                orig_col += values[3];
                result.push(Mapping {
                    gen_line,
                    gen_col: gen_col as u32,
                    source_idx: source_idx as u32,
                    orig_line: orig_line as u32,
                    orig_col: orig_col as u32,
                });
            }
        }
        gen_line += 1;
    }
    result
}

/// Decode a single VLQ segment into a list of values.
fn decode_vlq_segment(segment: &str) -> Vec<i64> {
    let mut values = Vec::new();
    let mut shift = 0u32;
    let mut value: i64 = 0;

    for ch in segment.bytes() {
        let digit = vlq_char_to_int(ch);
        if digit < 0 {
            break;
        }
        let digit = digit as i64;
        value += (digit & 0x1f) << shift;
        shift += 5;
        if (digit & 0x20) == 0 {
            // sign bit is the LSB
            if (value & 1) != 0 {
                values.push(-(value >> 1));
            } else {
                values.push(value >> 1);
            }
            value = 0;
            shift = 0;
        }
    }
    values
}

fn vlq_char_to_int(ch: u8) -> i32 {
    match ch {
        b'A'..=b'Z' => (ch - b'A') as i32,
        b'a'..=b'z' => (ch - b'a' + 26) as i32,
        b'0'..=b'9' => (ch - b'0' + 52) as i32,
        b'+' => 62,
        b'/' => 63,
        _ => -1,
    }
}

/// Rewrite a Hermes error/stack trace using a source map.
///
/// Looks for patterns like `at funcName (filename:line:col)` or `at anonymous (:line:col)`
/// and rewrites them using the source map.
pub fn rewrite_error(message: &str, source_map: &SourceMap, bundle_path: &str) -> String {
    use std::fmt::Write;

    let lines: Vec<&str> = message.lines().collect();
    let mut output = String::new();

    // The error message often has:
    //   line 0: "message text"
    //   line 1: "TypeError: message text"  (redundant)
    //   lines 2+: "    at func (file:line:col)"
    // Skip the redundant "TypeName: message" line if it matches the first line.
    let first_line = lines.first().copied().unwrap_or("");

    for line in &lines {
        // Skip redundant "ErrorType: message" line
        if let Some(after_colon) = line.split_once(": ") {
            if after_colon.1 == first_line
                && (after_colon.0.ends_with("Error") || after_colon.0.ends_with("Exception"))
            {
                continue;
            }
        }

        // Skip internal stack frames
        let trimmed = line.trim();
        if trimmed.contains("<module-loader>")
            || trimmed.contains("<eval>")
            || trimmed.contains("<bootstrap>")
        {
            continue;
        }

        if let Some(rewritten) = rewrite_stack_line(line, source_map, bundle_path) {
            let _ = writeln!(output, "{}", rewritten);
        } else {
            // Skip unrewritten bundle frames that couldn't be mapped
            if trimmed.starts_with("at ") && trimmed.contains(".bundle.") {
                continue;
            }
            let _ = writeln!(output, "{}", line);
        }
    }
    // Remove trailing newline
    if output.ends_with('\n') {
        output.pop();
    }
    output
}

/// Try to rewrite a single stack trace line.
fn rewrite_stack_line(line: &str, source_map: &SourceMap, bundle_path: &str) -> Option<String> {
    // Match patterns like:
    //   at funcName (filename:line:col)
    //   at funcName (:line:col)
    //   at anonymous (:line:col)
    let trimmed = line.trim();
    if !trimmed.starts_with("at ") {
        return None;
    }

    // Find the (filename:line:col) part
    let paren_start = trimmed.find('(')?;
    let paren_end = trimmed.rfind(')')?;
    if paren_end <= paren_start {
        return None;
    }

    let location = &trimmed[paren_start + 1..paren_end];
    let func_part = &trimmed[3..paren_start].trim();

    // Parse filename:line:col
    // Could be ":7:8" (no filename) or "file.js:7:8"
    let parts: Vec<&str> = location.rsplitn(3, ':').collect();
    if parts.len() < 2 {
        return None;
    }

    let col: u32 = parts[0].parse().ok()?;
    let gen_line: u32 = parts[1].parse().ok()?;
    let filename = if parts.len() > 2 { parts[2] } else { "" };

    // Only rewrite if the filename matches the bundle path or is empty
    let bundle_basename = Path::new(bundle_path)
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("");
    if !filename.is_empty()
        && filename != bundle_path
        && filename != bundle_basename
        && !filename.contains(".bundle.")
        && filename != "<module-loader>"
        && filename != "<eval>"
    {
        return None;
    }

    // Skip internal frames
    if filename == "<module-loader>" || filename == "<eval>" {
        return None;
    }

    // gen_line is 1-based from the stack, source map uses 0-based
    let (source, orig_line, orig_col) =
        source_map.lookup(gen_line.saturating_sub(1), col.saturating_sub(1))?;

    // Clean up the source path — resolve relative paths to absolute
    let mut display_source = source.to_string();
    // Strip repeated ../ prefixes and resolve against bundle directory
    if display_source.starts_with("../") || display_source.starts_with("./") {
        let bundle_dir = Path::new(bundle_path).parent().unwrap_or(Path::new(""));
        let resolved = bundle_dir.join(&display_source);
        if let Ok(canonical) = resolved.canonicalize() {
            display_source = canonical.to_string_lossy().to_string();
        }
    }

    Some(format!(
        "    at {} ({}:{}:{})",
        func_part, &display_source, orig_line, orig_col
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_vlq_decode() {
        // 'A' = 0, 'C' = 1, 'E' = 2
        assert_eq!(decode_vlq_segment("A"), vec![0]);
        assert_eq!(decode_vlq_segment("C"), vec![1]);
        assert_eq!(decode_vlq_segment("E"), vec![2]);
        assert_eq!(decode_vlq_segment("D"), vec![-1]);
    }

    #[test]
    fn test_vlq_decode_multi() {
        let values = decode_vlq_segment("AACA");
        assert_eq!(values, vec![0, 0, 1, 0]);
    }

    #[test]
    fn test_parse_source_map_reads_mappings_field() {
        let json = r#"{"version":3,"mappings":"AAAA","sources":["foo.ts"]}"#;
        let sm = SourceMap::parse(json).unwrap();
        let (source, line, col) = sm.lookup(0, 0).unwrap();
        assert_eq!(source, "foo.ts");
        assert_eq!(line, 1);
        assert_eq!(col, 1);
    }

    #[test]
    fn test_parse_source_map_json_with_embedded_key_names() {
        let json = r#"{
            "version":3,
            "sources":["foo.ts","bar.ts"],
            "names":["mappings","sources"],
            "mappings":"AAAA"
        }"#;

        let sm = SourceMap::parse(json).unwrap();
        let (source, line, col) = sm.lookup(0, 0).unwrap();

        assert_eq!(source, "foo.ts");
        assert_eq!(line, 1);
        assert_eq!(col, 1);
    }

    #[test]
    fn test_simple_source_map() {
        // A simple source map: one source file, identity mapping for line 0
        let json = r#"{"version":3,"sources":["input.ts"],"mappings":"AAAA"}"#;
        let sm = SourceMap::parse(json).unwrap();
        let (source, line, col) = sm.lookup(0, 0).unwrap();
        assert_eq!(source, "input.ts");
        assert_eq!(line, 1);
        assert_eq!(col, 1);
    }
}
