// @ref LLP 0005#capability-registry-bindings — generated writes are confined,
// atomic, and transactional across the closed output family.

import { afterEach, describe, expect, test } from "bun:test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  assertConfinedGeneratedFile,
  writeGeneratedFilesTransactionally,
} from "./generated-output-io.mjs";

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../../..",
);
const temporaryRoots = [];

function temporaryRoot(prefix) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
  temporaryRoots.push(root);
  return root;
}

afterEach(() => {
  for (const root of temporaryRoots.splice(0)) {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

describe("confined generated output writes", () => {
  test("writes a regular output atomically", () => {
    const root = temporaryRoot("ibex-generated-output-");
    const output = path.join(root, "generated", "output.txt");
    fs.mkdirSync(path.dirname(output));
    fs.writeFileSync(output, "before\n");

    writeGeneratedFilesTransactionally(root, [
      { path: output, content: "generated bytes\n", label: "regular output" },
    ]);

    expect(fs.readFileSync(output, "utf8")).toBe("generated bytes\n");
    expect(assertConfinedGeneratedFile(root, output).stat.nlink).toBe(1);
  });

  test("rolls every original byte back when validation fails", () => {
    const root = temporaryRoot("ibex-generated-rollback-");
    const first = path.join(root, "first.txt");
    const second = path.join(root, "nested", "second.txt");
    fs.writeFileSync(first, "before\n");

    expect(() =>
      writeGeneratedFilesTransactionally(
        root,
        [
          { path: first, content: "after\n" },
          { path: second, content: "new\n" },
        ],
        () => {
          throw new Error("semantic validation failed");
        },
      ),
    ).toThrow(/semantic validation failed/);
    expect(fs.readFileSync(first, "utf8")).toBe("before\n");
    expect(fs.existsSync(second)).toBe(false);
    expect(fs.existsSync(path.dirname(second))).toBe(false);
  });

  test("preflight rejection does not create output parents", () => {
    const root = temporaryRoot("ibex-generated-preflight-");
    const output = path.join(root, "new", "nested", "output.txt");

    expect(() =>
      writeGeneratedFilesTransactionally(root, [
        { path: output, content: "first\n" },
        { path: output, content: "duplicate\n" },
      ]),
    ).toThrow(/duplicate generated output path/);
    expect(fs.existsSync(path.join(root, "new"))).toBe(false);
  });

  test("rejects asynchronous validation and rolls written bytes back", () => {
    const root = temporaryRoot("ibex-generated-async-validation-");
    const output = path.join(root, "output.txt");
    fs.writeFileSync(output, "before\n");

    expect(() =>
      writeGeneratedFilesTransactionally(
        root,
        [{ path: output, content: "after\n" }],
        async () => undefined,
      ),
    ).toThrow(/validation must be synchronous/);
    expect(fs.readFileSync(output, "utf8")).toBe("before\n");
  });

  test("rejects destination and parent symbolic-link aliases", () => {
    if (process.platform === "win32") return;
    const root = temporaryRoot("ibex-generated-symlink-");
    const outside = temporaryRoot("ibex-generated-outside-");
    const insideSource = path.join(root, "source.txt");
    const outsideSource = path.join(outside, "outside.txt");
    fs.writeFileSync(insideSource, "inside\n");
    fs.writeFileSync(outsideSource, "outside\n");

    const outsideDestination = path.join(root, "outside-destination.txt");
    fs.symlinkSync(outsideSource, outsideDestination);
    expect(() =>
      writeGeneratedFilesTransactionally(root, [
        { path: outsideDestination, content: "overwrite\n" },
      ]),
    ).toThrow(/symbolic link/);
    expect(fs.readFileSync(outsideSource, "utf8")).toBe("outside\n");

    const insideAlias = path.join(root, "inside-alias.txt");
    fs.symlinkSync(insideSource, insideAlias);
    expect(() =>
      writeGeneratedFilesTransactionally(root, [
        { path: insideAlias, content: "overwrite\n" },
      ]),
    ).toThrow(/symbolic link/);
    expect(fs.readFileSync(insideSource, "utf8")).toBe("inside\n");

    const linkedParent = path.join(root, "linked-parent");
    fs.symlinkSync(outside, linkedParent, "dir");
    expect(() =>
      writeGeneratedFilesTransactionally(root, [
        { path: path.join(linkedParent, "escaped.txt"), content: "escape\n" },
      ]),
    ).toThrow(/parent path contains a symbolic link/);
    expect(fs.existsSync(path.join(outside, "escaped.txt"))).toBe(false);
  });

  test("writing and read-only validation reject hard-linked outputs", () => {
    const root = temporaryRoot("ibex-generated-hardlink-check-");
    const source = path.join(root, "source.txt");
    const output = path.join(root, "output.txt");
    fs.writeFileSync(source, "same inode\n");
    fs.linkSync(source, output);
    expect(() =>
      writeGeneratedFilesTransactionally(root, [
        { path: output, content: "overwrite\n" },
      ]),
    ).toThrow(/hard-linked/);
    expect(fs.readFileSync(source, "utf8")).toBe("same inode\n");
    expect(() => assertConfinedGeneratedFile(root, output)).toThrow(
      /hard-linked/,
    );
  });

  test("read-only validation never creates a missing parent", () => {
    const root = temporaryRoot("ibex-generated-readonly-");
    const output = path.join(root, "missing", "output.txt");
    expect(() => assertConfinedGeneratedFile(root, output)).toThrow(
      /parent directory is missing/,
    );
    expect(fs.existsSync(path.dirname(output))).toBe(false);
  });
});

describe("canonical generated checkout bytes", () => {
  test("pins byte-sensitive authorities and outputs to LF", () => {
    const attributes = fs.readFileSync(
      path.join(repoRoot, ".gitattributes"),
      "utf8",
    );
    for (const rule of [
      "packages/ibex-devtools/src/scripts/** text eol=lf",
      "vendored-generated/** text eol=lf",
      "session/** text eol=lf",
      "llp/fixtures/** text eol=lf",
      "runtime-surface.json text eol=lf",
    ]) {
      expect(attributes).toContain(rule);
    }

    for (const sourcePath of [
      "packages/ibex-devtools/src/scripts/generate-runtime-environment-inventory.mjs",
      "vendored-generated/repl_surface.generated.rs",
      "session/session-constants.v1.json",
      "llp/fixtures/0023-vfs-error-union.v1.json",
      "runtime-surface.json",
    ]) {
      expect(
        fs.readFileSync(path.join(repoRoot, sourcePath), "utf8").includes("\r"),
        sourcePath,
      ).toBe(false);
    }
  });
});
