// @generated by bun run generate:module-transform-config; do not edit.
// @ref LLP 0028#1-toolchain-and-pin-rotation--atomic-with-identity-rotation — generated constants bind runtime identity to the reviewed pin set
#![allow(dead_code)]
pub const TRANSFORM_CONFIGURATION_SCHEMA: &str = "ibex/module-transform-configuration/1";
pub const TRANSFORM_CONFIGURATION_DIGEST: &str =
    "sha256-TsgKoBzPAzyrKCqTwoDAcYVMCdgauOPwoxi0SEoqlv8";
pub const TRANSFORM_CACHE_TAG: &str =
    "module-transform-sha256-TsgKoBzPAzyrKCqTwoDAcYVMCdgauOPwoxi0SEoqlv8";
pub const SPIKE_TRANSFORM_FINGERPRINT: &str =
    "ibex-module-runner-spike/3+config/sha256-TsgKoBzPAzyrKCqTwoDAcYVMCdgauOPwoxi0SEoqlv8";
pub const PRODUCER_ID: &str = "ibex-oxc-module-producer";
pub const OXC_LOCKED_SET_DIGEST: &str = "sha256-qrZM4pCRBslTSVxzQelE1NtQhFGlISKmMUbvtkyqc-E";
pub const PARSER_VERSION_IDENTITY: &str =
    "oxc-locked-set/sha256-qrZM4pCRBslTSVxzQelE1NtQhFGlISKmMUbvtkyqc-E";
pub const ECMASCRIPT_TARGET: &str = "es2022";
pub const HERMES_TARGET: &str = "hermes-syntax-abi-es2022-factory-v1";
pub const HANDWRITTEN_PASS_VERSION: &str = "ibex-module-artifact-producer-3";
pub const TRANSFORM_VERSION_IDENTITY: &str =
    "ibex-module-artifact-producer-3+config/sha256-TsgKoBzPAzyrKCqTwoDAcYVMCdgauOPwoxi0SEoqlv8";
pub const MODULE_RUNNER_ABI: &str = "ibex-module-runner-3-guarded-computed-require";
pub const HERMES_COMPAT_VERSION: &str = "llp0019-hermes-compat-3-target-matrix";
pub const COMMONJS_DETECTOR: &str = "cjs-module-lexer";
pub const COMMONJS_DETECTOR_VERSION: &str = "2.1.0";
pub const OXC_MODULE_MODE: &str = "preserve";
pub const OXC_TYPESCRIPT_MODE: &str = "strip";
pub const OXC_JSX_RUNTIME: &str = "classic";
pub const CODEGEN_SOURCE_MAP: &str = "v3-source-id";
pub const MODULE_OPTIONS_DIGEST: &str = "sha256-S5sSvA22BQ20rR1KUr_vq-nWUYjDOWrwgNLC2gVwVdc";
pub const COMMONJS_OPTIONS_DIGEST: &str = "sha256-vdbxVYFSEpd_IvOucvDpq2M1x459PIHh8XLzIkGPMiU";
pub const JSON_OPTIONS_DIGEST: &str = "sha256-b0M48PkrxN9YldBElNpDL0Dt1fFTTI91guNRHi2cI30";
pub const MODULE_OUTPUT_OPTIONS_DIGEST: &str = "sha256-ZBShHalFf7cKJikJu2-lobyESkdCifuEzZ8jySrnLwo";
pub const COMMONJS_OUTPUT_OPTIONS_DIGEST: &str =
    "sha256-s0HGrti5Zxl3ZrXPc2Yuq-PCNl6Hne7ExnmLeA-BsH0";
pub const JSON_OUTPUT_OPTIONS_DIGEST: &str = "sha256-cVaQRd9nmBBTkha0pOphQPMtIsKlnjiHo-wF-JLjzzA";
pub const OXC_JSX_ENABLED: bool = true;
pub const OXC_DECORATORS: bool = false;
pub const CODEGEN_MINIFY: bool = false;
