// Generated by generate-webgpu-production-plan.mjs; do not edit.
// This artifact is reviewed for explicit private injection only. The
// matching native payload codec and several authenticated semantic inputs are
// absent, so it neither enables navigator.gpu nor makes a support claim.
import { createExecutableWebGpuCodecs } from './production-codec-runtime';

export const WEBGPU_OBJECT_KIND_TAGS = {
  "None": 0,
  "GPU": 1,
  "GPUAdapter": 2,
  "GPUDevice": 3,
  "GPUQueue": 4,
  "GPUBuffer": 5,
  "GPUTexture": 6,
  "GPUTextureView": 7,
  "GPUSampler": 8,
  "GPUBindGroupLayout": 9,
  "GPUBindGroup": 10,
  "GPUPipelineLayout": 11,
  "GPUShaderModule": 12,
  "GPUComputePipeline": 13,
  "GPURenderPipeline": 14,
  "GPUCommandEncoder": 15,
  "GPUComputePassEncoder": 16,
  "GPURenderPassEncoder": 17,
  "GPURenderBundleEncoder": 18,
  "GPURenderBundle": 19,
  "GPUCommandBuffer": 20,
  "GPUQuerySet": 21,
  "GPUCanvasContext": 22
} as const;

export const WEBGPU_EXECUTABLE_CODEC_MANIFEST = {
  "schema": "ibex/webgpu-executable-codec-manifest/2",
  "disposition": "reviewed-generated-injection-and-request-adapter-request-device-device-destroy-payload-codegen-input-native-codec-not-installed-no-support-claim",
  "profileId": "exact-webgpu-v1-draft",
  "scopeId": "native-triangle-phase-1a-v1",
  "operationCount": 25,
  "operationIds": [
    "GPU.getPreferredCanvasFormat",
    "GPU.requestAdapter",
    "GPUAdapter.requestDevice",
    "GPUCanvasContext.configure",
    "GPUCanvasContext.getConfiguration",
    "GPUCanvasContext.getCurrentTexture",
    "GPUCanvasContext.unconfigure",
    "GPUCommandEncoder.beginRenderPass",
    "GPUCommandEncoder.finish",
    "GPUDevice.createCommandEncoder",
    "GPUDevice.createRenderPipeline",
    "GPUDevice.createShaderModule",
    "GPUDevice.destroy",
    "GPUDevice.features",
    "GPUDevice.limits",
    "GPUDevice.lost",
    "GPUDevice.popErrorScope",
    "GPUDevice.pushErrorScope",
    "GPUDevice.queue",
    "GPUQueue.submit",
    "GPURenderPassEncoder.draw",
    "GPURenderPassEncoder.end",
    "GPURenderPassEncoder.setPipeline",
    "GPUTexture.createView",
    "GPUTexture.destroy"
  ],
  "maxPayloadBytes": 16777216,
  "byteOrder": "little-endian",
  "scalarRules": {
    "boolean": "u8-zero-or-one",
    "u32": "u32-le",
    "u64": "u64-le",
    "f64": "ieee754-f64-le-finite-policy-from-webidl",
    "string": "u32-byte-length-plus-well-formed-utf8",
    "optional": "u8-presence-plus-value",
    "sequence": "u32-count-plus-canonical-elements",
    "dictionary": "u8-value-tag-plus-u32-count-plus-unique-well-formed-utf8-key-and-canonical-value-pairs-sorted-by-unsigned-utf8-bytes-shorter-prefix-first"
  },
  "digests": {
    "operationSet": "8e19265cf3acf2ee228857bfceb1f7add75cd737580375ba4f21aaa4766db201",
    "semanticProgramSet": "6ccd84073c6cdf6c567d44e908119f165fcb531a1496a16bbb0499240c194b1c",
    "runtimeRouting": "41f616d7434c5a36dd6ff7ddfb1f67e34111ead239e8d941a6104e3deb82d0b9",
    "webgpuCVocabulary": "538132c7d41b91ac25fe2c70c529d39dfdded14cfd9ca21c1585563b0af288c9",
    "projection": "d66916233affe96a17bce13394ea91841333ef06807b989f856f424b84c0f26e"
  },
  "layout": {
    "requestMagic": "IBGQ",
    "resultMagic": "IBGR",
    "lossMagic": "IBGL",
    "version": 1,
    "header": "ascii4-magic-plus-u16-le-version-plus-u16-le-codec-tag-plus-u32-le-operation-wire-id",
    "reference": "u8-object-kind-plus-five-u64-le-identity-fields",
    "target": "u8-zero-or-one-presence-plus-optional-reference",
    "requestTail": "four-u64-le-ordinals-plus-generic-sealed-local-timeline-plus-generic-converted-arguments",
    "nullableNullResult": "authenticated-result-kind-null-plus-zero-payload-bytes",
    "catalogWireTagRule": "one-based-index-in-authority-catalog-order",
    "objectKindTagRule": "ExactGpuObjectKindV2-numeric-values-from-include-exact_runtime.h",
    "valueTags": {
      "null": 0,
      "false": 1,
      "true": 2,
      "u32": 3,
      "f64": 4,
      "string": 5,
      "sequence": 6,
      "dictionary": 7
    },
    "diagnosticMaxBytes": 4096,
    "sequenceMaxCount": 1024,
    "dictionaryMaxFields": 128,
    "nestingMaxDepth": 16
  },
  "nativeCodecPrograms": {
    "schema": "ibex/webgpu-native-codec-programs/2",
    "disposition": "request-adapter-request-device-device-destroy-payload-codegen-input-only-native-codec-not-installed-no-support-claim",
    "dispatch": {
      "carrierPath": "ExactGpuSemanticCallV2.operation_id",
      "payloadOperationWireIdRole": "constant-and-equality-check-only-never-dispatch",
      "payloadCodecTagRole": "route-selected-constant-and-equality-check-only-never-dispatch"
    },
    "scope": {
      "request": "service-request-payload-decoder-plus-operation-specific-call-joins",
      "completion": "service-completion-payload-codec-plus-operation-specific-event-joins",
      "excluded": "full-call-or-event-construction-and-global-v2-carrier-validation"
    },
    "carrierValidationDependency": {
      "authority": "ExactGpuSemanticCallV2-and-ExactGpuServiceEventV2",
      "requestStructuralValidationMustPrecede": "native-request-payload-decode",
      "requestStatefulValidationMustPrecede": "semantic-execution-and-provider-admission",
      "completionEncoderRequires": "authenticated-retained-call-plus-service-owned-operation-result",
      "completionValidationMustPrecede": "completion-payload-decode-and-wrapper-exposure",
      "globallyOwnedCarrierInvariants": [
        "exact-struct-size-abi-version-flags-reserved-and-payload-bounds",
        "valid-realm-account-topology-and-authority-context",
        "retained-operation-instance-promise-scope-ordinals-receiver-target-correlation",
        "valid-provider-admission-physical-sequence-and-device-transition-provenance",
        "result-kind-record-size-status-and-payload-shape"
      ],
      "programOwns": "selected-payload-layout-plus-operation-specific-carrier-joins-and-constraints-only"
    },
    "constants": {
      "providerTopologyId": 1
    },
    "primitiveEncodings": {
      "ascii4": {
        "widthBytes": 4,
        "encoding": "ascii"
      },
      "u8": {
        "widthBytes": 1,
        "encoding": "unsigned-integer"
      },
      "u16le": {
        "widthBytes": 2,
        "encoding": "unsigned-integer",
        "byteOrder": "little-endian"
      },
      "u32le": {
        "widthBytes": 4,
        "encoding": "unsigned-integer",
        "byteOrder": "little-endian"
      },
      "u64le": {
        "widthBytes": 8,
        "encoding": "unsigned-integer",
        "byteOrder": "little-endian"
      },
      "f64le": {
        "widthBytes": 8,
        "encoding": "ieee754-binary64",
        "byteOrder": "little-endian",
        "constraints": [
          "finite"
        ]
      },
      "utf8": {
        "kind": "length-prefixed-bytes",
        "lengthType": "u32le",
        "encoding": "utf8",
        "constraints": [
          "well-formed"
        ]
      }
    },
    "types": {
      "headerV1": {
        "kind": "struct",
        "fields": [
          {
            "name": "magic",
            "type": "ascii4"
          },
          {
            "name": "version",
            "type": "u16le"
          },
          {
            "name": "codecTag",
            "type": "u16le"
          },
          {
            "name": "operationWireId",
            "type": "u32le"
          }
        ]
      },
      "objectReferenceV1": {
        "kind": "struct",
        "fields": [
          {
            "name": "kind",
            "type": "u8",
            "catalog": "objectKindTags"
          },
          {
            "name": "objectId",
            "type": "u64le"
          },
          {
            "name": "objectGeneration",
            "type": "u64le"
          },
          {
            "name": "logicalDeviceId",
            "type": "u64le"
          },
          {
            "name": "logicalDeviceGeneration",
            "type": "u64le"
          },
          {
            "name": "providerGeneration",
            "type": "u64le"
          }
        ]
      },
      "optionalReferenceV1": {
        "kind": "optional",
        "discriminantType": "u8",
        "absentTag": 0,
        "presentTag": 1,
        "valueType": "objectReferenceV1"
      },
      "canonicalValueV1": {
        "kind": "recursive-tagged-union",
        "tagType": "u8",
        "maxDepthFrom": "codecLayout.nestingMaxDepth",
        "rootDepth": 0,
        "depthLimitOperator": "less-than-or-equal",
        "variants": [
          {
            "name": "null",
            "tag": 0,
            "payload": {
              "kind": "empty"
            }
          },
          {
            "name": "false",
            "tag": 1,
            "payload": {
              "kind": "empty"
            }
          },
          {
            "name": "true",
            "tag": 2,
            "payload": {
              "kind": "empty"
            }
          },
          {
            "name": "u32",
            "tag": 3,
            "payload": {
              "kind": "scalar",
              "type": "u32le"
            }
          },
          {
            "name": "f64",
            "tag": 4,
            "payload": {
              "kind": "scalar",
              "type": "f64le"
            }
          },
          {
            "name": "string",
            "tag": 5,
            "payload": {
              "kind": "scalar",
              "type": "utf8"
            }
          },
          {
            "name": "sequence",
            "tag": 6,
            "payload": {
              "kind": "sequence",
              "countType": "u32le",
              "elementType": "canonicalValueV1",
              "maxCountFrom": "codecLayout.sequenceMaxCount",
              "countLimitOperator": "less-than-or-equal"
            }
          },
          {
            "name": "dictionary",
            "tag": 7,
            "payload": {
              "kind": "dictionary",
              "countType": "u32le",
              "keyType": "utf8",
              "valueType": "canonicalValueV1",
              "maxCountFrom": "codecLayout.dictionaryMaxFields",
              "countLimitOperator": "less-than-or-equal",
              "keyConstraints": [
                "unique",
                "strictly-increasing-unsigned-utf8-bytes-shorter-prefix-first"
              ]
            }
          }
        ]
      },
      "requestAdapterOptionsV1": {
        "kind": "closed-dictionary",
        "encodingType": "canonicalValueV1",
        "unknownFields": "reject",
        "fields": [
          {
            "name": "featureLevel",
            "required": true,
            "value": {
              "kind": "string-enum",
              "values": [
                "core",
                "compatibility"
              ]
            }
          },
          {
            "name": "forceFallbackAdapter",
            "required": true,
            "value": {
              "kind": "boolean"
            }
          },
          {
            "name": "powerPreference",
            "required": false,
            "value": {
              "kind": "string-enum",
              "values": [
                "low-power",
                "high-performance"
              ]
            }
          },
          {
            "name": "xrCompatible",
            "required": true,
            "value": {
              "kind": "boolean"
            }
          }
        ],
        "preEncodingBranches": [
          {
            "condition": "featureLevel-not-core-or-compatibility",
            "disposition": "wrapper-local-null-no-service-call"
          }
        ]
      },
      "requestDeviceDescriptorV1": {
        "kind": "closed-dictionary",
        "encodingType": "canonicalValueV1",
        "trust": "untrusted-webidl-converted-semantic-service-ingress-only",
        "providerBoundary": "forbidden-raw-descriptor-must-not-reach-provider",
        "unknownFields": "reject",
        "fields": [
          {
            "name": "label",
            "required": true,
            "value": {
              "kind": "string"
            }
          },
          {
            "name": "requiredFeatures",
            "required": true,
            "value": {
              "kind": "sequence",
              "element": "string",
              "maxCountFrom": "codecLayout.sequenceMaxCount"
            }
          },
          {
            "name": "requiredLimits",
            "required": true,
            "value": {
              "kind": "dictionary",
              "key": "string",
              "value": "nonnegative-js-safe-integer",
              "maxCountFrom": "codecLayout.dictionaryMaxFields"
            }
          },
          {
            "name": "defaultQueue",
            "required": true,
            "value": {
              "kind": "closed-dictionary",
              "unknownFields": "reject",
              "fields": [
                {
                  "name": "label",
                  "required": true,
                  "value": {
                    "kind": "string"
                  }
                }
              ]
            }
          }
        ]
      },
      "sortedUniqueFeatureSequenceV1": {
        "kind": "sequence",
        "countType": "u32le",
        "elementType": "utf8",
        "maxCountFrom": "codecLayout.sequenceMaxCount",
        "constraints": [
          "strictly-increasing-utf8-strings"
        ]
      },
      "completeDeviceLimitsV1": {
        "kind": "ordered-record",
        "fieldNamesFrom": "semanticProjection.limitPolicy.limits",
        "requiredFieldCount": 36,
        "valueType": "u64le",
        "constraints": [
          "js-safe-integer"
        ]
      },
      "gpuDeviceCompletionBodyV1": {
        "kind": "struct",
        "fields": [
          {
            "name": "objectId",
            "type": "u64le",
            "constraint": "positive"
          },
          {
            "name": "objectGeneration",
            "type": "u64le",
            "constraint": "positive"
          },
          {
            "name": "logicalDeviceId",
            "type": "u64le",
            "constraint": "positive"
          },
          {
            "name": "logicalDeviceGeneration",
            "type": "u64le",
            "constraint": "positive"
          },
          {
            "name": "providerGeneration",
            "type": "u64le",
            "constraint": "positive"
          },
          {
            "name": "queueObjectId",
            "type": "u64le",
            "constraint": "positive"
          },
          {
            "name": "queueObjectGeneration",
            "type": "u64le",
            "constraint": "positive"
          },
          {
            "name": "features",
            "type": "sortedUniqueFeatureSequenceV1"
          },
          {
            "name": "limits",
            "type": "completeDeviceLimitsV1"
          },
          {
            "name": "diagnosticMessage",
            "type": "utf8",
            "maxBytesFrom": "codecLayout.diagnosticMaxBytes"
          }
        ]
      }
    },
    "routes": [
      {
        "operationId": "GPU.requestAdapter",
        "wireId": 1660448199,
        "request": {
          "payloadRole": "service-request-payload-decoder-plus-operation-specific-call-joins",
          "catalog": {
            "name": "serviceArguments",
            "tag": "gpu-request-adapter-service-request-v1",
            "wireTag": 2
          },
          "payload": {
            "kind": "struct",
            "fields": [
              {
                "name": "header",
                "type": "headerV1",
                "constants": {
                  "magic": "IBGQ",
                  "version": 1,
                  "codecTag": 2,
                  "operationWireId": 1660448199
                }
              },
              {
                "name": "receiver",
                "type": "objectReferenceV1"
              },
              {
                "name": "target",
                "type": "optionalReferenceV1"
              },
              {
                "name": "capturedScopeId",
                "type": "u64le"
              },
              {
                "name": "adapterOrdinal",
                "type": "u64le"
              },
              {
                "name": "deviceIngressOrdinal",
                "type": "u64le"
              },
              {
                "name": "queueIngressOrdinal",
                "type": "u64le"
              },
              {
                "name": "sealedLocalTimeline",
                "type": "canonicalValueV1"
              },
              {
                "name": "convertedArguments",
                "type": "canonicalValueV1",
                "constraintType": "requestAdapterOptionsV1"
              }
            ]
          },
          "carrierJoins": [
            {
              "payloadPath": "header.operationWireId",
              "carrierPath": "operation_id",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.kind",
              "carrierPath": "receiver.kind",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.objectId",
              "carrierPath": "receiver.object_id",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.objectGeneration",
              "carrierPath": "receiver.object_generation",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.logicalDeviceId",
              "carrierPath": "ingress_device.logical_device_id",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.logicalDeviceGeneration",
              "carrierPath": "ingress_device.logical_device_generation",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.providerGeneration",
              "carrierPath": "ingress_device.provider_generation",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.providerGeneration",
              "carrierPath": "provider_generation",
              "operator": "equal"
            },
            {
              "payloadPath": "target",
              "carrierPath": "target",
              "operator": "absent-iff-all-zero-reference"
            },
            {
              "payloadPath": "capturedScopeId",
              "carrierPath": "captured_scope_id",
              "operator": "equal"
            },
            {
              "payloadPath": "adapterOrdinal",
              "carrierPath": "adapter_ordinal",
              "operator": "equal"
            },
            {
              "payloadPath": "deviceIngressOrdinal",
              "carrierPath": "device_ingress_ordinal",
              "operator": "equal"
            },
            {
              "payloadPath": "queueIngressOrdinal",
              "carrierPath": "queue_ingress_ordinal",
              "operator": "equal"
            }
          ],
          "carrierConstraints": [
            {
              "carrierPath": "operation_id",
              "operator": "equal",
              "value": 1660448199
            },
            {
              "carrierPath": "flags",
              "operator": "equal",
              "value": 0
            },
            {
              "carrierPath": "topology_id",
              "operator": "equal",
              "valueFrom": "constants.providerTopologyId"
            },
            {
              "carrierPath": "ingress_device",
              "operator": "all-zero"
            },
            {
              "carrierPath": "provider_generation",
              "operator": "equal",
              "value": "0"
            },
            {
              "carrierPath": "operation_instance_id",
              "operator": "positive"
            },
            {
              "carrierPath": "promise_id",
              "operator": "positive"
            },
            {
              "carrierPath": "receiver.kind",
              "operator": "equal",
              "valueFrom": "objectKindTags.GPU"
            },
            {
              "carrierPath": "receiver.flags",
              "operator": "equal",
              "value": 0
            },
            {
              "carrierPath": "receiver.object_id",
              "operator": "positive"
            },
            {
              "carrierPath": "receiver.object_generation",
              "operator": "positive"
            },
            {
              "carrierPath": "target",
              "operator": "all-zero"
            },
            {
              "carrierPath": "captured_scope_id",
              "operator": "equal",
              "value": "0"
            },
            {
              "carrierPath": "adapter_ordinal",
              "operator": "equal",
              "value": "0"
            },
            {
              "carrierPath": "device_ingress_ordinal",
              "operator": "equal",
              "value": "0"
            },
            {
              "carrierPath": "queue_ingress_ordinal",
              "operator": "equal",
              "value": "0"
            }
          ],
          "valueConstraints": [
            {
              "payloadPath": "sealedLocalTimeline",
              "operator": "exact-empty-sequence"
            },
            {
              "payloadPath": "convertedArguments",
              "operator": "conforms-to-type",
              "type": "requestAdapterOptionsV1"
            }
          ],
          "noTrailingBytes": true
        },
        "completion": {
          "payloadRole": "service-completion-payload-codec-plus-operation-specific-event-joins",
          "catalog": {
            "name": "serviceCompletions",
            "tag": "nullable-gpu-adapter-service-completion-v2",
            "wireTag": 6
          },
          "commonCarrierConstraints": [
            {
              "carrierPath": "kind",
              "operator": "equal",
              "value": 1,
              "symbol": "EXACT_GPU_SERVICE_EVENT_OPERATION_RESULT_V2"
            },
            {
              "carrierPath": "record.operation_result.status",
              "operator": "equal",
              "value": 0
            },
            {
              "carrierPath": "record.operation_result.operation.operation_id",
              "operator": "equal",
              "value": 1660448199
            },
            {
              "carrierPath": "record.operation_result.operation.device_transition",
              "operator": "equal",
              "value": 0,
              "symbol": "EXACT_GPU_DEVICE_UNCHANGED_V2"
            },
            {
              "carrierPath": "record.operation_result.operation.ingress_device",
              "operator": "all-zero"
            },
            {
              "carrierPath": "record.operation_result.operation.result_device",
              "operator": "all-zero"
            }
          ],
          "variants": [
            {
              "name": "null",
              "resultKind": 2,
              "resultKindSymbol": "EXACT_GPU_RESULT_NULL_V2",
              "payload": {
                "kind": "empty",
                "exactLengthBytes": 0
              }
            },
            {
              "name": "object",
              "resultKind": 3,
              "resultKindSymbol": "EXACT_GPU_RESULT_OBJECT_V2",
              "objectKind": "GPUAdapter",
              "payload": {
                "kind": "struct",
                "fields": [
                  {
                    "name": "header",
                    "type": "headerV1",
                    "constants": {
                      "magic": "IBGR",
                      "version": 1,
                      "codecTag": 6,
                      "operationWireId": 1660448199
                    }
                  },
                  {
                    "name": "present",
                    "type": "u8",
                    "constant": 1
                  },
                  {
                    "name": "objectId",
                    "type": "u64le",
                    "constraint": "positive"
                  },
                  {
                    "name": "objectGeneration",
                    "type": "u64le",
                    "constraint": "positive"
                  },
                  {
                    "name": "providerGeneration",
                    "type": "u64le",
                    "constraint": "positive"
                  },
                  {
                    "name": "serviceDetachedExpired",
                    "type": "u8",
                    "constraint": "boolean-zero-or-one"
                  }
                ]
              },
              "carrierJoins": [
                {
                  "payloadPath": "providerGeneration",
                  "carrierPath": "record.operation_result.operation.provider_generation",
                  "operator": "equal"
                }
              ],
              "noTrailingBytes": true
            }
          ]
        }
      },
      {
        "operationId": "GPUAdapter.requestDevice",
        "wireId": 194635792,
        "request": {
          "payloadRole": "service-request-payload-decoder-plus-operation-specific-call-joins",
          "catalog": {
            "name": "serviceArguments",
            "tag": "gpu-request-device-service-request-v1",
            "wireTag": 3
          },
          "payload": {
            "kind": "struct",
            "fields": [
              {
                "name": "header",
                "type": "headerV1",
                "constants": {
                  "magic": "IBGQ",
                  "version": 1,
                  "codecTag": 3,
                  "operationWireId": 194635792
                }
              },
              {
                "name": "receiver",
                "type": "objectReferenceV1"
              },
              {
                "name": "target",
                "type": "optionalReferenceV1"
              },
              {
                "name": "capturedScopeId",
                "type": "u64le"
              },
              {
                "name": "adapterOrdinal",
                "type": "u64le"
              },
              {
                "name": "deviceIngressOrdinal",
                "type": "u64le"
              },
              {
                "name": "queueIngressOrdinal",
                "type": "u64le"
              },
              {
                "name": "sealedLocalTimeline",
                "type": "canonicalValueV1"
              },
              {
                "name": "convertedArguments",
                "type": "canonicalValueV1",
                "constraintType": "requestDeviceDescriptorV1"
              }
            ]
          },
          "carrierJoins": [
            {
              "payloadPath": "header.operationWireId",
              "carrierPath": "operation_id",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.kind",
              "carrierPath": "receiver.kind",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.objectId",
              "carrierPath": "receiver.object_id",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.objectGeneration",
              "carrierPath": "receiver.object_generation",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.logicalDeviceId",
              "carrierPath": "ingress_device.logical_device_id",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.logicalDeviceGeneration",
              "carrierPath": "ingress_device.logical_device_generation",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.providerGeneration",
              "carrierPath": "provider_generation",
              "operator": "equal"
            },
            {
              "payloadPath": "target",
              "carrierPath": "target",
              "operator": "absent-iff-all-zero-reference"
            },
            {
              "payloadPath": "capturedScopeId",
              "carrierPath": "captured_scope_id",
              "operator": "equal"
            },
            {
              "payloadPath": "adapterOrdinal",
              "carrierPath": "adapter_ordinal",
              "operator": "equal"
            },
            {
              "payloadPath": "deviceIngressOrdinal",
              "carrierPath": "device_ingress_ordinal",
              "operator": "equal"
            },
            {
              "payloadPath": "queueIngressOrdinal",
              "carrierPath": "queue_ingress_ordinal",
              "operator": "equal"
            }
          ],
          "carrierConstraints": [
            {
              "carrierPath": "operation_id",
              "operator": "equal",
              "value": 194635792
            },
            {
              "carrierPath": "flags",
              "operator": "equal",
              "value": 0
            },
            {
              "carrierPath": "topology_id",
              "operator": "equal",
              "valueFrom": "constants.providerTopologyId"
            },
            {
              "carrierPath": "ingress_device",
              "operator": "all-zero"
            },
            {
              "carrierPath": "provider_generation",
              "operator": "positive"
            },
            {
              "carrierPath": "operation_instance_id",
              "operator": "positive"
            },
            {
              "carrierPath": "promise_id",
              "operator": "positive"
            },
            {
              "carrierPath": "receiver.kind",
              "operator": "equal",
              "valueFrom": "objectKindTags.GPUAdapter"
            },
            {
              "carrierPath": "receiver.flags",
              "operator": "equal",
              "value": 0
            },
            {
              "carrierPath": "receiver.object_id",
              "operator": "positive"
            },
            {
              "carrierPath": "receiver.object_generation",
              "operator": "positive"
            },
            {
              "carrierPath": "target",
              "operator": "all-zero"
            },
            {
              "carrierPath": "captured_scope_id",
              "operator": "equal",
              "value": "0"
            },
            {
              "carrierPath": "adapter_ordinal",
              "operator": "positive"
            },
            {
              "carrierPath": "device_ingress_ordinal",
              "operator": "equal",
              "value": "0"
            },
            {
              "carrierPath": "queue_ingress_ordinal",
              "operator": "equal",
              "value": "0"
            }
          ],
          "valueConstraints": [
            {
              "payloadPath": "sealedLocalTimeline",
              "operator": "exact-empty-sequence"
            },
            {
              "payloadPath": "convertedArguments",
              "operator": "conforms-to-type",
              "type": "requestDeviceDescriptorV1"
            },
            {
              "payloadPath": "convertedArguments",
              "operator": "untrusted-semantic-service-ingress-only-never-provider-input"
            }
          ],
          "semanticServiceDerivations": [
            {
              "name": "generatedLogicalProviderDescriptor",
              "ownership": "native-semantic-service-derived-never-payload-or-wrapper-supplied",
              "inputs": [
                "untrusted-convertedArguments",
                "authenticated-adapter-state",
                "authenticated-feature-level-profile",
                "authenticated-capability-grant",
                "versioned-service-internal-requirements"
              ],
              "output": "exact-logical-features-limits-plus-versioned-service-internal-requirements-only",
              "forbiddenProviderInputs": [
                "convertedArguments",
                "raw-GPUDeviceDescriptor"
              ],
              "requiredBefore": [
                "provider-admission"
              ],
              "authenticatedCrossLinks": [
                {
                  "derivedPath": "providerGeneration",
                  "carrierPath": "provider_generation",
                  "operator": "equal"
                },
                {
                  "derivedPath": "adapterIdentity",
                  "carrierPath": "receiver",
                  "operator": "derived-from-authenticated-reference"
                }
              ]
            },
            {
              "name": "authenticatedResultSelectionIdentity",
              "ownership": "native-semantic-service-allocated-never-payload-or-wrapper-supplied",
              "inputs": [
                "authenticated-retained-call",
                "live-device-reservation",
                "authenticated-adapter-publication-credit",
                "authenticated-account-capacity-state"
              ],
              "output": "fresh-device-object-logical-device-and-queue-identities",
              "requiredBefore": [
                "provider-admission",
                "completion-encoding"
              ],
              "authenticatedCrossLinks": [
                {
                  "derivedPath": "logicalDeviceId",
                  "carrierPath": "record.operation_result.operation.result_device.logical_device_id",
                  "operator": "equal"
                },
                {
                  "derivedPath": "logicalDeviceGeneration",
                  "carrierPath": "record.operation_result.operation.result_device.logical_device_generation",
                  "operator": "equal"
                },
                {
                  "derivedPath": "providerGeneration",
                  "carrierPath": "record.operation_result.operation.result_device.provider_generation",
                  "operator": "equal"
                },
                {
                  "derivedPath": "retainedOperationIdentity",
                  "carrierPath": "record.operation_result.operation.operation_instance_id",
                  "operator": "bound-to-authenticated-retained-call"
                },
                {
                  "derivedPath": "retainedPromiseIdentity",
                  "carrierPath": "record.operation_result.operation.promise_id",
                  "operator": "bound-to-authenticated-retained-call"
                }
              ]
            }
          ],
          "executablePrerequisites": [
            "generatedLogicalProviderDescriptor",
            "authenticatedResultSelectionIdentity"
          ],
          "noTrailingBytes": true
        },
        "completion": {
          "payloadRole": "service-completion-payload-codec-plus-operation-specific-event-joins",
          "catalog": {
            "name": "serviceCompletions",
            "tag": "gpu-device-service-completion-v1",
            "wireTag": 4
          },
          "commonCarrierConstraints": [
            {
              "carrierPath": "kind",
              "operator": "equal",
              "value": 1,
              "symbol": "EXACT_GPU_SERVICE_EVENT_OPERATION_RESULT_V2"
            },
            {
              "carrierPath": "record.operation_result.status",
              "operator": "equal",
              "value": 0
            },
            {
              "carrierPath": "record.operation_result.operation.operation_id",
              "operator": "equal",
              "value": 194635792
            },
            {
              "carrierPath": "record.operation_result.operation.ingress_device",
              "operator": "all-zero"
            },
            {
              "carrierPath": "record.operation_result.operation.result_device",
              "operator": "positive"
            },
            {
              "carrierPath": "record.operation_result.operation.provider_generation",
              "operator": "positive"
            },
            {
              "carrierPath": "record.operation_result.operation.receiver.kind",
              "operator": "equal",
              "valueFrom": "objectKindTags.GPUAdapter"
            },
            {
              "carrierPath": "record.operation_result.operation.target",
              "operator": "all-zero"
            },
            {
              "carrierPath": "record.operation_result.operation.adapter_ordinal",
              "operator": "positive"
            },
            {
              "carrierPath": "record.operation_result.operation.device_ingress_ordinal",
              "operator": "equal",
              "value": "0"
            },
            {
              "carrierPath": "record.operation_result.operation.queue_ingress_ordinal",
              "operator": "equal",
              "value": "0"
            },
            {
              "carrierPath": "record.operation_result.result_kind",
              "operator": "equal",
              "value": 3,
              "symbol": "EXACT_GPU_RESULT_OBJECT_V2"
            }
          ],
          "payload": {
            "kind": "struct",
            "fields": [
              {
                "name": "header",
                "type": "headerV1",
                "constants": {
                  "magic": "IBGR",
                  "version": 1,
                  "codecTag": 4,
                  "operationWireId": 194635792
                }
              },
              {
                "name": "body",
                "type": "gpuDeviceCompletionBodyV1"
              }
            ]
          },
          "carrierJoins": [
            {
              "payloadPath": "body.logicalDeviceId",
              "carrierPath": "record.operation_result.operation.result_device.logical_device_id",
              "operator": "equal"
            },
            {
              "payloadPath": "body.logicalDeviceGeneration",
              "carrierPath": "record.operation_result.operation.result_device.logical_device_generation",
              "operator": "equal"
            },
            {
              "payloadPath": "body.providerGeneration",
              "carrierPath": "record.operation_result.operation.result_device.provider_generation",
              "operator": "equal"
            },
            {
              "payloadPath": "body.providerGeneration",
              "carrierPath": "record.operation_result.operation.provider_generation",
              "operator": "equal"
            }
          ],
          "serviceResultJoins": [
            {
              "payloadPath": "body.objectId",
              "serviceResultPath": "authenticatedResultSelectionIdentity.deviceObjectId",
              "operator": "equal"
            },
            {
              "payloadPath": "body.objectGeneration",
              "serviceResultPath": "authenticatedResultSelectionIdentity.deviceObjectGeneration",
              "operator": "equal"
            },
            {
              "payloadPath": "body.queueObjectId",
              "serviceResultPath": "authenticatedResultSelectionIdentity.queueObjectId",
              "operator": "equal"
            },
            {
              "payloadPath": "body.queueObjectGeneration",
              "serviceResultPath": "authenticatedResultSelectionIdentity.queueObjectGeneration",
              "operator": "equal"
            },
            {
              "payloadPath": "body.features",
              "serviceResultPath": "generatedLogicalProviderDescriptor.logicalFeatures",
              "operator": "equal"
            },
            {
              "payloadPath": "body.limits",
              "serviceResultPath": "generatedLogicalProviderDescriptor.logicalLimits",
              "operator": "equal"
            },
            {
              "payloadPath": "body.diagnosticMessage",
              "serviceResultPath": "nativeSemanticServiceResult.diagnosticMessage",
              "operator": "equal-never-caller-selected"
            }
          ],
          "variants": [
            {
              "name": "live-object",
              "carrierConstraints": [
                {
                  "carrierPath": "record.operation_result.operation.device_transition",
                  "operator": "equal",
                  "value": 1,
                  "symbol": "EXACT_GPU_DEVICE_ASSIGNED_V2"
                },
                {
                  "carrierPath": "record.operation_result.operation.provider_admission",
                  "operator": "equal",
                  "value": 1,
                  "symbol": "EXACT_GPU_PROVIDER_ADMITTED_V2"
                },
                {
                  "carrierPath": "record.operation_result.operation.physical_sequence",
                  "operator": "positive"
                },
                {
                  "carrierPath": "detachedAlreadyLost",
                  "operator": "equal",
                  "value": false
                },
                {
                  "carrierPath": "lossReason-and-backendClass",
                  "operator": "absent"
                }
              ],
              "payloadConstraints": [
                {
                  "payloadPath": "body.diagnosticMessage",
                  "operator": "exact-empty-string"
                }
              ]
            },
            {
              "name": "detached-not-admitted-object",
              "carrierConstraints": [
                {
                  "carrierPath": "record.operation_result.operation.device_transition",
                  "operator": "equal",
                  "value": 2,
                  "symbol": "EXACT_GPU_DEVICE_ASSIGNED_DETACHED_V2"
                },
                {
                  "carrierPath": "record.operation_result.operation.provider_admission",
                  "operator": "equal",
                  "value": 0,
                  "symbol": "EXACT_GPU_PROVIDER_NOT_ADMITTED_V2"
                },
                {
                  "carrierPath": "record.operation_result.operation.physical_sequence",
                  "operator": "equal",
                  "value": "0"
                },
                {
                  "carrierPath": "detachedAlreadyLost",
                  "operator": "equal",
                  "value": true
                },
                {
                  "carrierPath": "lossReason",
                  "operator": "equal",
                  "value": 1,
                  "symbol": "EXACT_GPU_DEVICE_LOSS_UNKNOWN_V2"
                },
                {
                  "carrierPath": "backendClass",
                  "operator": "equal",
                  "value": 0,
                  "symbol": "EXACT_GPU_BACKEND_NONE_V2"
                }
              ],
              "payloadConstraints": [
                {
                  "payloadPath": "body.diagnosticMessage",
                  "operator": "native-semantic-service-owned-stable-utf8-within-reviewed-bound"
                }
              ]
            },
            {
              "name": "detached-admitted-object",
              "carrierConstraints": [
                {
                  "carrierPath": "record.operation_result.operation.device_transition",
                  "operator": "equal",
                  "value": 2,
                  "symbol": "EXACT_GPU_DEVICE_ASSIGNED_DETACHED_V2"
                },
                {
                  "carrierPath": "record.operation_result.operation.provider_admission",
                  "operator": "equal",
                  "value": 1,
                  "symbol": "EXACT_GPU_PROVIDER_ADMITTED_V2"
                },
                {
                  "carrierPath": "record.operation_result.operation.physical_sequence",
                  "operator": "positive"
                },
                {
                  "carrierPath": "detachedAlreadyLost",
                  "operator": "equal",
                  "value": true
                },
                {
                  "carrierPath": "lossReason",
                  "operator": "equal",
                  "value": 1,
                  "symbol": "EXACT_GPU_DEVICE_LOSS_UNKNOWN_V2"
                },
                {
                  "carrierPath": "backendClass",
                  "operator": "equal",
                  "value": 0,
                  "symbol": "EXACT_GPU_BACKEND_NONE_V2"
                }
              ],
              "payloadConstraints": [
                {
                  "payloadPath": "body.diagnosticMessage",
                  "operator": "native-semantic-service-owned-stable-utf8-within-reviewed-bound"
                }
              ]
            }
          ],
          "noTrailingBytes": true
        }
      },
      {
        "operationId": "GPUDevice.destroy",
        "wireId": 206890944,
        "request": {
          "payloadRole": "service-request-payload-decoder-plus-operation-specific-call-joins",
          "catalog": {
            "name": "serviceArguments",
            "tag": "gpu-device-cleanup-service-request-v1",
            "wireTag": 12
          },
          "payload": {
            "kind": "struct",
            "fields": [
              {
                "name": "header",
                "type": "headerV1",
                "constants": {
                  "magic": "IBGQ",
                  "version": 1,
                  "codecTag": 12,
                  "operationWireId": 206890944
                }
              },
              {
                "name": "receiver",
                "type": "objectReferenceV1"
              },
              {
                "name": "target",
                "type": "optionalReferenceV1"
              },
              {
                "name": "capturedScopeId",
                "type": "u64le"
              },
              {
                "name": "adapterOrdinal",
                "type": "u64le"
              },
              {
                "name": "deviceIngressOrdinal",
                "type": "u64le"
              },
              {
                "name": "queueIngressOrdinal",
                "type": "u64le"
              },
              {
                "name": "sealedLocalTimeline",
                "type": "canonicalValueV1"
              },
              {
                "name": "convertedArguments",
                "type": "canonicalValueV1"
              }
            ]
          },
          "carrierJoins": [
            {
              "payloadPath": "header.operationWireId",
              "carrierPath": "operation_id",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.kind",
              "carrierPath": "receiver.kind",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.objectId",
              "carrierPath": "receiver.object_id",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.objectGeneration",
              "carrierPath": "receiver.object_generation",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.logicalDeviceId",
              "carrierPath": "ingress_device.logical_device_id",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.logicalDeviceGeneration",
              "carrierPath": "ingress_device.logical_device_generation",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.providerGeneration",
              "carrierPath": "ingress_device.provider_generation",
              "operator": "equal"
            },
            {
              "payloadPath": "receiver.providerGeneration",
              "carrierPath": "provider_generation",
              "operator": "equal"
            },
            {
              "payloadPath": "target",
              "carrierPath": "target",
              "operator": "absent-iff-all-zero-reference"
            },
            {
              "payloadPath": "capturedScopeId",
              "carrierPath": "captured_scope_id",
              "operator": "equal"
            },
            {
              "payloadPath": "adapterOrdinal",
              "carrierPath": "adapter_ordinal",
              "operator": "equal"
            },
            {
              "payloadPath": "deviceIngressOrdinal",
              "carrierPath": "device_ingress_ordinal",
              "operator": "equal"
            },
            {
              "payloadPath": "queueIngressOrdinal",
              "carrierPath": "queue_ingress_ordinal",
              "operator": "equal"
            }
          ],
          "carrierConstraints": [
            {
              "carrierPath": "operation_id",
              "operator": "equal",
              "value": 206890944
            },
            {
              "carrierPath": "flags",
              "operator": "equal",
              "value": 0
            },
            {
              "carrierPath": "topology_id",
              "operator": "equal",
              "valueFrom": "constants.providerTopologyId"
            },
            {
              "carrierPath": "ingress_device",
              "operator": "positive"
            },
            {
              "carrierPath": "provider_generation",
              "operator": "positive"
            },
            {
              "carrierPath": "operation_instance_id",
              "operator": "positive"
            },
            {
              "carrierPath": "promise_id",
              "operator": "equal",
              "value": "0"
            },
            {
              "carrierPath": "receiver.kind",
              "operator": "equal",
              "valueFrom": "objectKindTags.GPUDevice"
            },
            {
              "carrierPath": "receiver.flags",
              "operator": "equal",
              "value": 0
            },
            {
              "carrierPath": "receiver.object_id",
              "operator": "positive"
            },
            {
              "carrierPath": "receiver.object_generation",
              "operator": "positive"
            },
            {
              "carrierPath": "target",
              "operator": "all-zero"
            },
            {
              "carrierPath": "adapter_ordinal",
              "operator": "equal",
              "value": "0"
            },
            {
              "carrierPath": "device_ingress_ordinal",
              "operator": "positive"
            },
            {
              "carrierPath": "queue_ingress_ordinal",
              "operator": "equal",
              "value": "0"
            }
          ],
          "valueConstraints": [
            {
              "payloadPath": "sealedLocalTimeline",
              "operator": "canonical-sequence-within-layout-bounds"
            },
            {
              "payloadPath": "sealedLocalTimeline",
              "operator": "untrusted-wrapper-record-prefix-join-only-never-authority"
            },
            {
              "payloadPath": "convertedArguments",
              "operator": "exact-null"
            }
          ],
          "semanticServiceBoundary": {
            "stateAuthority": "authenticated-device-lifecycle-operation-and-provider-tables",
            "payloadRole": "comparison-input-only-never-authority",
            "requiredAfterDecode": [
              "authenticate-contiguous-sealed-local-timeline-prefix",
              "validate-idempotent-device-terminal-state",
              "validate-cleanup-predicates",
              "select-provider-admission-and-physical-sequence"
            ],
            "completionEncodingRequires": [
              "authenticated-retained-call",
              "service-owned-operation-result"
            ]
          },
          "executablePrerequisites": [],
          "noTrailingBytes": true
        },
        "completion": {
          "payloadRole": "service-completion-payload-codec-plus-operation-specific-event-joins",
          "catalog": {
            "name": "serviceCompletions",
            "tag": "terminal-receipt-service-completion-v1",
            "wireTag": 2
          },
          "commonCarrierConstraints": [
            {
              "carrierPath": "kind",
              "operator": "equal",
              "value": 1,
              "symbol": "EXACT_GPU_SERVICE_EVENT_OPERATION_RESULT_V2"
            },
            {
              "carrierPath": "record.operation_result.status",
              "operator": "equal",
              "value": 0
            },
            {
              "carrierPath": "record.operation_result.operation.operation_id",
              "operator": "equal",
              "value": 206890944
            },
            {
              "carrierPath": "record.operation_result.operation.device_transition",
              "operator": "equal",
              "value": 0,
              "symbol": "EXACT_GPU_DEVICE_UNCHANGED_V2"
            },
            {
              "carrierPath": "record.operation_result.operation.ingress_device",
              "operator": "positive"
            },
            {
              "carrierPath": "record.operation_result.operation.result_device",
              "operator": "positive"
            },
            {
              "carrierPath": "record.operation_result.operation.provider_generation",
              "operator": "positive"
            },
            {
              "carrierPath": "record.operation_result.operation.promise_id",
              "operator": "equal",
              "value": "0"
            },
            {
              "carrierPath": "record.operation_result.operation.receiver.kind",
              "operator": "equal",
              "valueFrom": "objectKindTags.GPUDevice"
            },
            {
              "carrierPath": "record.operation_result.operation.target",
              "operator": "all-zero"
            },
            {
              "carrierPath": "record.operation_result.operation.adapter_ordinal",
              "operator": "equal",
              "value": "0"
            },
            {
              "carrierPath": "record.operation_result.operation.device_ingress_ordinal",
              "operator": "positive"
            },
            {
              "carrierPath": "record.operation_result.operation.queue_ingress_ordinal",
              "operator": "equal",
              "value": "0"
            },
            {
              "carrierPath": "record.operation_result.result_kind",
              "operator": "equal",
              "value": 0,
              "symbol": "EXACT_GPU_RESULT_NONE_V2"
            }
          ],
          "payload": {
            "kind": "empty",
            "exactLengthBytes": 0
          },
          "semanticTerminalMapping": {
            "authorityPath": "semanticProjection.providerRoutingPrograms[operationId=GPUDevice.destroy]",
            "terminals": [
              {
                "terminalId": "repeat-cleanup-noop",
                "errorTiming": "none",
                "resultDisposition": "return-undefined",
                "providerTokenCount": 0,
                "physicalSequenceCount": 0,
                "event": {
                  "kind": "operation-result",
                  "kindValue": 1,
                  "kindSymbol": "EXACT_GPU_SERVICE_EVENT_OPERATION_RESULT_V2",
                  "resultKind": 0,
                  "resultKindSymbol": "EXACT_GPU_RESULT_NONE_V2",
                  "status": 0,
                  "completionVariant": "repeat-cleanup-noop"
                }
              },
              {
                "terminalId": "first-cleanup-rejection",
                "errorTiming": "device-timeline",
                "resultDisposition": "return-undefined-and-report-error",
                "providerTokenCount": 0,
                "physicalSequenceCount": 0,
                "event": {
                  "kind": "device-error",
                  "kindValue": 2,
                  "kindSymbol": "EXACT_GPU_SERVICE_EVENT_DEVICE_ERROR_V2",
                  "completionPayloadEncoderEligibility": "excluded-not-an-operation-result"
                }
              },
              {
                "terminalId": "first-cleanup-provider",
                "errorTiming": "none",
                "resultDisposition": "return-undefined",
                "providerTokenCount": 1,
                "physicalSequenceCount": 1,
                "event": {
                  "kind": "operation-result",
                  "kindValue": 1,
                  "kindSymbol": "EXACT_GPU_SERVICE_EVENT_OPERATION_RESULT_V2",
                  "resultKind": 0,
                  "resultKindSymbol": "EXACT_GPU_RESULT_NONE_V2",
                  "status": 0,
                  "completionVariant": "first-cleanup-provider"
                }
              }
            ]
          },
          "variants": [
            {
              "name": "repeat-cleanup-noop",
              "carrierConstraints": [
                {
                  "carrierPath": "record.operation_result.operation.provider_admission",
                  "operator": "equal",
                  "value": 0,
                  "symbol": "EXACT_GPU_PROVIDER_NOT_ADMITTED_V2"
                },
                {
                  "carrierPath": "record.operation_result.operation.physical_sequence",
                  "operator": "equal",
                  "value": "0"
                }
              ]
            },
            {
              "name": "first-cleanup-provider",
              "carrierConstraints": [
                {
                  "carrierPath": "record.operation_result.operation.provider_admission",
                  "operator": "equal",
                  "value": 1,
                  "symbol": "EXACT_GPU_PROVIDER_ADMITTED_V2"
                },
                {
                  "carrierPath": "record.operation_result.operation.physical_sequence",
                  "operator": "positive"
                }
              ]
            }
          ],
          "noTrailingBytes": true
        }
      }
    ]
  },
  "objectKindAuthority": {
    "path": "include/exact_runtime.h",
    "sha256": "5777fe2e0c59f06ce44c18ba478d3f9f56d03cb285e2a212b3760895a5340020"
  },
  "objectKindTags": {
    "None": 0,
    "GPU": 1,
    "GPUAdapter": 2,
    "GPUDevice": 3,
    "GPUQueue": 4,
    "GPUBuffer": 5,
    "GPUTexture": 6,
    "GPUTextureView": 7,
    "GPUSampler": 8,
    "GPUBindGroupLayout": 9,
    "GPUBindGroup": 10,
    "GPUPipelineLayout": 11,
    "GPUShaderModule": 12,
    "GPUComputePipeline": 13,
    "GPURenderPipeline": 14,
    "GPUCommandEncoder": 15,
    "GPUComputePassEncoder": 16,
    "GPURenderPassEncoder": 17,
    "GPURenderBundleEncoder": 18,
    "GPURenderBundle": 19,
    "GPUCommandBuffer": 20,
    "GPUQuerySet": 21,
    "GPUCanvasContext": 22
  },
  "carrierConstants": {
    "EXACT_GPU_SERVICE_EVENT_OPERATION_RESULT_V2": 1,
    "EXACT_GPU_SERVICE_EVENT_DEVICE_ERROR_V2": 2,
    "EXACT_GPU_DEVICE_UNCHANGED_V2": 0,
    "EXACT_GPU_DEVICE_ASSIGNED_V2": 1,
    "EXACT_GPU_DEVICE_ASSIGNED_DETACHED_V2": 2,
    "EXACT_GPU_PROVIDER_NOT_ADMITTED_V2": 0,
    "EXACT_GPU_PROVIDER_ADMITTED_V2": 1,
    "EXACT_GPU_DEVICE_LOSS_UNKNOWN_V2": 1,
    "EXACT_GPU_BACKEND_NONE_V2": 0,
    "EXACT_GPU_RESULT_NONE_V2": 0,
    "EXACT_GPU_RESULT_NULL_V2": 2,
    "EXACT_GPU_RESULT_OBJECT_V2": 3
  },
  "publicArguments": [
    {
      "wireTag": 1,
      "tag": "none-v1",
      "wireShape": "empty",
      "ownership": "none"
    },
    {
      "wireTag": 2,
      "tag": "gpu-request-adapter-options-v1",
      "wireShape": "GPURequestAdapterOptions-dictionary",
      "ownership": "owned-copy"
    },
    {
      "wireTag": 3,
      "tag": "gpu-device-descriptor-v1",
      "wireShape": "GPUDeviceDescriptor-dictionary",
      "ownership": "owned-copy-no-raw-provider-forward"
    },
    {
      "wireTag": 4,
      "tag": "gpu-canvas-configuration-v1",
      "wireShape": "GPUCanvasConfiguration-dictionary-plus-current-target-token",
      "ownership": "owned-copy"
    },
    {
      "wireTag": 5,
      "tag": "gpu-render-pass-descriptor-v1",
      "wireShape": "GPURenderPassDescriptor-dictionary-plus-handle-refs",
      "ownership": "recording-copy"
    },
    {
      "wireTag": 6,
      "tag": "gpu-command-buffer-descriptor-v1",
      "wireShape": "GPUCommandBufferDescriptor-dictionary",
      "ownership": "recording-copy"
    },
    {
      "wireTag": 7,
      "tag": "gpu-command-encoder-descriptor-v1",
      "wireShape": "GPUCommandEncoderDescriptor-dictionary",
      "ownership": "owned-copy"
    },
    {
      "wireTag": 8,
      "tag": "gpu-render-pipeline-descriptor-v1",
      "wireShape": "GPURenderPipelineDescriptor-dictionary-plus-shader-handle-refs",
      "ownership": "owned-copy"
    },
    {
      "wireTag": 9,
      "tag": "gpu-shader-module-descriptor-v1",
      "wireShape": "GPUShaderModuleDescriptor-dictionary-plus-wgsl-utf8",
      "ownership": "owned-copy"
    },
    {
      "wireTag": 10,
      "tag": "gpu-error-filter-v1",
      "wireShape": "validation-or-out-of-memory-or-internal-enum",
      "ownership": "wrapper-copy"
    },
    {
      "wireTag": 11,
      "tag": "gpu-command-buffer-handle-sequence-v1",
      "wireShape": "sequence-of-GPUCommandBuffer-handle-ref",
      "ownership": "owned-copy"
    },
    {
      "wireTag": 12,
      "tag": "gpu-draw-arguments-v1",
      "wireShape": "four-u32-with-webidl-defaults",
      "ownership": "recording-copy"
    },
    {
      "wireTag": 13,
      "tag": "gpu-render-pipeline-handle-v1",
      "wireShape": "GPURenderPipeline-handle-ref",
      "ownership": "recording-copy"
    },
    {
      "wireTag": 14,
      "tag": "gpu-texture-view-descriptor-v1",
      "wireShape": "GPUTextureViewDescriptor-dictionary",
      "ownership": "owned-copy"
    }
  ],
  "serviceArguments": [
    {
      "wireTag": 1,
      "tag": "none-service-request-v1",
      "wireShape": "no-service-call",
      "ownership": "none",
      "nativeProgramPrerequisitesRepresented": true,
      "executableFromCurrentAuthenticatedInputs": false,
      "unavailableSemanticFields": [
        "no-service-call"
      ]
    },
    {
      "wireTag": 2,
      "tag": "gpu-request-adapter-service-request-v1",
      "wireShape": "full typed GPU-singleton receiver derived from authenticated realm identity plus converted options and authority/account snapshot; the public wrapper receiver remains null and is never forwarded as the carrier receiver",
      "ownership": "owned-copy",
      "nativeProgramPrerequisitesRepresented": true,
      "executableFromCurrentAuthenticatedInputs": true,
      "unavailableSemanticFields": []
    },
    {
      "wireTag": 3,
      "tag": "gpu-request-device-service-request-v1",
      "wireShape": "adapter receiver plus generated logical provider descriptor and result-selection identity; never raw GPUDeviceDescriptor",
      "ownership": "owned-copy",
      "nativeProgramPrerequisitesRepresented": true,
      "executableFromCurrentAuthenticatedInputs": false,
      "unavailableSemanticFields": [
        "generatedLogicalProviderDescriptor",
        "authenticatedResultSelectionIdentity"
      ]
    },
    {
      "wireTag": 4,
      "tag": "gpu-canvas-configure-service-request-v1",
      "wireShape": "canvas-context receiver plus converted configuration and complete current target/account authority",
      "ownership": "owned-copy",
      "requiredSemanticFields": [
        "receiverContextRef",
        "attachmentGeneration",
        "contextGeneration",
        "configurationGeneration",
        "deviceRef",
        "format",
        "usage",
        "alphaMode",
        "colorSpace",
        "targetAuthorityDigest",
        "surfaceAccountToken",
        "surfaceAccountGeneration"
      ],
      "nativeProgramPrerequisitesRepresented": true,
      "executableFromCurrentAuthenticatedInputs": false,
      "unavailableSemanticFields": [
        "receiverContextRef",
        "attachmentGeneration",
        "contextGeneration",
        "configurationGeneration",
        "deviceRef",
        "format",
        "usage",
        "alphaMode",
        "colorSpace",
        "targetAuthorityDigest",
        "surfaceAccountToken",
        "surfaceAccountGeneration"
      ]
    },
    {
      "wireTag": 5,
      "tag": "gpu-create-command-encoder-service-request-v1",
      "wireShape": "device receiver plus wrapper-allocated command-encoder target and converted descriptor",
      "ownership": "owned-copy",
      "nativeProgramPrerequisitesRepresented": true,
      "executableFromCurrentAuthenticatedInputs": true,
      "unavailableSemanticFields": []
    },
    {
      "wireTag": 6,
      "tag": "gpu-create-render-pipeline-service-request-v1",
      "wireShape": "device receiver plus wrapper-allocated pipeline target, converted descriptor, and shader handle refs",
      "ownership": "owned-copy",
      "nativeProgramPrerequisitesRepresented": true,
      "executableFromCurrentAuthenticatedInputs": true,
      "unavailableSemanticFields": []
    },
    {
      "wireTag": 7,
      "tag": "gpu-create-shader-module-service-request-v1",
      "wireShape": "device receiver plus wrapper-allocated shader target and converted WGSL descriptor",
      "ownership": "owned-copy",
      "nativeProgramPrerequisitesRepresented": true,
      "executableFromCurrentAuthenticatedInputs": true,
      "unavailableSemanticFields": []
    },
    {
      "wireTag": 8,
      "tag": "gpu-push-error-scope-service-request-v1",
      "wireShape": "device receiver plus wrapper-mirrored scope identity/filter and authenticated device-ingress predecessor",
      "ownership": "owned-copy",
      "requiredSemanticFields": [
        "receiverDeviceRef",
        "scopeId",
        "filter",
        "deviceIngressOrdinal",
        "scopeStackGeneration",
        "precedingScopeId"
      ],
      "nativeProgramPrerequisitesRepresented": true,
      "executableFromCurrentAuthenticatedInputs": false,
      "unavailableSemanticFields": [
        "receiverDeviceRef",
        "scopeId",
        "filter",
        "deviceIngressOrdinal",
        "scopeStackGeneration",
        "precedingScopeId"
      ]
    },
    {
      "wireTag": 9,
      "tag": "gpu-create-texture-view-service-request-v1",
      "wireShape": "texture receiver plus wrapper-allocated view target, converted descriptor, and for a wrapper-local current texture its complete mint origin/provenance tuple; unknown texture receivers never materialize ambiently",
      "ownership": "owned-copy",
      "requiredSemanticFields": [
        "receiverTextureRef",
        "wrapperAllocatedTargetRef",
        "descriptor",
        "contextRef",
        "attachmentGeneration",
        "contextGeneration",
        "configurationGeneration",
        "currentEpoch",
        "mintOperationProvenance",
        "textureOriginDigest"
      ],
      "nativeProgramPrerequisitesRepresented": true,
      "executableFromCurrentAuthenticatedInputs": false,
      "unavailableSemanticFields": [
        "receiverTextureRef",
        "wrapperAllocatedTargetRef",
        "descriptor",
        "contextRef",
        "attachmentGeneration",
        "contextGeneration",
        "configurationGeneration",
        "currentEpoch",
        "mintOperationProvenance",
        "textureOriginDigest"
      ]
    },
    {
      "wireTag": 10,
      "tag": "gpu-pop-error-scope-service-request-v1",
      "wireShape": "device receiver plus exact scope identity, captured device-ingress barrier, and sealed pending-local prefix through that barrier",
      "ownership": "owned-copy",
      "requiredSemanticFields": [
        "receiverDeviceRef",
        "scopeId",
        "deviceIngressBarrier",
        "scopeStackGeneration",
        "sealedPendingLocalTimelineRecords"
      ],
      "nativeProgramPrerequisitesRepresented": true,
      "executableFromCurrentAuthenticatedInputs": false,
      "unavailableSemanticFields": [
        "receiverDeviceRef",
        "scopeId",
        "deviceIngressBarrier",
        "scopeStackGeneration",
        "sealedPendingLocalTimelineRecords"
      ]
    },
    {
      "wireTag": 11,
      "tag": "gpu-sealed-command-program-sequence-service-request-v1",
      "wireShape": "queue receiver plus bounded single-use command-buffer records; each record authenticates its logical operation identity, device-ingress/captured-scope provenance, device/generation, render-pass order, texture-view/pipeline refs, draw arguments, finish state, and canonical command-program digest",
      "ownership": "owned-copy-before-enqueue",
      "requiredSemanticFields": [
        "receiverQueueRef",
        "commandBufferRecords",
        "deviceGeneration",
        "queueIngressOrdinal",
        "capturedScopeId",
        "recordOperationProvenance",
        "passOrder",
        "textureViewRefs",
        "pipelineRefs",
        "drawArguments",
        "finishState",
        "commandProgramDigest"
      ],
      "nativeProgramPrerequisitesRepresented": true,
      "executableFromCurrentAuthenticatedInputs": false,
      "unavailableSemanticFields": [
        "receiverQueueRef",
        "commandBufferRecords",
        "deviceGeneration",
        "queueIngressOrdinal",
        "capturedScopeId",
        "recordOperationProvenance",
        "passOrder",
        "textureViewRefs",
        "pipelineRefs",
        "drawArguments",
        "finishState",
        "commandProgramDigest"
      ]
    },
    {
      "wireTag": 12,
      "tag": "gpu-device-cleanup-service-request-v1",
      "wireShape": "device receiver plus idempotent terminal intent",
      "ownership": "authority-reducing",
      "nativeProgramPrerequisitesRepresented": true,
      "executableFromCurrentAuthenticatedInputs": true,
      "unavailableSemanticFields": []
    },
    {
      "wireTag": 13,
      "tag": "gpu-texture-cleanup-service-request-v1",
      "wireShape": "texture receiver plus idempotent terminal intent; an unmaterialized current texture carries its complete mint origin and is retired without ambient materialization",
      "ownership": "authority-reducing",
      "requiredSemanticFields": [
        "receiverTextureRef",
        "materializationState",
        "contextRef",
        "attachmentGeneration",
        "contextGeneration",
        "configurationGeneration",
        "currentEpoch",
        "mintOperationProvenance",
        "textureOriginDigest"
      ],
      "nativeProgramPrerequisitesRepresented": true,
      "executableFromCurrentAuthenticatedInputs": false,
      "unavailableSemanticFields": [
        "receiverTextureRef",
        "materializationState",
        "contextRef",
        "attachmentGeneration",
        "contextGeneration",
        "configurationGeneration",
        "currentEpoch",
        "mintOperationProvenance",
        "textureOriginDigest"
      ]
    },
    {
      "wireTag": 14,
      "tag": "gpu-canvas-unconfigure-service-request-v1",
      "wireShape": "canvas-context receiver plus exact attachment/context/configuration identity and idempotent cleanup intent",
      "ownership": "authority-reducing",
      "requiredSemanticFields": [
        "receiverContextRef",
        "attachmentGeneration",
        "contextGeneration",
        "configurationGeneration",
        "targetAuthorityDigest",
        "surfaceAccountToken",
        "surfaceAccountGeneration"
      ],
      "nativeProgramPrerequisitesRepresented": true,
      "executableFromCurrentAuthenticatedInputs": false,
      "unavailableSemanticFields": [
        "receiverContextRef",
        "attachmentGeneration",
        "contextGeneration",
        "configurationGeneration",
        "targetAuthorityDigest",
        "surfaceAccountToken",
        "surfaceAccountGeneration"
      ]
    }
  ],
  "serviceCompletions": [
    {
      "wireTag": 1,
      "tag": "none-service-completion-v1",
      "wireShape": "no-service-call",
      "identity": "none"
    },
    {
      "wireTag": 2,
      "tag": "terminal-receipt-service-completion-v1",
      "wireShape": "empty success or typed device-timeline error keyed to the full admitted completion correlation identity",
      "identity": "one-terminal-receipt"
    },
    {
      "wireTag": 3,
      "tag": "nullable-gpu-adapter-service-completion-v1",
      "wireShape": "null or fresh adapter identity plus compatibility/account settlement state",
      "identity": "one-promise-settlement"
    },
    {
      "wireTag": 4,
      "tag": "gpu-device-service-completion-v1",
      "wireShape": "live device identity plus stable queue/lost identities, or one self-contained ASSIGNED + NOT_ADMITTED service-detached already-lost result whose wrapper settlement requires no lifecycle tombstone",
      "identity": "one-promise-settlement"
    },
    {
      "wireTag": 5,
      "tag": "nullable-gpu-error-service-completion-v1",
      "wireShape": "nullable typed GPUError value after exact scope barrier",
      "identity": "one-promise-settlement"
    },
    {
      "wireTag": 6,
      "tag": "nullable-gpu-adapter-service-completion-v2",
      "wireShape": "null or fresh adapter identity plus a required authenticated serviceDetachedExpired u8; zero retains a live service attachment and credits, one denotes a post-positive-commit close settlement with no retained service object, credits, or provider handle",
      "identity": "one-promise-settlement"
    }
  ],
  "completeLimitNames": [
    "maxTextureDimension1D",
    "maxTextureDimension2D",
    "maxTextureDimension3D",
    "maxTextureArrayLayers",
    "maxBindGroups",
    "maxBindGroupsPlusVertexBuffers",
    "maxBindingsPerBindGroup",
    "maxDynamicUniformBuffersPerPipelineLayout",
    "maxDynamicStorageBuffersPerPipelineLayout",
    "maxSampledTexturesPerShaderStage",
    "maxSamplersPerShaderStage",
    "maxStorageBuffersPerShaderStage",
    "maxStorageBuffersInVertexStage",
    "maxStorageBuffersInFragmentStage",
    "maxStorageTexturesPerShaderStage",
    "maxStorageTexturesInVertexStage",
    "maxStorageTexturesInFragmentStage",
    "maxUniformBuffersPerShaderStage",
    "maxUniformBufferBindingSize",
    "maxStorageBufferBindingSize",
    "minUniformBufferOffsetAlignment",
    "minStorageBufferOffsetAlignment",
    "maxVertexBuffers",
    "maxBufferSize",
    "maxVertexAttributes",
    "maxVertexBufferArrayStride",
    "maxInterStageShaderVariables",
    "maxColorAttachments",
    "maxColorAttachmentBytesPerSample",
    "maxComputeWorkgroupStorageSize",
    "maxComputeInvocationsPerWorkgroup",
    "maxComputeWorkgroupSizeX",
    "maxComputeWorkgroupSizeY",
    "maxComputeWorkgroupSizeZ",
    "maxComputeWorkgroupsPerDimension",
    "maxImmediateSize"
  ]
} as const;

const generated = createExecutableWebGpuCodecs(
  WEBGPU_EXECUTABLE_CODEC_MANIFEST,
  WEBGPU_OBJECT_KIND_TAGS,
);

export const WEBGPU_EXECUTABLE_CODECS_FOR_INJECTION = generated.bundle;
export const WEBGPU_EXECUTABLE_CODEC_TEST_SUPPORT = generated.testSupport;
