// Generated by generate-webgpu-production-plan.mjs; do not edit.
// The route table is production input, but navigator.gpu remains gated
// until a separately generated executable codec bundle validates it.
export const WEBGPU_PRODUCTION_PLAN = {
  "schema": "ibex/webgpu-production-wrapper-plan/1",
  "profileId": "exact-webgpu-v1-draft",
  "scopeId": "native-triangle-phase-1a-v1",
  "maxPayloadBytes": 16777216,
  "codecReadiness": "generated-injection-only-native-decoder-absent",
  "digests": {
    "operationSet": "ba939cdb05e89cb5243317e6836465e3612b25d8e02f49a94187064b972830e7",
    "semanticProgramSet": "ecb999ed815c17184598f83bf3f64702bf050ff31fbd4c2326b68cac74f09058",
    "runtimeRouting": "5b1244d55a739e1c7999c2f88213ab440d55573fcbda96a939c53f49ef5afc28",
    "webgpuCVocabulary": "9e4905a3ea6f48bb3921e17567863c68823d604033a3d56ae31269255f445079",
    "projection": "504727fb1b490ef876bea3676066097cb0b3a4601fa8ed7b2bbd9caf55732a82"
  },
  "activeRouteSubset": {
    "scopeId": "native-triangle-phase-1a-v1",
    "operationCount": 25,
    "operationIds": [
      "GPU.getPreferredCanvasFormat",
      "GPU.requestAdapter",
      "GPUAdapter.requestDevice",
      "GPUCanvasContext.configure",
      "GPUCanvasContext.getConfiguration",
      "GPUCanvasContext.getCurrentTexture",
      "GPUCanvasContext.unconfigure",
      "GPUCommandEncoder.beginRenderPass",
      "GPUCommandEncoder.finish",
      "GPUDevice.createCommandEncoder",
      "GPUDevice.createRenderPipeline",
      "GPUDevice.createShaderModule",
      "GPUDevice.destroy",
      "GPUDevice.features",
      "GPUDevice.limits",
      "GPUDevice.lost",
      "GPUDevice.popErrorScope",
      "GPUDevice.pushErrorScope",
      "GPUDevice.queue",
      "GPUQueue.submit",
      "GPURenderPassEncoder.draw",
      "GPURenderPassEncoder.end",
      "GPURenderPassEncoder.setPipeline",
      "GPUTexture.createView",
      "GPUTexture.destroy"
    ]
  },
  "stagedWorkloadClosure": {
    "scopeId": "typegpu-workloads-native-staging-v1",
    "status": "audited-not-routable-not-installed",
    "supportClaim": "none",
    "nativeExecutionEvidence": "none-recording-provider-is-inventory-only",
    "source": {
      "path": "tests/gpu/typegpu-workload-closure-v1.json",
      "sha256": "3ae28e76c09783fd1dc4b28670661c9a97a158888c272f943a9dcb46b16dbdb0"
    },
    "typegpuVersion": "0.11.9",
    "operationCount": 51,
    "additionalOperationCount": 30,
    "additionalOperations": [
      {
        "operationId": "GPUBuffer.destroy",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUBuffer.getMappedRange",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUBuffer.mapAsync",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUBuffer.mapState",
        "memberKind": "property",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUBuffer.unmap",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUBuffer.usage",
        "memberKind": "property",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUCommandEncoder.beginComputePass",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUCommandEncoder.clearBuffer",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUCommandEncoder.copyBufferToBuffer",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUCommandEncoder.copyTextureToTexture",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUComputePassEncoder.dispatchWorkgroups",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUComputePassEncoder.end",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUComputePassEncoder.setBindGroup",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUComputePassEncoder.setPipeline",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUDevice.createBindGroup",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUDevice.createBindGroupLayout",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUDevice.createBuffer",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUDevice.createComputePipeline",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUDevice.createPipelineLayout",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUDevice.createSampler",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUDevice.createTexture",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUQueue.copyExternalImageToTexture",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUQueue.writeBuffer",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUQueue.writeTexture",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPURenderPassEncoder.setBindGroup",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPURenderPassEncoder.setVertexBuffer",
        "memberKind": "method",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUTexture.dimension",
        "memberKind": "property",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUTexture.format",
        "memberKind": "property",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUTexture.height",
        "memberKind": "property",
        "disposition": "staged-unroutable-no-prototype-member"
      },
      {
        "operationId": "GPUTexture.width",
        "memberKind": "property",
        "disposition": "staged-unroutable-no-prototype-member"
      }
    ],
    "properties": [
      "GPUBuffer.mapState",
      "GPUBuffer.usage",
      "GPUDevice.features",
      "GPUDevice.limits",
      "GPUDevice.queue",
      "GPUTexture.dimension",
      "GPUTexture.format",
      "GPUTexture.height",
      "GPUTexture.width"
    ],
    "constants": [
      "GPUBufferUsage.COPY_DST",
      "GPUBufferUsage.COPY_SRC",
      "GPUBufferUsage.MAP_READ",
      "GPUBufferUsage.STORAGE",
      "GPUBufferUsage.UNIFORM",
      "GPUBufferUsage.VERTEX",
      "GPUMapMode.READ",
      "GPUShaderStage.COMPUTE",
      "GPUShaderStage.FRAGMENT",
      "GPUShaderStage.VERTEX",
      "GPUTextureUsage.COPY_DST",
      "GPUTextureUsage.COPY_SRC",
      "GPUTextureUsage.RENDER_ATTACHMENT",
      "GPUTextureUsage.STORAGE_BINDING",
      "GPUTextureUsage.TEXTURE_BINDING"
    ],
    "hostExtensions": [
      "CanvasHandle.context",
      "CanvasHandle.invalidate",
      "CanvasHandle.onDamage",
      "CanvasHandle.onFrame",
      "FrameLease.getCurrentTexture",
      "FrameLease.submit",
      "globalThis.cancelAnimationFrame",
      "globalThis.createImageBitmap",
      "globalThis.fetch",
      "globalThis.requestAnimationFrame"
    ],
    "blockers": [
      "ordered-logical-semantic-program",
      "executable-public-and-service-codecs",
      "matching-native-service-decoder-and-provider-method",
      "generated-capsec-edge-and-supported-target-cell",
      "native-conformance-and-platform-evidence"
    ],
    "publicSurfaceRule": "members-remain-absent-until-all-blockers-close-no-throwing-stubs",
    "embeddedCodecRule": "EMBEDDED_EXECUTABLE_WEBGPU_CODECS-remains-undefined"
  },
  "routes": [
    {
      "operationId": "GPU.getPreferredCanvasFormat",
      "wireId": 1287763171,
      "interfaceName": "GPU",
      "memberName": "getPreferredCanvasFormat",
      "memberKind": "method",
      "dispatchClass": "wrapper-local",
      "logicalExecutionKind": "wrapper-local",
      "resultTiming": "synchronous-return",
      "providerSubmission": "none",
      "receiverHandleKind": null,
      "wrapperAllocatedTargetHandleKind": null,
      "resultHandleKind": null,
      "serviceReceiverProjection": {
        "source": "not-carried",
        "kind": null,
        "flags": 0,
        "objectIdSource": null,
        "objectGenerationSource": null
      },
      "publicArgumentCodec": "none-v1",
      "serviceArgumentCodec": "none-service-request-v1",
      "serviceCompletionCodec": "none-service-completion-v1",
      "publicResultCodec": "gpu-texture-format-v1",
      "promiseIdentity": "not-carried-wrapper-only"
    },
    {
      "operationId": "GPU.requestAdapter",
      "wireId": 1660448199,
      "interfaceName": "GPU",
      "memberName": "requestAdapter",
      "memberKind": "method",
      "dispatchClass": "provider-promise",
      "logicalExecutionKind": "provider-async",
      "resultTiming": "promise-settlement",
      "providerSubmission": "semantic-call-promise-completion",
      "receiverHandleKind": null,
      "wrapperAllocatedTargetHandleKind": null,
      "resultHandleKind": "GPUAdapter",
      "serviceReceiverProjection": {
        "source": "realm-gpu-singleton",
        "kind": "GPU",
        "flags": 0,
        "objectIdSource": "realmIdentity.realmId",
        "objectGenerationSource": "realmIdentity.realmGeneration"
      },
      "publicArgumentCodec": "gpu-request-adapter-options-v1",
      "serviceArgumentCodec": "gpu-request-adapter-service-request-v1",
      "serviceCompletionCodec": "nullable-gpu-adapter-service-completion-v1",
      "publicResultCodec": "nullable-gpu-adapter-handle-promise-v1",
      "promiseIdentity": "required-nonzero-distinct-from-operation-instance"
    },
    {
      "operationId": "GPUAdapter.requestDevice",
      "wireId": 579563582,
      "interfaceName": "GPUAdapter",
      "memberName": "requestDevice",
      "memberKind": "method",
      "dispatchClass": "provider-promise",
      "logicalExecutionKind": "provider-async",
      "resultTiming": "promise-settlement",
      "providerSubmission": "semantic-call-promise-completion",
      "receiverHandleKind": "GPUAdapter",
      "wrapperAllocatedTargetHandleKind": null,
      "resultHandleKind": "GPUDevice",
      "serviceReceiverProjection": {
        "source": "wrapper-full-reference",
        "kind": "GPUAdapter",
        "flags": 0,
        "objectIdSource": "wrapperReceiver.logicalHandle",
        "objectGenerationSource": "wrapperReceiver.lifecycleGeneration"
      },
      "publicArgumentCodec": "gpu-device-descriptor-v1",
      "serviceArgumentCodec": "gpu-request-device-service-request-v1",
      "serviceCompletionCodec": "gpu-device-service-completion-v1",
      "publicResultCodec": "gpu-device-handle-promise-v1",
      "promiseIdentity": "required-nonzero-distinct-from-operation-instance"
    },
    {
      "operationId": "GPUCanvasContext.configure",
      "wireId": 3865035710,
      "interfaceName": "GPUCanvasContext",
      "memberName": "configure",
      "memberKind": "method",
      "dispatchClass": "wrapper-local-service-enqueue",
      "logicalExecutionKind": "wrapper-local-service-enqueue",
      "resultTiming": "synchronous-return-service-enqueued",
      "providerSubmission": "semantic-call-device-timeline",
      "receiverHandleKind": "GPUCanvasContext",
      "wrapperAllocatedTargetHandleKind": null,
      "resultHandleKind": null,
      "serviceReceiverProjection": {
        "source": "wrapper-full-reference",
        "kind": "GPUCanvasContext",
        "flags": 0,
        "objectIdSource": "wrapperReceiver.logicalHandle",
        "objectGenerationSource": "wrapperReceiver.lifecycleGeneration"
      },
      "publicArgumentCodec": "gpu-canvas-configuration-v1",
      "serviceArgumentCodec": "gpu-canvas-configure-service-request-v1",
      "serviceCompletionCodec": "terminal-receipt-service-completion-v1",
      "publicResultCodec": "undefined-v1",
      "promiseIdentity": "zero-non-applicable"
    },
    {
      "operationId": "GPUCanvasContext.getConfiguration",
      "wireId": 3293775739,
      "interfaceName": "GPUCanvasContext",
      "memberName": "getConfiguration",
      "memberKind": "method",
      "dispatchClass": "wrapper-local",
      "logicalExecutionKind": "wrapper-local",
      "resultTiming": "synchronous-return",
      "providerSubmission": "none",
      "receiverHandleKind": "GPUCanvasContext",
      "wrapperAllocatedTargetHandleKind": null,
      "resultHandleKind": null,
      "serviceReceiverProjection": {
        "source": "not-carried",
        "kind": null,
        "flags": 0,
        "objectIdSource": null,
        "objectGenerationSource": null
      },
      "publicArgumentCodec": "none-v1",
      "serviceArgumentCodec": "none-service-request-v1",
      "serviceCompletionCodec": "none-service-completion-v1",
      "publicResultCodec": "nullable-gpu-canvas-configuration-snapshot-v1",
      "promiseIdentity": "not-carried-wrapper-only"
    },
    {
      "operationId": "GPUCanvasContext.getCurrentTexture",
      "wireId": 3157634281,
      "interfaceName": "GPUCanvasContext",
      "memberName": "getCurrentTexture",
      "memberKind": "method",
      "dispatchClass": "wrapper-local-deferred-service",
      "logicalExecutionKind": "wrapper-local-deferred-service",
      "resultTiming": "synchronous-logical-identity-deferred-service",
      "providerSubmission": "none",
      "receiverHandleKind": "GPUCanvasContext",
      "wrapperAllocatedTargetHandleKind": "GPUTexture",
      "resultHandleKind": "GPUTexture",
      "serviceReceiverProjection": {
        "source": "not-carried",
        "kind": null,
        "flags": 0,
        "objectIdSource": null,
        "objectGenerationSource": null
      },
      "publicArgumentCodec": "none-v1",
      "serviceArgumentCodec": "none-service-request-v1",
      "serviceCompletionCodec": "none-service-completion-v1",
      "publicResultCodec": "gpu-texture-handle-v1",
      "promiseIdentity": "zero-non-applicable-sealed-local-timeline-record"
    },
    {
      "operationId": "GPUCanvasContext.unconfigure",
      "wireId": 935342475,
      "interfaceName": "GPUCanvasContext",
      "memberName": "unconfigure",
      "memberKind": "method",
      "dispatchClass": "authority-reducing-service",
      "logicalExecutionKind": "cleanup-service",
      "resultTiming": "synchronous-return-cleanup-enqueued",
      "providerSubmission": "semantic-call-authority-reducing",
      "receiverHandleKind": "GPUCanvasContext",
      "wrapperAllocatedTargetHandleKind": null,
      "resultHandleKind": null,
      "serviceReceiverProjection": {
        "source": "wrapper-full-reference",
        "kind": "GPUCanvasContext",
        "flags": 0,
        "objectIdSource": "wrapperReceiver.logicalHandle",
        "objectGenerationSource": "wrapperReceiver.lifecycleGeneration"
      },
      "publicArgumentCodec": "none-v1",
      "serviceArgumentCodec": "gpu-canvas-unconfigure-service-request-v1",
      "serviceCompletionCodec": "terminal-receipt-service-completion-v1",
      "publicResultCodec": "undefined-v1",
      "promiseIdentity": "zero-non-applicable"
    },
    {
      "operationId": "GPUCommandEncoder.beginRenderPass",
      "wireId": 1908549907,
      "interfaceName": "GPUCommandEncoder",
      "memberName": "beginRenderPass",
      "memberKind": "method",
      "dispatchClass": "wrapper-recording",
      "logicalExecutionKind": "wrapper-recording",
      "resultTiming": "synchronous-recording",
      "providerSubmission": "none",
      "receiverHandleKind": "GPUCommandEncoder",
      "wrapperAllocatedTargetHandleKind": "GPURenderPassEncoder",
      "resultHandleKind": "GPURenderPassEncoder",
      "serviceReceiverProjection": {
        "source": "not-carried",
        "kind": null,
        "flags": 0,
        "objectIdSource": null,
        "objectGenerationSource": null
      },
      "publicArgumentCodec": "gpu-render-pass-descriptor-v1",
      "serviceArgumentCodec": "none-service-request-v1",
      "serviceCompletionCodec": "none-service-completion-v1",
      "publicResultCodec": "gpu-render-pass-encoder-handle-v1",
      "promiseIdentity": "zero-non-applicable-sealed-local-timeline-record"
    },
    {
      "operationId": "GPUCommandEncoder.finish",
      "wireId": 2481184390,
      "interfaceName": "GPUCommandEncoder",
      "memberName": "finish",
      "memberKind": "method",
      "dispatchClass": "wrapper-recording",
      "logicalExecutionKind": "wrapper-recording",
      "resultTiming": "synchronous-recording",
      "providerSubmission": "none",
      "receiverHandleKind": "GPUCommandEncoder",
      "wrapperAllocatedTargetHandleKind": "GPUCommandBuffer",
      "resultHandleKind": "GPUCommandBuffer",
      "serviceReceiverProjection": {
        "source": "not-carried",
        "kind": null,
        "flags": 0,
        "objectIdSource": null,
        "objectGenerationSource": null
      },
      "publicArgumentCodec": "gpu-command-buffer-descriptor-v1",
      "serviceArgumentCodec": "none-service-request-v1",
      "serviceCompletionCodec": "none-service-completion-v1",
      "publicResultCodec": "gpu-command-buffer-handle-v1",
      "promiseIdentity": "zero-non-applicable-sealed-local-timeline-record"
    },
    {
      "operationId": "GPUDevice.createCommandEncoder",
      "wireId": 4055478657,
      "interfaceName": "GPUDevice",
      "memberName": "createCommandEncoder",
      "memberKind": "method",
      "dispatchClass": "service-submit",
      "logicalExecutionKind": "service-enqueue",
      "resultTiming": "synchronous-logical-identity-service-enqueued",
      "providerSubmission": "semantic-call-device-timeline",
      "receiverHandleKind": "GPUDevice",
      "wrapperAllocatedTargetHandleKind": "GPUCommandEncoder",
      "resultHandleKind": "GPUCommandEncoder",
      "serviceReceiverProjection": {
        "source": "wrapper-full-reference",
        "kind": "GPUDevice",
        "flags": 0,
        "objectIdSource": "wrapperReceiver.logicalHandle",
        "objectGenerationSource": "wrapperReceiver.lifecycleGeneration"
      },
      "publicArgumentCodec": "gpu-command-encoder-descriptor-v1",
      "serviceArgumentCodec": "gpu-create-command-encoder-service-request-v1",
      "serviceCompletionCodec": "terminal-receipt-service-completion-v1",
      "publicResultCodec": "gpu-command-encoder-handle-v1",
      "promiseIdentity": "zero-non-applicable"
    },
    {
      "operationId": "GPUDevice.createRenderPipeline",
      "wireId": 2407151159,
      "interfaceName": "GPUDevice",
      "memberName": "createRenderPipeline",
      "memberKind": "method",
      "dispatchClass": "service-submit",
      "logicalExecutionKind": "service-enqueue",
      "resultTiming": "synchronous-logical-identity-service-enqueued",
      "providerSubmission": "semantic-call-device-timeline",
      "receiverHandleKind": "GPUDevice",
      "wrapperAllocatedTargetHandleKind": "GPURenderPipeline",
      "resultHandleKind": "GPURenderPipeline",
      "serviceReceiverProjection": {
        "source": "wrapper-full-reference",
        "kind": "GPUDevice",
        "flags": 0,
        "objectIdSource": "wrapperReceiver.logicalHandle",
        "objectGenerationSource": "wrapperReceiver.lifecycleGeneration"
      },
      "publicArgumentCodec": "gpu-render-pipeline-descriptor-v1",
      "serviceArgumentCodec": "gpu-create-render-pipeline-service-request-v1",
      "serviceCompletionCodec": "terminal-receipt-service-completion-v1",
      "publicResultCodec": "gpu-render-pipeline-handle-v1",
      "promiseIdentity": "zero-non-applicable"
    },
    {
      "operationId": "GPUDevice.createShaderModule",
      "wireId": 599085487,
      "interfaceName": "GPUDevice",
      "memberName": "createShaderModule",
      "memberKind": "method",
      "dispatchClass": "service-submit",
      "logicalExecutionKind": "service-enqueue",
      "resultTiming": "synchronous-logical-identity-service-enqueued",
      "providerSubmission": "semantic-call-device-timeline",
      "receiverHandleKind": "GPUDevice",
      "wrapperAllocatedTargetHandleKind": "GPUShaderModule",
      "resultHandleKind": "GPUShaderModule",
      "serviceReceiverProjection": {
        "source": "wrapper-full-reference",
        "kind": "GPUDevice",
        "flags": 0,
        "objectIdSource": "wrapperReceiver.logicalHandle",
        "objectGenerationSource": "wrapperReceiver.lifecycleGeneration"
      },
      "publicArgumentCodec": "gpu-shader-module-descriptor-v1",
      "serviceArgumentCodec": "gpu-create-shader-module-service-request-v1",
      "serviceCompletionCodec": "terminal-receipt-service-completion-v1",
      "publicResultCodec": "gpu-shader-module-handle-v1",
      "promiseIdentity": "zero-non-applicable"
    },
    {
      "operationId": "GPUDevice.destroy",
      "wireId": 206890944,
      "interfaceName": "GPUDevice",
      "memberName": "destroy",
      "memberKind": "method",
      "dispatchClass": "authority-reducing-service",
      "logicalExecutionKind": "cleanup-service",
      "resultTiming": "synchronous-return-cleanup-enqueued",
      "providerSubmission": "semantic-call-authority-reducing",
      "receiverHandleKind": "GPUDevice",
      "wrapperAllocatedTargetHandleKind": null,
      "resultHandleKind": null,
      "serviceReceiverProjection": {
        "source": "wrapper-full-reference",
        "kind": "GPUDevice",
        "flags": 0,
        "objectIdSource": "wrapperReceiver.logicalHandle",
        "objectGenerationSource": "wrapperReceiver.lifecycleGeneration"
      },
      "publicArgumentCodec": "none-v1",
      "serviceArgumentCodec": "gpu-device-cleanup-service-request-v1",
      "serviceCompletionCodec": "terminal-receipt-service-completion-v1",
      "publicResultCodec": "undefined-v1",
      "promiseIdentity": "zero-non-applicable"
    },
    {
      "operationId": "GPUDevice.features",
      "wireId": 3810427763,
      "interfaceName": "GPUDevice",
      "memberName": "features",
      "memberKind": "property",
      "dispatchClass": "wrapper-property-read",
      "logicalExecutionKind": "wrapper-local",
      "resultTiming": "synchronous-stable-property",
      "providerSubmission": "none",
      "receiverHandleKind": "GPUDevice",
      "wrapperAllocatedTargetHandleKind": null,
      "resultHandleKind": null,
      "serviceReceiverProjection": {
        "source": "not-carried",
        "kind": null,
        "flags": 0,
        "objectIdSource": null,
        "objectGenerationSource": null
      },
      "publicArgumentCodec": "none-v1",
      "serviceArgumentCodec": "none-service-request-v1",
      "serviceCompletionCodec": "none-service-completion-v1",
      "publicResultCodec": "gpu-supported-features-snapshot-v1",
      "promiseIdentity": "not-carried-wrapper-only"
    },
    {
      "operationId": "GPUDevice.limits",
      "wireId": 363717510,
      "interfaceName": "GPUDevice",
      "memberName": "limits",
      "memberKind": "property",
      "dispatchClass": "wrapper-property-read",
      "logicalExecutionKind": "wrapper-local",
      "resultTiming": "synchronous-stable-property",
      "providerSubmission": "none",
      "receiverHandleKind": "GPUDevice",
      "wrapperAllocatedTargetHandleKind": null,
      "resultHandleKind": null,
      "serviceReceiverProjection": {
        "source": "not-carried",
        "kind": null,
        "flags": 0,
        "objectIdSource": null,
        "objectGenerationSource": null
      },
      "publicArgumentCodec": "none-v1",
      "serviceArgumentCodec": "none-service-request-v1",
      "serviceCompletionCodec": "none-service-completion-v1",
      "publicResultCodec": "gpu-supported-limits-snapshot-v1",
      "promiseIdentity": "not-carried-wrapper-only"
    },
    {
      "operationId": "GPUDevice.lost",
      "wireId": 892795326,
      "interfaceName": "GPUDevice",
      "memberName": "lost",
      "memberKind": "property",
      "dispatchClass": "wrapper-property-read",
      "logicalExecutionKind": "wrapper-local",
      "resultTiming": "stable-promise-property",
      "providerSubmission": "none",
      "receiverHandleKind": "GPUDevice",
      "wrapperAllocatedTargetHandleKind": null,
      "resultHandleKind": null,
      "serviceReceiverProjection": {
        "source": "not-carried",
        "kind": null,
        "flags": 0,
        "objectIdSource": null,
        "objectGenerationSource": null
      },
      "publicArgumentCodec": "none-v1",
      "serviceArgumentCodec": "none-service-request-v1",
      "serviceCompletionCodec": "none-service-completion-v1",
      "publicResultCodec": "gpu-device-lost-stable-promise-v1",
      "promiseIdentity": "not-carried-wrapper-only"
    },
    {
      "operationId": "GPUDevice.popErrorScope",
      "wireId": 2687703037,
      "interfaceName": "GPUDevice",
      "memberName": "popErrorScope",
      "memberKind": "method",
      "dispatchClass": "provider-promise",
      "logicalExecutionKind": "provider-async",
      "resultTiming": "promise-settlement-after-scope-barrier",
      "providerSubmission": "semantic-call-promise-completion",
      "receiverHandleKind": "GPUDevice",
      "wrapperAllocatedTargetHandleKind": null,
      "resultHandleKind": null,
      "serviceReceiverProjection": {
        "source": "wrapper-full-reference",
        "kind": "GPUDevice",
        "flags": 0,
        "objectIdSource": "wrapperReceiver.logicalHandle",
        "objectGenerationSource": "wrapperReceiver.lifecycleGeneration"
      },
      "publicArgumentCodec": "none-v1",
      "serviceArgumentCodec": "gpu-pop-error-scope-service-request-v1",
      "serviceCompletionCodec": "nullable-gpu-error-service-completion-v1",
      "publicResultCodec": "nullable-gpu-error-promise-v1",
      "promiseIdentity": "required-nonzero-distinct-from-operation-instance"
    },
    {
      "operationId": "GPUDevice.pushErrorScope",
      "wireId": 1311136574,
      "interfaceName": "GPUDevice",
      "memberName": "pushErrorScope",
      "memberKind": "method",
      "dispatchClass": "wrapper-local-service-enqueue",
      "logicalExecutionKind": "wrapper-local-service-enqueue",
      "resultTiming": "synchronous-return-service-enqueued",
      "providerSubmission": "semantic-service-timeline",
      "receiverHandleKind": "GPUDevice",
      "wrapperAllocatedTargetHandleKind": null,
      "resultHandleKind": null,
      "serviceReceiverProjection": {
        "source": "wrapper-full-reference",
        "kind": "GPUDevice",
        "flags": 0,
        "objectIdSource": "wrapperReceiver.logicalHandle",
        "objectGenerationSource": "wrapperReceiver.lifecycleGeneration"
      },
      "publicArgumentCodec": "gpu-error-filter-v1",
      "serviceArgumentCodec": "gpu-push-error-scope-service-request-v1",
      "serviceCompletionCodec": "terminal-receipt-service-completion-v1",
      "publicResultCodec": "undefined-v1",
      "promiseIdentity": "zero-non-applicable"
    },
    {
      "operationId": "GPUDevice.queue",
      "wireId": 1949537636,
      "interfaceName": "GPUDevice",
      "memberName": "queue",
      "memberKind": "property",
      "dispatchClass": "wrapper-property-read",
      "logicalExecutionKind": "wrapper-local",
      "resultTiming": "synchronous-stable-property",
      "providerSubmission": "none",
      "receiverHandleKind": "GPUDevice",
      "wrapperAllocatedTargetHandleKind": null,
      "resultHandleKind": "GPUQueue",
      "serviceReceiverProjection": {
        "source": "not-carried",
        "kind": null,
        "flags": 0,
        "objectIdSource": null,
        "objectGenerationSource": null
      },
      "publicArgumentCodec": "none-v1",
      "serviceArgumentCodec": "none-service-request-v1",
      "serviceCompletionCodec": "none-service-completion-v1",
      "publicResultCodec": "gpu-queue-handle-v1",
      "promiseIdentity": "not-carried-wrapper-only"
    },
    {
      "operationId": "GPUQueue.submit",
      "wireId": 308839175,
      "interfaceName": "GPUQueue",
      "memberName": "submit",
      "memberKind": "method",
      "dispatchClass": "service-submit",
      "logicalExecutionKind": "service-enqueue",
      "resultTiming": "synchronous-return-service-enqueued",
      "providerSubmission": "semantic-call-device-timeline",
      "receiverHandleKind": "GPUQueue",
      "wrapperAllocatedTargetHandleKind": null,
      "resultHandleKind": null,
      "serviceReceiverProjection": {
        "source": "wrapper-full-reference",
        "kind": "GPUQueue",
        "flags": 0,
        "objectIdSource": "wrapperReceiver.logicalHandle",
        "objectGenerationSource": "wrapperReceiver.lifecycleGeneration"
      },
      "publicArgumentCodec": "gpu-command-buffer-handle-sequence-v1",
      "serviceArgumentCodec": "gpu-sealed-command-program-sequence-service-request-v1",
      "serviceCompletionCodec": "terminal-receipt-service-completion-v1",
      "publicResultCodec": "undefined-v1",
      "promiseIdentity": "zero-non-applicable"
    },
    {
      "operationId": "GPURenderPassEncoder.draw",
      "wireId": 3054695767,
      "interfaceName": "GPURenderPassEncoder",
      "memberName": "draw",
      "memberKind": "method",
      "dispatchClass": "wrapper-recording",
      "logicalExecutionKind": "wrapper-recording",
      "resultTiming": "synchronous-recording",
      "providerSubmission": "none",
      "receiverHandleKind": "GPURenderPassEncoder",
      "wrapperAllocatedTargetHandleKind": null,
      "resultHandleKind": null,
      "serviceReceiverProjection": {
        "source": "not-carried",
        "kind": null,
        "flags": 0,
        "objectIdSource": null,
        "objectGenerationSource": null
      },
      "publicArgumentCodec": "gpu-draw-arguments-v1",
      "serviceArgumentCodec": "none-service-request-v1",
      "serviceCompletionCodec": "none-service-completion-v1",
      "publicResultCodec": "undefined-v1",
      "promiseIdentity": "zero-non-applicable-sealed-local-timeline-record"
    },
    {
      "operationId": "GPURenderPassEncoder.end",
      "wireId": 1724778411,
      "interfaceName": "GPURenderPassEncoder",
      "memberName": "end",
      "memberKind": "method",
      "dispatchClass": "wrapper-recording",
      "logicalExecutionKind": "wrapper-recording",
      "resultTiming": "synchronous-recording",
      "providerSubmission": "none",
      "receiverHandleKind": "GPURenderPassEncoder",
      "wrapperAllocatedTargetHandleKind": null,
      "resultHandleKind": null,
      "serviceReceiverProjection": {
        "source": "not-carried",
        "kind": null,
        "flags": 0,
        "objectIdSource": null,
        "objectGenerationSource": null
      },
      "publicArgumentCodec": "none-v1",
      "serviceArgumentCodec": "none-service-request-v1",
      "serviceCompletionCodec": "none-service-completion-v1",
      "publicResultCodec": "undefined-v1",
      "promiseIdentity": "zero-non-applicable-sealed-local-timeline-record"
    },
    {
      "operationId": "GPURenderPassEncoder.setPipeline",
      "wireId": 551383281,
      "interfaceName": "GPURenderPassEncoder",
      "memberName": "setPipeline",
      "memberKind": "method",
      "dispatchClass": "wrapper-recording",
      "logicalExecutionKind": "wrapper-recording",
      "resultTiming": "synchronous-recording",
      "providerSubmission": "none",
      "receiverHandleKind": "GPURenderPassEncoder",
      "wrapperAllocatedTargetHandleKind": null,
      "resultHandleKind": null,
      "serviceReceiverProjection": {
        "source": "not-carried",
        "kind": null,
        "flags": 0,
        "objectIdSource": null,
        "objectGenerationSource": null
      },
      "publicArgumentCodec": "gpu-render-pipeline-handle-v1",
      "serviceArgumentCodec": "none-service-request-v1",
      "serviceCompletionCodec": "none-service-completion-v1",
      "publicResultCodec": "undefined-v1",
      "promiseIdentity": "zero-non-applicable-sealed-local-timeline-record"
    },
    {
      "operationId": "GPUTexture.createView",
      "wireId": 1846872529,
      "interfaceName": "GPUTexture",
      "memberName": "createView",
      "memberKind": "method",
      "dispatchClass": "service-submit",
      "logicalExecutionKind": "service-enqueue",
      "resultTiming": "synchronous-logical-identity-service-enqueued",
      "providerSubmission": "semantic-call-device-timeline",
      "receiverHandleKind": "GPUTexture",
      "wrapperAllocatedTargetHandleKind": "GPUTextureView",
      "resultHandleKind": "GPUTextureView",
      "serviceReceiverProjection": {
        "source": "wrapper-full-reference",
        "kind": "GPUTexture",
        "flags": 0,
        "objectIdSource": "wrapperReceiver.logicalHandle",
        "objectGenerationSource": "wrapperReceiver.lifecycleGeneration"
      },
      "publicArgumentCodec": "gpu-texture-view-descriptor-v1",
      "serviceArgumentCodec": "gpu-create-texture-view-service-request-v1",
      "serviceCompletionCodec": "terminal-receipt-service-completion-v1",
      "publicResultCodec": "gpu-texture-view-handle-v1",
      "promiseIdentity": "zero-non-applicable"
    },
    {
      "operationId": "GPUTexture.destroy",
      "wireId": 2933046788,
      "interfaceName": "GPUTexture",
      "memberName": "destroy",
      "memberKind": "method",
      "dispatchClass": "authority-reducing-service",
      "logicalExecutionKind": "cleanup-service",
      "resultTiming": "synchronous-return-cleanup-enqueued",
      "providerSubmission": "semantic-call-authority-reducing",
      "receiverHandleKind": "GPUTexture",
      "wrapperAllocatedTargetHandleKind": null,
      "resultHandleKind": null,
      "serviceReceiverProjection": {
        "source": "wrapper-full-reference",
        "kind": "GPUTexture",
        "flags": 0,
        "objectIdSource": "wrapperReceiver.logicalHandle",
        "objectGenerationSource": "wrapperReceiver.lifecycleGeneration"
      },
      "publicArgumentCodec": "none-v1",
      "serviceArgumentCodec": "gpu-texture-cleanup-service-request-v1",
      "serviceCompletionCodec": "terminal-receipt-service-completion-v1",
      "publicResultCodec": "undefined-v1",
      "promiseIdentity": "zero-non-applicable"
    }
  ]
} as const;
