// @generated by bun run generate:capsec-runtime-projection; do not edit.
// @ref LLP 0029#2-executable-layout-stub-envelope-footer — generated constants pin only runtime-relevant CapSec semantics
pub const CAPSEC_RUNTIME_PROJECTION_SCHEMA: &str = "ibex/capsec-runtime-projection/1";
pub const CAPSEC_RUNTIME_PROJECTION_DOMAIN: &str = "ibex:capsec-runtime-projection:1";
pub const CAPSEC_RUNTIME_PROJECTION_DIGEST: &str =
    "sha256-Ccg_eLrjLTw4XgdPYC3BQJYSTZryHWvoJMFg-HY2acQ";

#[cfg(test)]
mod tests {
    #[test]
    fn generated_capsec_runtime_projection_digest_matches_bytes() {
        let bytes = include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/vendored-generated/capsec-runtime-projection.canonical.json"
        ));
        let text = std::str::from_utf8(bytes).unwrap();
        let value = capsec_semantics::strict_json::parse_strict(text).unwrap();
        assert_eq!(
            capsec_semantics::canonical::to_jcs_bytes(&value).unwrap(),
            bytes
        );
        assert_eq!(value["schema"], super::CAPSEC_RUNTIME_PROJECTION_SCHEMA);
        assert_eq!(
            capsec_semantics::digest::compute_domain_digest(
                super::CAPSEC_RUNTIME_PROJECTION_DOMAIN,
                &value,
                &[],
            )
            .unwrap(),
            super::CAPSEC_RUNTIME_PROJECTION_DIGEST,
        );
    }
}
