// @generated by bun run generate:compiled-environment-profile; do not edit.
// @ref LLP 0029#4-compiled-mode-authority — the stub pins the reviewed environment consumer taxonomy
pub const COMPILED_ENVIRONMENT_PROFILE_SCHEMA: &str = "ibex/compiled-environment-profile/1";
pub const COMPILED_ENVIRONMENT_PROFILE_DOMAIN: &str = "ibex:compiled-environment-profile:1";
pub const COMPILED_ENVIRONMENT_PROFILE_DIGEST: &str =
    "sha256-nm2iRsVawi9RGQoIEnHijR7G5NPk7Mk-Czhpw-LR1H0";
pub const COMPILED_ENVIRONMENT_PROFILE_RELEASE_ELIGIBLE: bool = true;

#[cfg(test)]
mod tests {
    #[test]
    fn generated_compiled_environment_profile_digest_matches_bytes() {
        let bytes = include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/vendored-generated/compiled-environment-profile.canonical.json"
        ));
        let text = std::str::from_utf8(bytes).unwrap();
        let value = capsec_semantics::strict_json::parse_strict(text).unwrap();
        assert_eq!(
            capsec_semantics::canonical::to_jcs_bytes(&value).unwrap(),
            bytes
        );
        assert_eq!(value["schema"], super::COMPILED_ENVIRONMENT_PROFILE_SCHEMA);
        assert_eq!(
            capsec_semantics::digest::compute_domain_digest(
                super::COMPILED_ENVIRONMENT_PROFILE_DOMAIN,
                &value,
                &[],
            )
            .unwrap(),
            super::COMPILED_ENVIRONMENT_PROFILE_DIGEST,
        );
    }
}
